- security/strongswan/pkg-plist
@rbgarga: I think it's better to submit this downstream. There's too much red tape upstream!
> Fix gcm.conf.sample file in plist

- sysutils/pfSense-pkg-Service_Watchdog/files/usr/local/pkg/servicewatchdog.inc
This stops a "dashboard crash dump" that is not very informative (it would be nice if it gave a reason as well as quoting the line number of the call to servicewatchdog_cron_job). No idea why this is not a problem in 2.2.5 - I guess the newer PHP and associated ini now gives a warning if a function is called with seemingly missing parameter(s).
You can do whatever to bump the version number if you wish :)
Crash report begins.  Anonymous machine information:
amd64
10.2-STABLE
FreeBSD 10.2-STABLE #228 54cf5d1(devel): Mon Dec  7 15:57:12 CST 2015     root@pfs23-amd64-builder:/usr/home/pfsense/pfsense/tmp/obj/usr/home/pfsense/pfsense/tmp/FreeBSD-src/sys/pfSense
Crash report details:
PHP Errors:
[08-Dec-2015 11:23:16 Asia/Kathmandu] PHP Stack trace:
[08-Dec-2015 11:23:16 Asia/Kathmandu] PHP …
> servicewatchdog_cron_job declare default parameter value

- net/pfSense-pkg-OpenBGPD/Makefile
- net/pfSense-pkg-OpenBGPD/files/usr/local/pkg/openbgpd.inc
- net/pfSense-pkg-OpenBGPD/files/usr/local/pkg/openbgpd.xml
- net/pfSense-pkg-OpenBGPD/files/usr/local/pkg/openbgpd_groups.xml
- net/pfSense-pkg-OpenBGPD/files/usr/local/pkg/openbgpd_neighbors.xml
- net/pfSense-pkg-OpenBGPD/files/usr/local/share/pfSense-pkg-OpenBGPD/info.xml
- net/pfSense-pkg-OpenBGPD/files/usr/local/www/openbgpd_raw.php
- net/pfSense-pkg-OpenBGPD/files/usr/local/www/openbgpd_status.php
- nuke various PBI junk
- no need to add user/group any more
- nuke usage of net.inet.ip.ipsec_in_use (https://redmine.pfsense.org/issues/5370)
> OpenBGPD - remove obsolete pre-2.3 stuff

- sysutils/pfSense-pkg-Cron/files/usr/local/pkg/cron.inc
Not bumping version now, there are still some bootstrap changes pending for https://redmine.pfsense.org/issues/5571
> cron - Nuke obsolete stuff

- net/pfSense-pkg-pfBlockerNG/Makefile
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.sh
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl_easylist.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl_lists.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_top20.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_v4lists.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_v6lists.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/share/pfSense-pkg-pfBlockerNG/info.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_alerts.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_log.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_threats.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_update.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/www/index.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/widgets/include/widget-pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/widgets/javascript/pfblockerng.js
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
- net/pfSense-pkg-pfBlockerNG/pkg-descr
There are still some issues with pkg.php and pkg_edit.php that need to be resolved. It will not affect functionality, as they are mostly cosmetic issues.
Redmine Issue:
https://redmine.pfsense.org/issues/5618
> pfBlockerNG Bootstrap conversion

- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc
* Add missing $g global setting.
* Adjust Installation messages to suit new pkg installation code.
* Remove '-cgi' from php command, causing issues with max_execution_time
* Add/Change syslog notice messages.
> pfBlockerNG - Improve Installation and other fixes

- net/pfSense-pkg-Quagga_OSPF/Makefile
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd.xml
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd_interfaces.xml
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd_raw.xml
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/share/pfSense-pkg-Quagga_OSPF/info.xml
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/www/status_ospfd.php
this my first PR for packages. hopefully i didn't miss anything.
> quagga initial boostrap conv

- net-mgmt/pfSense-pkg-softflowd/pkg-descr
> softflowd - Fix whitespace in pkg-descr

- www/pfSense-pkg-squid/files/usr/local/pkg/squid_antivirus.inc
> squid - fix clamd path startup script creation

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy.xml
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_htmllist.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/share/pfSense-pkg-haproxy-devel/info.xml
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_files.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pool_edit.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pools.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_stats.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_templates.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/widgets/widgets/haproxy.widget.php
- net/pfSense-pkg-haproxy-devel/pkg-descr
haproxy-devel, use new print_apply_box function, and cleanup / small syntax changes, pkg 0.41
> haproxy-devel, use new print_apply_box function, and cleanup / small syntax changes, pkg 0.41

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
- net/pfSense-pkg-haproxy/Makefile
- net/pfSense-pkg-haproxy/files/usr/local/pkg/haproxy/haproxy.inc
haproxy, fix 'host contains' should use hdr_sub instead of hdr_dir in config
> haproxy, fix 'host contains' should use hdr_sub instead of hdr_dir in config

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_sid_mgmt.php
This package update addresses the following user reported bugs in the initial Bootstrap conversion of the Snort GUI package.
1. PASS LIST, HOME NET, EXTERNAL NET and SUPPRESS LIST drop-downs not populating with available list names on SNORT INTERFACES tab, and existing value from an old config are not shown when the package is upgraded.
2. DEFAULT values are missing from the drop-downs for HOME NET, EXTERNAL NET, PASS LIST and SUPPRESS LIST.
3. Not able to select alternate interfaces on ALERTS tab.
4. Wrong short description for checkbox control label on SID MGMT tab.
> Snort 3.2.9.1_3 Bootstrap Conversion Bug Fixes

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_ip_reputation.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_browser.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
This update for the Suricata GUI package addresses some reported bugs in the Bootstrap conversion.
**Bug Fixes**
1. Unable to select alternate interfaces for display on the ALERTS tab.
2. "Add to Suppress" and "Remove from Blocked" icons not working when clicked on ALERTS tab.
3. Selected interface not working properly on LOGS VIEW tab and not updating log contents when changed.
4. Interface name missing in title of IP REP tab.
5. Table columns not properly hiding overflow text with ellipsis on RULES tab.
6. Fix auto-suggest errors with Alias on PASS LIST EDIT page.
7. Fix invalid references to 'Snort' on INTERFACES tab.
8. Fix HTML validation errors on various pages due to extraneous markup tags.
> Suricata 2.1.9.1 _5 - Bug fixes for Bootstrap conversion

- security/snort/Makefile
- security/snort/distinfo
- security/snort/files/patch-spoink-integration.diff
- security/snort/files/snort.in
- security/snort/pkg-plist
This updates the Snort binary on pfSense 2.3-BETA to version 2.9.8.0 to sync with upstream.  Release notes for 2.9.8.0 can be found on the Snort.org web site here: 
https://www.snort.org/downloads/snort/release_notes_2.9.8.0.txt
This pfSense version of Snort contains a custom _alert-pf_ output plugin to implement IP address blocking using pf firewall system calls.
> Snort 2.9.8.0 binary update

- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_post_install.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_blocked.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interface_logs.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_log_mgmt.php
- security/pfSense-pkg-snort/files/usr/local/www/widgets/javascript/snort_alerts.js
- security/pfSense-pkg-snort/files/usr/local/www/widgets/widgets/snort_alerts.widget.php
This update corrects a few more GUI bugs from the recent Bootstrap conversion of Snort.
**Code Fixes:**
1. Stats log filename incorrect in drop-down on LOGS VIEW tab.
2. Receive system log error "open() "_/usr/local/www/javascript/base64.js_" failed from LOGS VIEW tab.
3. Settings not saving on LOGS MGMT tab.
4. Alerts Widget does not auto-update and does not display friendly interface names.
5. Add VIEW RULES button to RULES tab to allow viewing of raw rules content for selected category.
6. Improve feedback on UPDATES tab when updating rules via a temporary workaround.
7. Style footer of blocked IPs table on BLOCKED tab to "bg-info".
8. Fix up errant newlines in post-install code and tidy up status messages.
9. Fix Snort auto-start failure after upgrade or reinstall.
> pfSense-pkg-snort 3.2.9.1_6 -- more Bootstrap bug fixes and binary update to 2.9.8.0

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_mgmt.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/widgets/javascript/suricata_alerts.js
- security/pfSense-pkg-suricata/files/usr/local/www/widgets/widgets/suricata_alerts.widget.php
This Suricata GUI package update fixes a few more discovered Bootstrap conversion bugs.  See commit history for details.
> pfSense-pkg-suricata 2.1.9.1_7 -- a few more Bootstrap-related bug fixes

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/widgets/javascript/suricata_alerts.js
This update corrects a pair of typos (missing closing quote on strings) in the _suricata_alerts.js_ JavaScript file used in the Alerts widget.  The missing quotes cause the Dashboard Alerts widget to not auto-update.
> pfSense-pkg-suricata_2.1.9.1_8 - Fix typo in Suricata Alerts widget JavaScript

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_barnyard.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This update corrects a few more issues discovered after the initial Bootstrap conversion of the Suricata package.  Some default values were not being recognized, and several _Form_Select_ fields had incorrectly structured arrays as their data source resulting in the field failing to properly reflect previously saved data on the INTERFACE SETTINGS and GLOBAL SETTINGS tabs.  On the BARNYARD2 tab, an incorrect help text was fixed on a textbox control.
> pfSens- pkg-suricata 2.1.9.1_9 -- Fix a few more Bootstrap conversion issues

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata.xml
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php
- security/pfSense-pkg-suricata/files/usr/local/www/widgets/widgets/suricata_alerts.widget.php
- security/pfSense-pkg-suricata/files/var/db/suricata/sidmods/dropsid-sample.conf
- security/pfSense-pkg-suricata/pkg-plist
This package update adds Netmap Inline IPS support to the Suricata GUI and corrects a few lingering Bootstrap conversion bugs.
> pfSense-pkg-suricata-3.0 -- Update to 3.0 GUI with Netmap Inline IPS Support

- sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
Make the status monitoring settings panel collapsible with page load state configurable in general setup associated panels show/hide.
Replace Update button with refresh icon on title bar.
Requires pfSense pull request # 2722 Status Monitoring - Settings Panel Collapsible.
https://github.com/pfsense/pfsense/pull/2722
> Status Monitoring - Settings Panel Collapsible

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_import_aliases.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_libhtp_policy_engine.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_browser.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_mgmt.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_os_policy_engine.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules_flowbits.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_suppress.php
This update corrects a number of issues identified during user testing of the new Bootstrap-converted inline IPS mode package.
**Bug Fixes**
1. Help text under Enable checkbox on SID MGMT tab is incorrect.
2. Icons are missing from several buttons on the FLOW/STREAM and APP PARSERS tabs.
3. Update Info Block icons at bottom of INTERFACES tab to show start, restart and stop icons.
4. When IPS mode is Inline, hide Pass List drop-down on INTERFACE SETTINGS tab since it is not used in IPS mode inline.
5. Adjust icons on Flowbits Rules view page to match Snort and widen the column for displaying SID.
6. Change RULES tab to match Snort.  Put View rules button next to drop-down and change to buttons in Overrides section.
7. Fix many logic issues in implementation of new _dropsid.conf_ support on …
> pfSense-pkg-suricata-3.0_1 - More Bootstrap and other bug fixes

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_etiqrisk_update.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php
This update corrects some user-reported bugs and some more Bootstrap conversion issues.
**Bug Fixes**
1. Rules auto-managed by SID MGMT tab files are not tagged correctly on the RULES tab.
2. IQRisk IP Reputation files not downloading for users with subscription code.
3. Icons indicating rule GID:SID added to Supress Lists get duplicated when IPs are the same on ALERTS tab.
4. Snort VRT rules checkboxes not auto-disabled when IPS-Policy is selected on CATEGORIES tab.
5. PCRE selection of SIDs not working correctly for auto-SID management.
> pfSense-pkg-suricata 3.0_2 - Fix user-reported issues and a few other things

- net/pfSense-pkg-pfBlockerNG/Makefile
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.sh
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl_easylist.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl_lists.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_extra.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_sync.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_top20.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_v4lists.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_v6lists.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_alerts.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_alerts_ar.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_log.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_threats.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_update.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/www/index.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/widgets/javascript/pfblockerng.js
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
* Add TLSv1.1 to cURL SSL Options
* Improve 'Max daily download failure threshold' feature
* Improve function pfbng_text_area_decode() add $mode variable to account for '#' comment lines in DNSBL Suppression Alias
* Improve dnsbl_suppression() function
* 'Advanced In/Outbound Firewall Rules' - Force any Invert Source/Destination Alias to use 'Alias Native' settings
* Improve GZIP archive extraction function
* Re-factor Tracker IDs. (Convert all unique Alias details (via ascii table number) and return a 10 digit tracker ID)
If a duplicate Tracker ID is found, default to a pre-determined Tracker ID format starting with '1700000010'
* When DNSBL is enabled, but all Aliases/Feeds are 'Disabled', clear existing DNSBL Unbound Database properly.
* Improve Proofpoint/Emerging Threats IQRisk …
> pfBlockerNG - version 2.0.8

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_ip_reputation.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
This update addresses the following issues.
**Bug Fixes**
1. IP Reputation enable checkbox not "sticking" on IP REP tab.
2. Typo in function name causes crash dump when updating rule sets.
3. Displaying large rule set on RULES tab results in PHP memory error and blank page in browser.
1. When inline IPS mode is selected, the Netmap subsystem requires that Hardware Checksum, Hardware TCP Segmentation and Hardware Large Receive Offloading all be disabled.  Suricata now checks for this when inline IPS mode is selected for an interface, and a notification message is printed for the user if all three parameters are not disabled.  These parameters are located on the **System > Advanced > Networking** tab of pfSense.
> pfSense-pkg-suricata-3.0_5 - Bug fix update

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_blocked.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/widgets/widgets/snort_alerts.widget.php
This update corrects a few issues in the Snort package GUI.  No new features are added in this release.
**Bug Fixes**
1. Removed unnecessary code in the Snort Alerts widget that was causing a silent JavaScript error.
2. Eliminated the use of "echo" statements and cleaned up the code for the RULES tab.
3. Removed an extraneous newline character printed when auto-refresh was enabled on the BLOCKS tab.
4. Fixed the auto-refresh on the ALERTS tab so that it actually works now.
5. Added the required runtime dependency on Barnyard2 to the GUI package Makefile so that the Barnyard2 binary will be installed along with Snort.
6. Added code to reload the UPDATES tab page when finished downloading and installing updated rules so the new values are displayed.
> pfSense-pkg-snort-3.2.9.1_8 GUI Package Update

- net/pfSense-pkg-haproxy-devel/Makefile
haproxy-devel, switch to ports/net/haproxy-devel (currently 1.7 version)
> haproxy-devel, switch to ports/net/haproxy-devel (currently 1.7 version)

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
This update corrects two user-reported bugs in the Snort GUI package.
**Bug Fixes**
1. IP Reputation Lists added on the IPREP tab always get saved as Blacklist files even when adding using the Add Whitelist button.
2. For users with XMLRPC Sync enabled, a missing include file causes an undefined function error during the XMLRPC sync at package installation.
> pfSense-pkg-snort-3.2.9.1_9 -- Bug Fix Update

- sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
Saying "data series" again seemed redundant.
> Info Block Wording to be More Concise

- sysutils/pfSense-Status_Monitoring/Makefile
- sysutils/pfSense-Status_Monitoring/files/usr/local/www/rrd_fetch_json.php
this also needs to be looked at for "queues" & "queuedrops" => I don't have a clue what unit they are supposed to have.
> status/monitoring fix tooltip unit_acronyms

- sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
Info boxes don't have close buttons - the "i" icon is used to open and close the box.
> Redmine #6106 Remove close button from info box

- sysutils/pfSense-pkg-Service_Watchdog/files/usr/local/pkg/servicewatchdog.inc
when processing the Service Watchdog list.
Leave the permanent update of the list for when the user next edits Service Watchdog settings.
This is an alternate version of https://github.com/pfsense/FreeBSD-ports/pull/105
> Change apinger to dpinger on the fly

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_browser.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_mgmt.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_suppress.php
- security/pfSense-pkg-suricata/files/usr/local/www/widgets/widgets/suricata_alerts.widget.php
This update corrects a number of user-reported bugs in the GUI package.
**Bug Fixes**
1. The ALERTS, BLOCKS,  LOGS VIEW and SID MGMT tabs are missing some or all breadcrumbs in the header.
2. Rule suppression using "by address" icons on the ALERTS tab results in garbled HTML resulting in the tooltip text being incorrectly displayed instead the appropriate icon.
3. Disabling of rules by clicking the icon on the ALERTS tab not working and resulting in just a page reload.
4. Suppress List deletion is allowed for an assigned list, but it should be prevented and a warning message displayed instead.
5. Dashboard Widget not properly handling multiple interfaces (row sorting gets off).
6. Editing/saving of Custom Rules not working on RULES tab.
7. Pass Lists created on the PASS LIST tab are not …
> pfSense-pkg-suricata-3.0_6 -- Bug Fix Update

- net/pfSense-pkg-pfBlockerNG/Makefile
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl.xml
* Fix package de-install function
* Fix 'States Removal' - only parse 'Deny|Reject' types, and exclude any "!" Not Rules.
> pfBlockerNG - version 2.0.11

- net/pfSense-pkg-pfBlockerNG/Makefile
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.sh
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_alerts.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_log.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_update.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/www/index.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
* Floating Rule Generation - Check if XML tag is empty.
* Fix for https://redmine.pfsense.org/issues/6246
* Make timestamps consistent (DNSBL)
* When a failed download marker is found, bypass Cron Hour validation, and re-attempt download
* Alerts Tab - Fix typo in 'Auto-Resolve'
* Log Tab - While downloading a selected log file, exit on completion, otherwise HTML code will get appended to the downloaded log file.
* Update Tab - Fix issue with "headers already sent" PHP error
* Update Tab - Fix whitespace
* widget - Scroll failed downloads instead of previous Line limit defined by $pfb['maxfails'] variable.
> pfBlockerNG - version 2.0.12

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This update for the Suricata GUI package addresses the following reported bugs.
**Bug Fixes**
1. Typo in list name parameter results in an inability to see and select custom IP lists for the HOME_NET or EXTERNAL_NET settings on the INTERFACE SETTINGS tab.
2. Dashboard Suricata Alerts widget not always properly restored following a package reinstall.
3. An extra text file is leftover in the rules directory following removal of the package.
> pfSense-pkg-suricata-3.0_7 -- Bug fix update

- net/pfSense-pkg-pfBlockerNG/Makefile
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_update.php
* Fix for #6229 - When $pfb['interval'] is not defined, default the variable to '1'. This variable was introduced over a year ago, but if the user does not hit "save" in the pfBlockerNG General Tab, this variable does not get created.  In 2.2.x, the error was never noticed; however, in 2.3, the PHP errors are more verbose. So when a user upgrades from 2.2.x to 2.3.x, this variable, when not defined, will cause issues.
* Fix for DNSBL. When disabled, it wasn't removing the pf table correctly.  "There were error(s) loading the rules: /tmp/rules.debug"
> pfBlockerNG - version 2.0.14

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/pkg_haproxy_tabs.inc
- net/pfSense-pkg-haproxy/Makefile
- net/pfSense-pkg-haproxy/files/usr/local/pkg/haproxy/pkg_haproxy_tabs.inc
haproxy, haproxy-devel, pkg0.47, fix show tabs for non admin users that have permissions
> haproxy, haproxy-devel, pkg0.47, fix show tabs for non admin users that have permissions

- net-mgmt/pfSense-pkg-nrpe/Makefile
- net-mgmt/pfSense-pkg-nrpe/files/etc/inc/priv/nrpe2.priv.inc
- net-mgmt/pfSense-pkg-nrpe/files/pkg-deinstall.in
- net-mgmt/pfSense-pkg-nrpe/files/pkg-install.in
- net-mgmt/pfSense-pkg-nrpe/files/usr/local/pkg/nrpe.xml
- net-mgmt/pfSense-pkg-nrpe/files/usr/local/pkg/nrpe2.inc
- net-mgmt/pfSense-pkg-nrpe/files/usr/local/share/pfSense-pkg-nrpe/info.xml
- net-mgmt/pfSense-pkg-nrpe/pkg-descr
- net-mgmt/pfSense-pkg-nrpe/pkg-plist
Hi,
this is the bootstrap port of the NRPE package.
Best
Sven
> Bootstrap Port NRPE

- net/pfSense-pkg-pfBlockerNG/Makefile
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.sh
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_top20.xml
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_alerts.php
* Fix Issue for RamDisk installation on Reboot - https://redmine.pfsense.org/issues/6116 and https://redmine.pfsense.org/issues/6380
* Fix typo - https://redmine.pfsense.org/issues/6368
* Improve DNSBL Suppression function for comment lines
* Improve find_reported_header() function for excluded files
* Write log message to the system log on Reboot
* Suppress 'localhost.localdomain' - added due to SWC Feed
* Fix potential unset() error
* Fix ADBlock EasyPrivacy parse code
* dnsbl.sh - Only start when DNSBL is enabled. Kill all DNSBL pids if multiple found.
* Fix typos in TOP20 Country List
* Add a new Rule Order option
> pfBlockerNG - version 2.0.15

- sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
When localStorage is cleared and you add a right axis field that has units other than the main left axis, the units will be "null" due to the tempKey stripping out the "(right axis)" from the key and thus not finding a match in localStorage.
> Fix null unit on status monitoring graph

- sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
Adjust saved default time period and resolution order.
// Time period setting change applies valid resolutions and selects the default resolution of the time period.
// Time period setting needs to be before resolution so that the time period default doesn't override the page load default resolution.
// Time period setting needs to be before custom start/end date/time so those will be enabled before applying their setting.
Fixes bug 6402
> Status Monitoring - Default Resolution II

- security/snort/Makefile
- security/snort/distinfo
- security/snort/files/snort.in
- security/snort/pkg-descr
- security/snort/pkg-plist
Update Snort binary package to version 2.9.8.3 to match upstream and since version 2.9.8.0 is EOL for  rules updates.
> Bump Snort binary to v2.9.8.3 to sync with upstream.

- sysutils/pfSense-pkg-System_Patches/files/usr/local/www/system_patches.php
When viewing installed patch list on 2.3+ the GitHub commit URLs are quite long and cause the main table to extend beyond the screen boundary. This looks weird and forces you to scroll to access the action buttons.
Seeing the commit URL on the list doesn't add much as far as usability (and it can be seen anyway if needed on the edit page). This patch makes the page display properly.
> Small cosmetic patch to System Patches list view

- net-mgmt/pfSense-pkg-zabbix-agent/Makefile
- net-mgmt/pfSense-pkg-zabbix-agent/files/usr/local/pkg/zabbix-agent-lts.inc
- net-mgmt/pfSense-pkg-zabbix-agent/files/usr/local/pkg/zabbix-agent-lts.xml
- net-mgmt/pfSense-pkg-zabbix-proxy/Makefile
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/pkg/zabbix-proxy-lts.inc
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/pkg/zabbix-proxy-lts.xml
zabbix packages - update to 3.0
Upgrade for zabbix agent and proxy packages
~~Pull TLS commit (cherry-pick) from master~~
Change web gui to TLS related options
> zabbix packages - update to 3.0

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_utils.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pool_edit.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/widgets/widgets/haproxy.widget.php
fix frontend duplication issue, widget permissions and save/load server-state, several code cleanups.
> haproxy-devel, 0.49

- sysutils/pfSense-pkg-apcupsd/Makefile
- sysutils/pfSense-pkg-apcupsd/files/etc/inc/priv/apcupsd.priv.inc
- sysutils/pfSense-pkg-apcupsd/files/pkg-deinstall.in
- sysutils/pfSense-pkg-apcupsd/files/pkg-install.in
- sysutils/pfSense-pkg-apcupsd/files/usr/local/pkg/apcupsd.conf.php
- sysutils/pfSense-pkg-apcupsd/files/usr/local/pkg/apcupsd.inc
- sysutils/pfSense-pkg-apcupsd/files/usr/local/pkg/apcupsd.xml
- sysutils/pfSense-pkg-apcupsd/files/usr/local/pkg/apcupsd_mail.php
- sysutils/pfSense-pkg-apcupsd/files/usr/local/share/pfSense-pkg-apcupsd/info.xml
- sysutils/pfSense-pkg-apcupsd/files/usr/local/www/apcupsd_status.php
- sysutils/pfSense-pkg-apcupsd/pkg-descr
- sysutils/pfSense-pkg-apcupsd/pkg-plist
Converting old package to 2.3 structure.
> apcupsd - add package to 2.3

- sysutils/pfSense-pkg-apcupsd/Makefile
- sysutils/pfSense-pkg-apcupsd/files/usr/local/pkg/apcupsd.inc
There are two calls on rc.start_packages, sync_package() and start_service(), 
and on the sync of apcupsd the package is restarted.
This PR prevents apcupsd of being started two times on booting.
Problem reported on:
https://forum.pfsense.org/index.php?topic=70830.msg646565#msg646565
Those logs just showed up when using pcnet protocol. 
Also:
- Fix php_deinstall_apcupsd()
- Bump version
> apcupsd - prevents apcupsd of being started two times

- net/pfSense-pkg-ntopng/Makefile
- net/pfSense-pkg-ntopng/files/usr/local/pkg/ntopng.inc
- net/pfSense-pkg-ntopng/files/usr/local/pkg/ntopng.xml
- net/pfSense-pkg-ntopng/files/usr/local/www/ntopng_redirect.php
- net/pfSense-pkg-ntopng/pkg-plist
Ntopng now uses the same http(s) configuration as the webgui. Necessary following the introduction of HSTS.
> Support https

- dns/pfSense-pkg-bind9/Makefile
- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.inc
- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.xml
Hi,
this commit fixes the bug that the daemon is not recognized if IPv4 and IPv6 are both enabled.
Best
Sven
> Bind9 Error on ipv4 and ipv6 enabled restart the running daemon is not recognized

- sysutils/pfSense-pkg-System_Patches/Makefile
- sysutils/pfSense-pkg-System_Patches/files/usr/local/pkg/patches.inc
1) Nested IF statements can be combined
2) Add/remove shellcmd contains logic that only needs to run if the early shellcmd array does/doesn't exist
3) Logs should be non-vague ("...added/removed a shellcmd" is better if it states the command added/removed, and for removal, clarify it removed an existing command)
Re-resubmit, as originally against old pfsense-packages, see pfsense/pfsense-packages#1229, then conflicts prevented merge (PR#47 here)
> System patches logic simplifications (resubmit of PR #47)

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export.php
openvpn-client-export, added a 'save defaults' button and search option in user/certificate list, also moved the export buttons out of the list.
> openvpn-client-export, added a 'save defaults' button and search option

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export.php
openvpn-client-export, fix showing certs/users when no defaults have been saved before
> openvpn-client-export, fix showing certs/users when no defaults have been saved before

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/share/pfSense-pkg-haproxy-devel/info.xml
haproxy-devel, request syslogsocket in chroot environment, fix 'transparent-client-ip' function using ipfw on 2.4
> haproxy-devel, request syslogsocket in chroot environment, fix 'transparent-client-ip' function using ipfw on 2.4

- sysutils/pfSense-pkg-syslog-ng/Makefile
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng.inc
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng.xml
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng_advanced.xml
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/www/syslog-ng_log_viewer.php
- Prevent opening edit mode on the _DEFAULT entry when clicking the "Advanced" tab; makes it impossible to do anything without modifying the URL manually in the browser.
- Allow overriding default values (Feature #4548)
- Better defaults/options for log viewer (Bug #6547)
- Fix log rotation with bzip2
> syslog-ng - multiple fixes

- www/pfSense-pkg-squid/files/usr/local/pkg/squid_reverse.inc
Properly break out $reverse_ip config onto two lines in order to avoid the Squid configuration limit of 1024 characters per line.
> Squid - Correct conf creation for reverse IPs

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export.php
Exporting clients for revoked certificates makes no sense.
> Do not list client exports for revoked certificates.

- ftp/pfSense-pkg-tftpd/Makefile
- ftp/pfSense-pkg-tftpd/files/etc/inc/priv/tftpd.priv.inc
- ftp/pfSense-pkg-tftpd/files/pkg-deinstall.in
- ftp/pfSense-pkg-tftpd/files/pkg-install.in
- ftp/pfSense-pkg-tftpd/files/usr/local/pkg/tftpd.inc
- ftp/pfSense-pkg-tftpd/files/usr/local/pkg/tftpd.xml
- ftp/pfSense-pkg-tftpd/files/usr/local/share/pfSense-pkg-tftpd/info.xml
- ftp/pfSense-pkg-tftpd/pkg-descr
- ftp/pfSense-pkg-tftpd/pkg-plist
Rather than porting the old tftp package, I created a new package for the much more versatile and fast tftp-hpa daemon. This is my first attempt at packaging, so please advise about any problems with the code. The package did compile, install and work correctly on a fresh pfSense 2.3.2 install.
> add pfSense tftp package for tftp-hpa daemon

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/pkg/openvpn-client-export.inc
- security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export.php
Add support for PKCS#11 certificate store (e. g. SafeNet eToken).
Only tested with Microsoft Windows client, not with Viscosity.
> PKCS#11 support added

- sysutils/pfSense-Status_Monitoring/files/usr/local/www/rrd_fetch_json.php
Monitoring graphs last sample being zero
If there is no RRD data sample for the current minute then the graph, and last and minimum data values will be zero, and average skewed,  in certain circumstances.  Such as resolution 1 minute and graph loaded prior to the current minute RRD sample being made.  Similar for the first minute of other resolutions and custom time periods.
This commit corrects this by restricting the 'end' option to no later than the RRD last sample time.
> Status / Monitoring - Last Sample Zero II

- net/pfSense-pkg-Quagga_OSPF/Makefile
- net/pfSense-pkg-Quagga_OSPF/files/etc/inc/priv/quagga_ospfd.priv.inc
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd.inc
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd.xml
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/share/pfSense-pkg-Quagga_OSPF/info.xml
- net/pfSense-pkg-Quagga_OSPF/pkg-descr
Slightly modified patch from https://redmine.pfsense.org/issues/3303 to handle the checkbox-based configuration in old versions of the package. (I'd rather avoid renaming the badly chosen config variable name and upgrading the config on upgrade.)
While here, also tweaked the package description (conflicts should be handled by pkg now) and removed some copy-paste junk from privs.
> Allow quagga ospf stub, not so stub and totally stub areas (Feature #3303)

- sysutils/pfSense-pkg-AutoConfigBackup/Makefile
- sysutils/pfSense-pkg-AutoConfigBackup/files/usr/local/pkg/autoconfigbackup.inc
- sysutils/pfSense-pkg-AutoConfigBackup/files/usr/local/pkg/autoconfigbackup.xml
- sysutils/pfSense-pkg-AutoConfigBackup/files/usr/local/www/autoconfigbackup_backup.php
Make it possible to disable the package without uninstalling (e.g. to prevent timeout delays when there's no WAN connection). Also, it is now possible to delete the stored credentials from config.xml. 
Some tweaks to avoid completely bogus "success" message for Bug #6950 while here. Now it should at least report failure when the write_config() failed due to the user having user-config-readonly privilege, instead of always claiming it worked.
> Disable Auto Config Backup feature (Feature #6951), add some tweaks for savemsg (Bug #6950)

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
Add checkbox to suricata_interfaces_edit.php to log payload data with eve.json alerts (inspired by this forum post https://forum.pfsense.org/index.php?topic=112587.0) and corresponding updates to suricata_generate_yaml.php to properly generate suricata.yaml with new options
> Suricata eve alert payload logging

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export.php
openvpn-client-export, fix, show local-users and their certificates also when a user above them has their certificate revoked
> openvpn-client-export, fix, show local-users and their certificates also when a user above them has their certificate revoked

- sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
To fix:
```
[2.4.0-BETA][root@pf24.localdomain]/tmp/scripts: php generate-privdefs.php /
--Locating www php files--
--Gathering privilege metadata--
warning: tag PRIV has malformed data in '//usr/local/www/status_monitoring.php'
warning: tag PRIV has malformed data in '//usr/local/www/status_monitoring.php'
warning: tag PRIV has malformed data in '//usr/local/www/status_monitoring.php'
warning: tag PRIV has malformed data in '//usr/local/www/status_monitoring.php'
warning: tag PRIV has malformed data in '//usr/local/www/status_monitoring.php'
--Generating privilege definitions--
```
Note: The priv data for this page is actually in pfSense-Status_Monitoring.priv.inc
> Remove PRIV block in status_monitoring.php

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
This update corrects a couple of minor bugs noticed with the Suricata package on pfSense 2.4-BETA. These fixes are compatible with the Suricata package on pfSense 2.3.x as well.
**Bug Fixes:**
1.  The auto-update of the GeoIP database should default to enabled on the GLOBAL SETTINGS tab. On a fresh install when the underlying parameter is empty (non-existent) in the _config.xml_ file, the checkbox on this tab remains unchecked (or off) when it should show checked (or on).
2.  When restarting Suricata using the icon on the INTERFACES tab, Suricata will stop but may fail to restart due to the presence of a PID file in _/var/run_. When stopping Suricata, ensure the PID file for the interface is removed if it still exists in _/var/run_ after Suricata is stopped.
> pfSense-pkg-suricata-3.0_12 - bug fixes

- sysutils/pfSense-pkg-System_Patches/Makefile
- sysutils/pfSense-pkg-System_Patches/files/usr/local/www/system_patches_edit.php
Note: this code is happily backward-compatible with pfSense base versions that do not have breadcrumb links code - $pglinks is never used in those versions, so will sit and happily do nothing.
> Add breadcrumb links for system_patches_edit

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_mgmt.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
This update of the Suricata GUI package adds three new features, restores Pass List functionality when running with inline IPS mode enabled, and corrects four bugs.
1. The RULES tab has an action column with an icon to indicate if the rule action is alert or drop.  Clicking the icon allows toggling the rule action via a user override.  The GID:SID of the rule along with the user overriden action are both stored in the firewall config for Suricata and used to set the rule action when the enforcing rules file for the interface instance is written (the _suricata.rules_ file located in the _/rules_ directory of the interface).
2. The list of rules displayed on the RULES tab can now be filtered by state (enabled or disabled) to help with identifying enabled or disabled rules. …
> pfSense-pkg-suricata-3.1.2 - Update for bug fixes and new features

- www/pfSense-pkg-squid/Makefile
- www/pfSense-pkg-squid/files/usr/local/pkg/squid_antivirus.inc
Make the minutes random (avoids some mirrors overload issues) and the update frequency more obvious.
> Squid - improve ClamAV DB updates cronjob handling

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_ip_reputation.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php
This update to the Suricata GUI package corrects issues with implementation of default Pass Lists when running Suricata with inline IPS Mode enabled.  A couple of other minor bugs are also fixed.
**Bug Fixes**
1. Remove automatic inclusion of all locally-attached networks in the default Pass List when using IPS mode.  This had the unintended side-effect of essentially whitelisting all traffic to and from local hosts.
2. Added the capability to completely disable use of the default Pass List when running with inline IPS Mode.  Formerly, the default Pass List would be used when no custom list was specified.
3. Remove automatic inclusion of the WAN interface IP address in the default Pass List when using IPS mode.  This had the unintended side-effect of essentially whitelist all inbound NAT …
> pfSense-pkg-suricata-3.1.2 0 -- Pass List implementation fix

- sysutils/pfSense-Status_Monitoring/Makefile
- sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
enable_rrd_graphing() does not actually return a status. It "just works".
Better to just give a specific message (enabled or disabled) rather than make an irrelevant attempt to use get_std_save_message()
> Fixup RRD graphing enabled/disabled message

- ftp/pfSense-pkg-tftpd/Makefile
- ftp/pfSense-pkg-tftpd/files/etc/inc/priv/tftpd.priv.inc
- ftp/pfSense-pkg-tftpd/files/usr/local/pkg/tftpd.inc
- ftp/pfSense-pkg-tftpd/files/usr/local/pkg/tftpd.xml
- ftp/pfSense-pkg-tftpd/files/usr/local/www/tftp_files.php
- ftp/pfSense-pkg-tftpd/pkg-plist
- Add option to bind to a single IP
- Add option to force IPv4 only
- Add option to specify the maximum permitted block size
- Re-add backup/restore/upload/delete functionality
- Remove useless custom_add_php_command
- Remove unneeded includes
- Use a PID file for the service
- Remove useless filter_configure() call
- Nuke the shipped startup script on install
- Fix custom_php_{install,deinstall}_command
> pfSense-pkg-tftpd package improvements

- net-mgmt/pfSense-pkg-darkstat/Makefile
- net-mgmt/pfSense-pkg-darkstat/files/usr/local/pkg/darkstat.xml
- Fix service handling
- Improve bootstrap conversion
- Remove useless custom_add_php_command
- Input validation clean up
> darkstat package improvements

- sysutils/pfSense-upgrade/Makefile
- sysutils/pfSense-upgrade/files/pfSense-upgrade
Add GitSync options support.
Minimal, Diff, Show Files, Show Command, Dry Run
(cherry picked from commit ea134477c3fa793333c4253838bd42a09eea9dc7)
> System Update Settings - GitSync Options

- net/pfSense-pkg-freeradius2/Makefile
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradius.inc
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradius.xml
Service handling fixes:
- Remove unwanted freeradius restart on install/upgrade
This breaks things due to restarting the service multiple times - once here and more times when custom_php_resync_config_command is run on install, which in turn runs freeradius_settings_resync() which restarts the service, and then freeradius_users_resync() runs which restarts the service yet again.
- Add an argument to skip service restart to freeradius_settings_resync() function
- Do not restart service twice on resync
- Do not restart on boot
- Attempt to fix XMLRPC sync which was restarting the service four times for a good measure, WTF.
Other fixes:
- Remove an evil recursive chown call on /var/log screwing up logdir permissions for things like squid, clamav, redis... Same unwanted recursive chown would …
> freeradius service handling fixes (Bug #6404), fix chown handling and various bugs

- net/pfSense-pkg-freeradius2/Makefile
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradius.inc
- Honor $restart_svc in freeradius_clients_resync() - missed in previous round of fixes
- Add $restart_svc argument to freeradius_allcertcnf_resync() for consistency and in case it's needed in future (currently only used by freeradiuscerts.xml)
- Make the checks syntax consistent across functions for readability
- Improve some comments
> freeradius service handling fixes (Bug #6404) - round #2

- www/pfSense-pkg-squid/Makefile
- www/pfSense-pkg-squid/files/usr/local/pkg/squid.inc
- www/pfSense-pkg-squid/files/usr/local/pkg/squid.xml
This implements a couple of options for configuring SSL MITM interception, as discussed @ https://forum.pfsense.org/index.php?topic=123461.0
- Splice Whitelist, Bump Otherwise
This is the current code, still used by default.
- Splice All
Will splice everything. No need to install CA certificate on clients, and lets SquidGuard do its job. No content filtering (AV) possible, obviously.
- Custom
Use advanced custom options. Tinker with it as you wish. Unsupported, if you break it, fix it yourself.
Tweak a couple of descriptions/comments and fix some tags while here.
> Squid - implement SSL MITM mode options

- security/pfSense-pkg-tinc/Makefile
- security/pfSense-pkg-tinc/files/usr/local/pkg/tinc.inc
https://redmine.pfsense.org/issues/7173
@rbgarga  Switched this to use ```pkg_``` as an interface group reserved for packages, since dash is clearly not viable character here. Whatever is agreed on here, needs a couple of other commits in pfSense itself.
> tinc - fix interface group handling, avoid rename() producing a crash report on save due to non-empty directory

- net/pfSense-pkg-freeradius2/Makefile
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradius.inc
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradius.xml
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradiusauthorizedmacs.xml
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradiuscerts.xml
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradiusclients.xml
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradiuseapconf.xml
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradiusinterfaces.xml
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradiusmodulesldap.xml
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradiussettings.xml
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradiussqlconf.xml
- net/pfSense-pkg-freeradius2/files/usr/local/www/freeradius_view_config.php
Code style/other fixes
- Fix code style, whitespace, indentation
- Make things much more readable by leaving out the  middle part of the```?:``` ternary operator
- Replace exec() with mwexec() 
- Use native PHP functions where possible/suitable
- Replace horrible code using echo redirection from shell with file_put_contents()
- Use openvpn_create_dhparams() to create DH params file
- Do not use code like ```exec("cd $foo; bar")```
- Use full paths to executables in mwexec()
- Improve comments
- Etc. ...
Others:
- Add prominent deprecation warnings to 'Certificates' and 'EAP' tabs regarding the redundant FreeRADIUS Cert Manager feature. See https://redmine.pfsense.org/issues/7170.
- Fix Bug #6928 - "Access-Reject" not logged in MySQL radpostauth table
> freeradius code style and other fixes

- www/pfSense-pkg-squid/Makefile
- www/pfSense-pkg-squid/files/etc/inc/priv/squid.priv.inc
- www/pfSense-pkg-squid/files/usr/local/pkg/squid.xml
- www/pfSense-pkg-squid/files/usr/local/www/squid_clwarn.php
- www/pfSense-pkg-squid/files/usr/local/www/widgets/widgets/squid_antivirus_status.widget.php
- replace inline base64 images with bootstrap icons
- tidy up tables and remove old styling
- fix squiclamav version detection and use pkg_exec() to get packages' versions in general
- fix version and HTML on squid_clwarn.php page
> Squid - dashboard widget bootstrap facelift + fixes

- sysutils/pfSense-pkg-LCDproc/Makefile
- sysutils/pfSense-pkg-LCDproc/files/usr/local/pkg/lcdproc.inc
- sysutils/pfSense-pkg-LCDproc/files/usr/local/pkg/lcdproc_client.php
- sysutils/pfSense-pkg-LCDproc/files/usr/local/www/packages/lcdproc/lcdproc.php
- sysutils/pfSense-pkg-LCDproc/files/usr/local/www/packages/lcdproc/lcdproc_screens.php
* Adds [extra driver settings needed to support Adafruit LCDs](https://forum.pfsense.org/index.php?topic=124321.0)
* Fixes a [bug in the displaying of load averages](https://forum.pfsense.org/index.php?topic=110177.msg687858#msg687858)
(also bumps the package version from 0.10.3 to 0.10.4)
> Lcdproc update

- www/pfSense-pkg-Lightsquid/Makefile
- www/pfSense-pkg-Lightsquid/files/usr/local/pkg/lightsquid.inc
- www/pfSense-pkg-Lightsquid/files/usr/local/pkg/lightsquid.xml
Clean up the GUI and fix whitespace/indentation while here.
> Lightsquid - make lighttpd listen on IPv6 + GUI cleanup

- net-mgmt/pfSense-pkg-darkstat/Makefile
- net-mgmt/pfSense-pkg-darkstat/files/usr/local/pkg/darkstat.inc
- net-mgmt/pfSense-pkg-darkstat/files/usr/local/pkg/darkstat.xml
- net-mgmt/pfSense-pkg-darkstat/files/usr/local/www/darkstat_redirect.php
- net-mgmt/pfSense-pkg-darkstat/pkg-plist
- Split PHP code out of XML to darkstat.inc
- Make darkstat webgui port configurable
- Add a description tag to XML work around Bug #7178 - impossible to enable the service on pfSense themes otherwise; works properly with Compact-Red)
> darkstat - make port configurable, split PHP from XML, add work around for Bug #7178

- sysutils/pfSense-pkg-apcupsd/Makefile
- sysutils/pfSense-pkg-apcupsd/files/usr/local/pkg/apcupsd.inc
- sysutils/pfSense-pkg-apcupsd/files/usr/local/pkg/apcupsd.xml
This quote from apccontrol explains:
```
[...]
#
[...]
```
Suggested and tested by LucaTo from pfsense forum. Thank you.
> pfSense-pkg-apcupsd - new option for set shutdown behavior

- net-mgmt/pfSense-pkg-darkstat/Makefile
- net-mgmt/pfSense-pkg-darkstat/files/usr/local/pkg/darkstat.inc
- net-mgmt/pfSense-pkg-darkstat/files/usr/local/pkg/darkstat.xml
- net-mgmt/pfSense-pkg-darkstat/files/usr/local/www/darkstat_redirect.php
Hardcoding HTTP still has effect no on people using HTTPS, due to the hardcoded HSTS header in nginx (https://redmine.pfsense.org/issues/6650). Was broken before with ```$myurl```, still exactly same broken now, no regression, except that the port is configurable.
As a workaround, I added a field where people can put their own hostname or IP used for the redirect, instead of the pfSense hostname. Pretty much required for everyone on HTTPS.
> darkstat - Hardcode to HTTP, add optional custom hostname/IP address configuration

- net/pfSense-pkg-Quagga_OSPF/Makefile
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd.inc
Quagga 1.x does not like to be killed with SIGKILL. Try to kill it more gracefully. If everything fails, eventually force a SIGKILL on (re)start because otherwise things breaks completely.
> Quagga_OSPF - Attempt to work around Bug #6305

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_rules.php
See https://github.com/pfsense/pfsense/pull/3495
@bmeeks8 - Still using the pre-bootstrap tables, not touching that now.
> Suricata - remove {fbegin,fend}.inc usage

- www/pfSense-pkg-Lightsquid/Makefile
- www/pfSense-pkg-Lightsquid/files/usr/local/pkg/lightsquid.inc
- Sanitize indentation
- Get rid of a whole slew of incredibly annoying useless defines that were only murking the code
- Avoid rm -rf usage and use rmdir_recursive() instead
- Sort includes and cosmetics
> Lightsquid code style fixes

- sysutils/pfSense-pkg-System_Patches/Makefile
- sysutils/pfSense-pkg-System_Patches/files/usr/local/pkg/patches.inc
- sysutils/pfSense-pkg-System_Patches/files/usr/local/www/system_patches_edit.php
and a little typo in System Patches Edit.
> System Patches ignore unlink of downloaded patch

- dns/pfSense-pkg-bind9/Makefile
- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.inc
- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.xml
- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind_sync.xml
- Add enable checkbox to sync targets
- User port and protocol selection
- Make username configurable for 2.4
- Fix literal IPv6 handling
- Fix HA sync protocol/port handling
- Do some sanity checking before attempting to run XMLRPC sync
- Fix descriptions in XML so that they are actually visible in the GUI, they are not shown with rowhelper fields
> BIND - XMLRPC fixes

- net-mgmt/pfSense-pkg-softflowd/Makefile
- net-mgmt/pfSense-pkg-softflowd/files/etc/inc/priv/softflowd.priv.inc
- net-mgmt/pfSense-pkg-softflowd/files/usr/local/pkg/softflowd.inc
- net-mgmt/pfSense-pkg-softflowd/files/usr/local/pkg/softflowd.xml
- net-mgmt/pfSense-pkg-softflowd/pkg-plist
- Split PHP code to softflowd.inc
- Improve input validation
- Clean up descriptions, set required fields
- Add privileges settings
- Do not double the data in certain setups (https://redmine.pfsense.org/issues/4731#note-6)
- Add enable/disable toggle
BTW, while touching this, could anyone tell me WTH is that ```cleanup_config_softflowd()``` function doing?
> softflowd package cleanup, add privileges settings

- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.inc
BIND does not have a chance to freeze zones and
clean up if it is stopped or restarted with SIGKILL.
SIGTERM is the BIND9 documented way of stopping
named:
https://ftp.isc.org/isc/bind9/cur/9.9/doc/arm/Bv9ARM.ch03.html#signals
SIGKILL is not the right way to stop processes in
rc scripts: http://novosial.org/shell/kill-9/index.html
Discovered this when using dynamic zones and my zones were corrupted every time I made a configuration change (and BIND was restarted by the resync).
> Restart BIND with SIGTERM, not SIGKILL

- www/pfSense-pkg-squid/Makefile
- www/pfSense-pkg-squid/files/usr/local/pkg/squid.inc
- www/pfSense-pkg-squid/files/usr/local/www/widgets/widgets/squid_antivirus_status.widget.php
- Fix the Squid AV widget for systems with /var ramdisk.
- Disable cache digests generation unless we are a sibling to another proxy; avoids pointless periodic Squid freezes which have never been solved upstream.
- Add reason to write_config() calls
> Squid - Fix ClamAV DB location in widget (Bug #7305), cache digests tweaks

- net/pfSense-pkg-cellular/Makefile
- net/pfSense-pkg-cellular/files/usr/local/pkg/cellular.inc
- Use explode() instead of deprecated split()
- Fix input error message to match the actual check
> cellular pkg - Get rid of deprecated split() function

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export.php
- security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export_shared.php
Related to https://github.com/pfsense/pfsense/pull/3629
Part of https://redmine.pfsense.org/issues/7385
> pfSense-pkg-openvpn-client-export - add missing includes

- security/pfSense-pkg-acme/Makefile
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_htmllist.inc
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates.php
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates_edit.php
fix moving certificates with anchor for certificates with a name containing a dot
https://redmine.pfsense.org/issues/7342#note-5
show extra 'detail' fields when tables are drawn in 'edit mode' for a new certificate
https://redmine.pfsense.org/issues/7237
> Acme, fix moving certificates, showing detail fields

- net-mgmt/pfSense-pkg-net-snmp/Makefile
- net-mgmt/pfSense-pkg-net-snmp/files/usr/local/pkg/net-snmp.xml
- ~~Service name must not use hyphens to not get conflicted with [pfSenseHelpers.js](https://github.com/pfsense/pfsense/blob/master/src/usr/local/www/js/pfSenseHelpers.js#L658-L659)~~
- Fix a typo in `snmptrapd` executable name
- Bump PORTREVISION
> pfSense-pkg-net-snmp: Fix services

- dns/pfSense-pkg-bind9/files/usr/local/pkg/pkg_bind.inc
Updated BIND Log location:
From:  diag_logs_resolver.php
To:      status_logs.php?logfile=resolver
Bug Report: https://redmine.pfsense.org/issues/7431
> Update BIND to point to correct Log location

- security/pfSense-pkg-stunnel/Makefile
- security/pfSense-pkg-stunnel/files/etc/inc/priv/stunnel.priv.inc
- security/pfSense-pkg-stunnel/files/pkg-deinstall.in
- security/pfSense-pkg-stunnel/files/pkg-install.in
- security/pfSense-pkg-stunnel/files/usr/local/pkg/stunnel.inc
- security/pfSense-pkg-stunnel/files/usr/local/pkg/stunnel.xml
- security/pfSense-pkg-stunnel/files/usr/local/share/pfSense-pkg-stunnel/info.xml
- security/pfSense-pkg-stunnel/files/usr/local/www/shortcuts/pkg_stunnel.inc
- security/pfSense-pkg-stunnel/pkg-descr
- security/pfSense-pkg-stunnel/pkg-plist
Mostly straight copies of the files from the 2.2 package with the new 2.3 package metadata files.
No attempt has been made to clean up the existing code, notably in security/pfSense-pkg-stunnel/files/usr/local/pkg/stunnel.inc:
- There is code checking for pfsense versions < 2.3 which can probably be deleted
- The gui attempts to render colored text, but since it gets escaped simply renders text like &lt;font color="#AABBCC"&gt;blahblah&lt;/font&gt;.  I couldn't figure out how to get colored text in the status page tables.
I am willing to work on those issues, but since this doesn't seem to have any major issues perhaps it is OK as a first approximation to get the stunnel package working again.  If the pull can't be accepted as is, any pointers on how to fix the above issues would be …
> Add stunnel package for pfSense 2.3

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
**Suricata 3.2.1**
This updates the Suricata package on pfSense to version 3.2.1.  The underlying Suricata binary is also versioned up to 3.2.1.  Some configuration parameters were changed as a result of the update.
**Release Notes:**
1. Suricata 3.2.1 now supports hyperscan for the pattern matcher algorithm.  Hyperscan is a high-performance regex pattern matching library.  Several older pattern matching algorithms were deprecated.  If your existing Suricata configuration is using any pattern matcher algorithm not shown below, the setting will be migrated to "Auto".  If your existing configuration is "AC", then it will be left at that value and you will need to manually change the _Pattern Matcher_ setting on the INTERFACE SETTINGS tab.  The new valid options for Pattern Matching are: …
> pfSense-pkg-suricata-3.2.1

- net-mgmt/pfSense-pkg-net-snmp/Makefile
- net-mgmt/pfSense-pkg-net-snmp/files/usr/local/pkg/net-snmp.inc
- net-mgmt/pfSense-pkg-net-snmp/files/usr/local/pkg/net-snmptrapd.xml
> pfSense-pkg-net-snmp: Add option to not let snmptrapd become a subagent

- security/suricata/files/patch-alert-pf.diff
This update patches the _alert-pf_ custom blocking plugin for pfSense so that it properly registers itself as an Output Packet Module.
> Fix registration of alert-pf blocking plugin to honor Suricata 3.2.x format

- net/pfSense-pkg-freeradius2/Makefile
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradius.inc
- net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradiuseapconf.xml
- net/pfSense-pkg-freeradius2/pkg-message
Also added some messages and input validation regarding EAP certificates here (see https://redmine.pfsense.org/issues/7479).
> FreeRADIUS - put CRL on a new line (Bug #7491), add some messages for missing certificates

- net-mgmt/pfSense-pkg-zabbix-proxy/Makefile
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/pkg/zabbix-proxy-lts.inc
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/pkg/zabbix-proxy-lts.xml
- Add SNMP Trap Monitoring options
- Bump PORTVERSION
> pfSense-pkg-zabbix-proxy: Add SNMP Trap Monitoring options

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/widgets/widgets/haproxy.widget.php
pfSense 2.4 supports potentially multiple copies of a widget on the dashboard. For this, the widget name is no longer just like "haproxy", but is "haproxy-0" (and could be "haproxy-1" etc in future, if haproxy wanted to allow multiple copies).
Make haproxy-devel use the passed-in value of $widgetname to generate the id of the widget panel footer. That works in both 2.3.* and 2.4.
> Make haproxy-devel widget settings open

- GIDs
- UIDs
- net-mgmt/pfSense-pkg-snmptt/Makefile
- net-mgmt/pfSense-pkg-snmptt/files/etc/inc/priv/snmptt.priv.inc
- net-mgmt/pfSense-pkg-snmptt/files/pkg-deinstall.in
- net-mgmt/pfSense-pkg-snmptt/files/pkg-install.in
- net-mgmt/pfSense-pkg-snmptt/files/usr/local/pkg/snmptt.inc
- net-mgmt/pfSense-pkg-snmptt/files/usr/local/pkg/snmptt.ini.php
- net-mgmt/pfSense-pkg-snmptt/files/usr/local/pkg/snmptt.xml
- net-mgmt/pfSense-pkg-snmptt/files/usr/local/pkg/snmptt_conf.xml
- net-mgmt/pfSense-pkg-snmptt/files/usr/local/share/pfSense-pkg-snmptt/info.xml
- net-mgmt/pfSense-pkg-snmptt/pkg-descr
- net-mgmt/pfSense-pkg-snmptt/pkg-plist
- net-mgmt/snmptt/Makefile
- net-mgmt/snmptt/files/newsyslog-snmptt.conf
- net-mgmt/snmptt/files/snmptt.in
- net-mgmt/snmptt/pkg-plist
> SNMPTT (SNMP Trap Translator) is an SNMP trap handler written in Perl
> for use with the Net-SNMP. Easy to setup and use.
It was mostly used select fields to follow the configuration file pattern, with values "0,1", "0,1,2", "0,1,2,3,4" and "1,2,3,4".
There is more information about the `custom_php_service_status_command` [here](https://gist.github.com/dbaio/d0c5d4f10ca0a6edcc68c3e3702e41e4).
Accepting suggestions in this approach, I couldn't find another package using this custom command.
Cherry picked [this commit](https://github.com/pfsense/FreeBSD-ports/commit/88f5effabf75eff1653c682275a24874f18e0cae).
Thank you.
> Add new package SNMPTT (SNMP Trap Translator)

- net/pfSense-pkg-Quagga_OSPF/Makefile
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/bin/quaggactl
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd.inc
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd.xml
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd_interfaces.xml
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd_raw.xml
- net/pfSense-pkg-Quagga_OSPF/files/usr/local/www/status_ospfd.php
Allows raw config to be entered to enable the use of BGP and OSPFv3 and provides required support to control the daemons.
For users who require both BGP and OSPF this is the only way of accomplishing this. Also some people who are using Quagga elsewhere in their infrastructure, means that they have only one type of BGP config to manage.
Based on work from this pull request
https://github.com/pfsense/pfsense-packages/pull/1258/files
> Enable BGP and OSPFv3

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_barnyard.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_blocked.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_define_servers.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interface_logs.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_preprocessors.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_sid_mgmt.php
This update for the Snort GUI package implements support for the latest 2.9.9.0 version of the Snort binary.  Release Note for Snort 2.9.9.0 can be found here:  [https://www.snort.org/downloads/snort/release_notes_2.9.9.0.txt](url)
**GUI Package New Features:**
None
**GUI Package Bug Fixes:**
1.  When using the download buttons on the ALERTS, BLOCKED and SID MGT tabs, the downloaded files either have HTML appended to them (if downloading individual files) or when downloading a gzip archive it shows as corrupt on Windows.
2.  Redmine Bug #7555, translation data shown in breadcrumb link when no interfaces are defined for Snort and one of the interface settings tabs is selected.
> pfSense-pkg-snort-3.2.9.3 -- Update for Snort 2.9.9.0 binary and GUI bug fixes

- sysutils/pfSense-pkg-Shellcmd/Makefile
- sysutils/pfSense-pkg-Shellcmd/files/usr/local/pkg/shellcmd.inc
shellcmd, dont write the config when no changes where made, it pollutes the config backups
> shellcmd, dont write the config when no changes where made, it pollutes the config backups

- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
Enabling EVE redis output support for suricata. The additional overhead, due to the needed "hiredis" library , is quite small.
Why?
This provides an elegant way to ship eve output towards an ELK stack using redis as a buffer. This method even supports large events which can't be transported trough syslog. For example alerts with packet dump.
Note that the RLIST mode which can be selected in the Webgui is not officially supported yet.
I've just introduced this option to suricata. A PR for it is pending [here](https://github.com/inliniac/suricata/pull/2724).
> Suricata redis support

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This fixes the bug [7278 Suricata Service - Advanced Configuration Pass-Through not working](https://redmine.pfsense.org/issues/7278)
Also fixing a form render error: After saving the "Advanced Configuration Pass-Through" is showing base64 encoded text.
> Bugfix for Bug #7278 Suricata Service - Advanced Configuration Pass-Through not working

- www/pfSense-pkg-squidGuard/Makefile
- www/pfSense-pkg-squidGuard/files/usr/local/www/sgerror.php
Removing code that was allowing to force the squidguard to make a curl HEAD request when squidguard sgerror.php page was requested to show a TAG_BLANK_IMG with 'u' parameter set to a target url and msg parameter containing 'maxlen_'
> Corrects SquidGuard sgerror.php page was allowing curl requests on TAG_BLANK_IMG.

- dns/pfSense-pkg-bind9/Makefile
- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.inc
Previously, the BIND package would blank out the hostname field and always use "@" for either MX or NS records. However, this is an arbitrary limitation. If you want to delegate a sub-domain, then you need to be able to provide a NS record with a hostname. Additionally, providing MX records for hosts is a valid record as well.
This patch continues to allow a blank hostname field (automatically replacing with "@"), so this should be backward compatible for existing users.
> Allow NS/MX records to have hostnames with pfSense-pkg-bind9

- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
why not adding this fields to the custom fields? maybe needs a suboption at the interface or could stay as it is to extend the http eve.json information as default.
> adding extended custom http eve.json fields

- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
As part of preparing the response to the download request we were incorrectly setting the location header and exiting the operation.
This addresses [Bug 7674](https://redmine.pfsense.org/issues/7674).
> Bug #7674 - Issue Downloading Snort Alert Log Download

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_barnyard.php
The logic of the password input type will send a hardcoded '********' post value when the value has not been edited which was not handled. The changes are to escape when the DMYPWD constant is being passed in. Another aspect of this is that when the value has not changed, it needs to be re-encoded to base64 since it was decrypted during page load.
This is to address [Bug-7616](https://redmine.pfsense.org/issues/7616).
> Bug 7616 - Barnyard2 webui configuration updates result in ****** written to the config for the password

- net/pfSense-pkg-freeradius3/Makefile
- net/pfSense-pkg-freeradius3/files/usr/local/pkg/freeradius.inc
The configuration of using the radius server and a single client on
the loopback device should be allowed.  This allows a secure
method for using OTP tokens on a single firewall.
Signed-off-by: Jason Wessel <jason@wesselworks.com>
> pfSense-pkg-freeradius3: Allow 127.0.0.1 for interface selection

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
Suricata can (also) log flow info in EVE, which can be used when analysing with an ELK stack. This change enables this in the interface editor as well as creates the corresponding `YAML`. 
Since enabling this option potentially generates larg(er) log files, including packet capture, the option is disabled by default.
> pfSense-pkg-suricata: Suricata eve flow patch

- net-mgmt/pfSense-pkg-nrpe/Makefile
- net-mgmt/pfSense-pkg-nrpe/files/usr/local/pkg/nrpe2.inc
Hello,
Currently there's no way of easily extending the monitoring within PFSense, if it's not exposed by an existing check_* or via SNMP it's very difficult to be able to check from external monitoring like Nagios. 
If the user has the ability to inject a shell command that gets dropped into the nrpe.conf then you can define new checks pretty easily by adding commands like  `/bin/tcsh -c 'grep ok /path/to/the/statefile/here && exit 0'` into the GUI. It's not exactly the easiest thing for people to do, but it does at least add a seam for extension.
Feedback welcome!
Thanks,
Rob
> NRPE: Allowing user to define custom shell commands

- security/snort/Makefile
- security/snort/files/patch-spoink-integration.diff
This update corrects a bug in the custom blocking plugin for the Snort binary.  Failure to validate that the IP header information in an alerting packet is valid before attempting to insert the IP addressess into the "snort2c" table could cause Signal 11 faults in the Snort binary.  Certain alerts, particularly from the ARP Spoofing detection preprocessor, may not contain valid IP header information.  The IP header information is now validated before attempting to insert the addresses into the "snort2c" table.  Alert packets with empty or invalid IP header information are now ignored by the blocking plugin since it could not do anything useful with them anyway.
> Snort 2.9.9.0_3 -- Bug Fix for custom blocking module

- net/pfSense-pkg-freeradius3/Makefile
- net/pfSense-pkg-freeradius3/files/usr/local/pkg/freeradius.inc
The previous change broke the thing altogether, $policy.mac-addr-regexp is nowhere defined.
```
/usr/local/etc/raddb/policy.d/pfs_custom_policies[2]: Reference "${policy.mac-addr-regexp}" not found
/usr/local/etc/raddb/policy.d/pfs_custom_policies[2]: Parse error expanding ${...} in condition
Errors reading or parsing /usr/local/etc/raddb/radiusd.conf
```
Rewritten per https://wiki.freeradius.org/guide/mac-auth#plain-mac-auth_raddb-policy-conf; also not using any variable there to avoid needless issues with the PHP code.
> net/pfSense-pkg-freeradius3: Fix MAC rewriting policy

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
**Snort GUI Package**
This update fixes the XMLRPC package sync code so that it works in both 2.3 and 2.4 versions of pfSense.
None
**Bug Fixes**
1.  XMLRPC package sync does not work in pfSense 2.4-RC due to changes in the XMLRPC client.
> pfSense-pkg-snort-3.2.9.5_1 -- fix XMLRPC sync to work in both 2.3 and 2.4 pfSense versions

- sysutils/pfSense-pkg-System_Patches/Makefile
- sysutils/pfSense-pkg-System_Patches/files/usr/local/www/system_patches.php
- sysutils/pfSense-pkg-System_Patches/files/usr/local/www/system_patches_edit.php
Part of https://redmine.pfsense.org/issues/204
Also nuke obsolete useless code while here.
>  sysutils/pfSense-pkg-System_Patches: Add reason to write_config() calls

- security/pfSense-pkg-acme/Makefile
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_generalsettings.php
Part of https://redmine.pfsense.org/issues/204
>  security/pfSense-pkg-acme: Add reason to write_config() call

- sysutils/apcupsd/Makefile
- sysutils/apcupsd/files/apcupsd.in
- sysutils/apcupsd/files/patch-platforms_etc_Makefile
- sysutils/apcupsd/files/pkg-message.in
- sysutils/apcupsd/pkg-plist
- sysutils/pfSense-pkg-apcupsd/Makefile
My primary motivation for pulling in the rev 2 package of apcupsd-3.14.14 is the MODBUS USB driver option (I just cherry-picked f7e0540ed53e2225730aa36ddd00b037ad38e369). I wasn't sure if the pfSense-pkg-apcupsd port revision also needed to be bumped up to trigger a rebuild of the package with the updated apcupsd dependency.
CC: @dbaio
> pfSense-pkg-apcupsd: Pull in apcupsd-3.14.14_2

- sysutils/pfSense-pkg-Shellcmd/Makefile
- sysutils/pfSense-pkg-Shellcmd/files/usr/local/pkg/shellcmd.inc
Also remove references to nanobsd while here.
> sysutils/pfSense-pkg-Shellcmd: Fix earlyshellcmd special case for pfSense-pkg-System_Patches

- sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
Based on the [description of the issue](https://forum.pfsense.org/index.php?topic=117036.msg662322#msg662322)  from people that are able to reproduce it (I definitely am not one of them), I added *all* the halved values, to prevent more revisits to the code here.
> pfSense-Status_Monitoring - fix other cases of "unknown" step value (Bug #6860)

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_sync.xml
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This update removes the use of the deprecated _<no_drop_down>_ XML tag on the SYNC tab in the Suricata GUI.  Additional warning messages and help text has been added to alert users of potential limited hardware NIC driver support when selecting IPS Inline Mode operation.
None
**Bug Fixes**
1. Remove use of the deprecated _<no_drop_down>_ XML tag in the code page for the SYNC tab.  This tag is no longer honored after the pfSense conversion to Bootstrap.
2. Add additional help text to the group section, and display a save message warning when saving changes if selecting IPS Inline Mode operation, on the INTERFACE SETTINGS tab.  The user is warned of limited Netmap support in some NIC drivers and the potential for system crashes when selecting Inline IPS Mode operation with …
> pfSense-pkg-suricata-4.0.0_2 - Remove use of deprecated XML code page tag.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_sync.xml
This update removes the use of the deprecated <no_drop_down> XML code page tag on the SYNC tab of the Snort GUI.  The tag's former functionality was removed from pfSense during the Bootstrap conversion.
None
**Bug Fixes**
1.  Remove deprecated <no_drop_down> XML code page tag used in the SYNC tab GUI code.
> pfSense-pkg-snort-3.2.9.5_2 - Remove use of deprecated XML code page tag

- net/pfSense-pkg-freeradius3/Makefile
- net/pfSense-pkg-freeradius3/files/usr/local/pkg/freeradius.inc
- net/pfSense-pkg-freeradius3/files/usr/local/pkg/freeradiusclients.xml
https://redmine.pfsense.org/issues/7836
> FreeRADIUS3: Put client shared secret between single quotes to avoid breaking configuration (Bug #7836)

- www/pfSense-pkg-squidGuard/files/usr/local/pkg/squidguard_configurator.inc
This update is a FIX a issue on set set DATE RANGE on squidguard configurator.
Before, it was not possible to create break dates. The validation mask reported error.
line 285 - This change will fix a typo in a variable
line 1838 - This change will fix the date comparison variable in case of date range
line 1841 - This change will fix the date range comparison
line 1846 - This change is the fix to set date and date range on squidguard TIMES. It will make it possible to create the date range in all possible squidguard patterns.
Now we can have timerange in pfsense's Squidguard configurator.
> Fix SQUIDGUARD DATE RANGE

- net-mgmt/pfSense-pkg-zabbix-agent/Makefile
- net-mgmt/pfSense-pkg-zabbix-agent/files/etc/inc/priv/zabbix-agent.priv.inc
- net-mgmt/pfSense-pkg-zabbix-agent/files/usr/local/pkg/zabbix-agent.inc
- net-mgmt/pfSense-pkg-zabbix-agent/files/usr/local/pkg/zabbix-agent.xml
- net-mgmt/pfSense-pkg-zabbix-agent/files/usr/local/share/pfSense-pkg-zabbix-agent/info.xml
- net-mgmt/pfSense-pkg-zabbix-agent/pkg-plist
- net-mgmt/pfSense-pkg-zabbix-agent22/Makefile
- net-mgmt/pfSense-pkg-zabbix-agent32/Makefile
- net-mgmt/pfSense-pkg-zabbix-agent34/Makefile
- net-mgmt/pfSense-pkg-zabbix-proxy/Makefile
- net-mgmt/pfSense-pkg-zabbix-proxy/files/etc/inc/priv/zabbix-proxy.priv.inc
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/pkg/zabbix-proxy.inc
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/pkg/zabbix-proxy.xml
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/share/pfSense-pkg-zabbix-proxy/info.xml
- net-mgmt/pfSense-pkg-zabbix-proxy/pkg-plist
- net-mgmt/pfSense-pkg-zabbix-proxy22/Makefile
- net-mgmt/pfSense-pkg-zabbix-proxy32/Makefile
- net-mgmt/pfSense-pkg-zabbix-proxy34/Makefile
Bring all versions of Zabbix with Active Support to pfSense.
`net-mgmt/pfSense-pkg-zabbix-agent` and `net-mgmt/pfSense-pkg-zabbix-proxy` Zabbix LTS 3.0 are Master Ports.
Slave Ports:
`net-mgmt/pfSense-pkg-zabbix-agent22` Zabbix LTS 2.2
`net-mgmt/pfSense-pkg-zabbix-agent32` Zabbix Standard 3.2
`net-mgmt/pfSense-pkg-zabbix-agent34` Zabbix Standard 3.4
`net-mgmt/pfSense-pkg-zabbix-proxy22` Zabbix LTS 2.2
`net-mgmt/pfSense-pkg-zabbix-proxy32` Zabbix Standard 3.2
`net-mgmt/pfSense-pkg-zabbix-proxy34` Zabbix Standard 3.4
All packages will share the same config.
Stable LTS release | Release date | End of Full Support*(3 years) | End of Limited Support**(5 years)
-- | -- | -- | --
Zabbix 3.0 | 16 February 2016 | February, 2019 | February, 2021
Zabbix 2.2 | 12 November 2013 | August, 2017 | …
> pfSense-pkg-zabbix-[agent|proxy]: Bring all versions of Zabbix with Active Support to pfSense

- net/pfSense-pkg-pfBlockerNG/Makefile
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.sh
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/www/index.php
* Switch flock() to try_lock()
* Remove conf_mount_{ro,rw} calls
* Add 'Alias type' rules to states removal feature
> pfBlockerNG v2.1.2_1

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
Snort.org distributes three versions of shared-object precompiled rules for FreeBSD.  The versions are for FreeBSD 8.1, FreeBSD 9 and FreeBSD 10.  The former Snort package code defaulted to the 8.1 rules (from way back when) and then tested via a _uname -r_ call to  see if FreeBSD 10 was present.  That worked for older pfSense releases, but with the release of 2.4 and the new FreeBSD 11.x underlying OS, the old code would incorrectly default to FreeBSD 8.1.  This change makes Snort always use the FreeBSD 10 SO rules until such time as Snort.org provides FreeBSD 11 rules.
> Change Snort to always use FreeBSD-10-0 precompiled SO rules in pfSense 2.4.x releases.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_generate_conf.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_global.php
The OpenAppID rules file is maintained by a volunteer contributor.  The pfSense team has agreed to host the OpenAppID rules file archive to increase reliability of the rules file download from users impacted by the geo-blocking policies enforced at the original hosting site in Brazil.
**Updates:**
The URL for the OpenAppID rules archive file now points to http://files.pfsense.org/openappid/.
**Bug Fixes:**
1. Clear out the dynamic_preprocessors sub-directory while rebuilding the _snort.conf_ file for an interface.  This ensures dynamic preprocessor libraries are removed when the corresponding dynamic preprocessor has been disabled in the GUI.  Otherwise, Snort will continue to load the disabled preprocessor so long as the library exists in the dynamic_preprocessors sub-directory.
> Update OpenAppID rules URL in Snort GUI package

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
This updates the URLs used for downloading the Proofpoint ET-Pro and ET-Open rules packages.  Proofpoint recently changed the folder structure on the download site to include the Suricata engine version as part of the rules download URL.
There are no new features or functionality changes in this update.
**Bug Fixes:**
1. Update the URL generation for ET-Pro and ET-Open rules package downloads to reflect recent changes made by Proofpoint.
> Adjust Suricata ET-Pro rules URL based on recent changes by Proofpoint.

- net-mgmt/pfSense-pkg-zabbix-agent/Makefile
- net-mgmt/pfSense-pkg-zabbix-agent/pkg-descr
- net-mgmt/pfSense-pkg-zabbix-proxy/Makefile
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/pkg/zabbix-proxy.inc
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/pkg/zabbix-proxy.xml
- net-mgmt/pfSense-pkg-zabbix-proxy/pkg-descr
When SNMPTrapper is disabled, it is preventing Zabbix Proxy to listen
Active Checks from agents.
Also introduce new fields in web config, `ListenIP` and `ListenPort`.
While here, improve pkg-descr from Agent/Proxy and bump version.
> pfSense-pkg-zabbix: Fix a bug in Zabbix Proxy / Active Checks

- security/pfSense-pkg-tinc/files/usr/local/pkg/tinc.inc
- security/pfSense-pkg-tinc/files/usr/local/pkg/tinc.xml
Quick and dirty tinc support for CARP:
- make tinc a carp plugin
- when we get a rc.carpmaster event, start tinc if not already running
- when we get a rc.backup event, stop tinc if running
TODO: disable the option to launch tinc on a CARP BACKUP node
> tinc support for CARP

- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng.php
Correct a grammar error, “What new” to “What’s new”.
> Pfblockerng grammar error in pfblockerng.php

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php
haproxy-devel
-add support for nbthread option available in haproxy 1.8 version, and add hard-stop-after setting
-use crt-list to specify certificates and certificate specific options regarding client certificates and advanced ssl options.
> haproxy-devel, add gui support for crtlist nbthread hardstop

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_define_vars.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist.php
This update to the Suricata GUI package contains three bug fixes and five new or updated features.  The version is changed to 4.0.3 to match that of the underlying Suricata binary.
1.  Add the SIP_SERVERS variable to the list of other automatically included rules variables on the VARIABLES tab.
2.  Add some help/hint text to the INTERFACE SETTINGS tab in the blocking section to emphasize Inline mode needs rule actions changed to DROP.
3.  Add notice to "Clear Blocks Interval" setting on GLOBAL SETTINGS tab that clearing only works for Legacy Mode.
4.  Make INTERFACES tab dynamic by periodically polling Suricata binary status and updating status icons for each configured interface.
5.  Configure ET-Pro rules download URL path based on full Suricata engine version.  See …
> pfSense-pkg-suricata 4.0.3 Update

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This PR adds the functionality to configure the logged http headers and smtp fields in extended eve output. 
This might be helpful if one wants to reduce the log output for various reasons. For example the logging of the Authorization header could leak login credentials. At the moment all HTTP headers are logged if extended http logging is enabled.
> pfSense-pkg-suricata: Extended eve output selectable headers

- sysutils/pfSense-pkg-RRD_Summary/Makefile
- sysutils/pfSense-pkg-RRD_Summary/files/usr/local/pkg/rrd-summary.xml
- sysutils/pfSense-pkg-RRD_Summary/files/usr/local/share/pfSense-pkg-RRD_Summary/info.xml
- sysutils/pfSense-pkg-RRD_Summary/files/usr/local/www/status_rrd_summary.php
- sysutils/pfSense-pkg-RRD_Summary/pkg-descr
Rewrite of RRD Summary package to allow display of available historical data beyond current and previous month.  Bumped the major version because of the significant changes.
This is my first attempt at a pfSense package, please be gentle :)
> pfSense-pkg-RRD_Summary - Rewrite to include display of historical data

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_generate_conf.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_migrate_config.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_barnyard.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_global.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_passlist.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_preprocessors.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
- security/pfSense-pkg-snort/files/var/db/snort/sidmods/disablesid-sample.conf
- security/pfSense-pkg-snort/files/var/db/snort/sidmods/enablesid-sample.conf
This update to the Snort GUI package incorporates six bug fixes and two new features.  The GUI package now supports the latest 2.9.11.1 version of Snort.  References to the text "Snort VRT rules" within hints, help messages, log entries and titles within the GUI have been changed to read "Snort Subscriber Rules" to align with the naming convention preferred by Talos and Cisco.
1.  Added dynamic updating of service status to INTERFACES tab for Snort and Barnyard2.  When starting Snort on an interface, the task is launched as a background job and the GUI monitors the task status to update the icons on the INTERFACES tab.
2.  Added support for the new "Max-Detect" IPS Policy available with Snort Subscriber Rules.  This new policy is designed mainly for testing purposes as it …
> pfSense-pkg-snort-3.2.9.6 Update

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php
haproxy-devel, dont check 'external address' for a valid ip/port when shared frontend is checked.
> haproxy-devel, dont check 'external address' for a valid ip/port when shared frontend is checked.

- net/pfSense-pkg-cellular/Makefile
- net/pfSense-pkg-cellular/files/usr/local/bin/cellular_dev.py
Hi,
it seems that pythons os.link does not work reliably os.symlink does seem to work.
This patch changes the link to symlink.
Best
Sven
> Cellular Package change link to symlink

- net-mgmt/pfSense-pkg-softflowd/Makefile
- net-mgmt/pfSense-pkg-softflowd/files/usr/local/pkg/softflowd.inc
- net-mgmt/pfSense-pkg-softflowd/files/usr/local/pkg/softflowd.xml
- net-mgmt/pfSense-pkg-softflowd/files/usr/local/share/pfSense-pkg-softflowd/info.xml
- net-mgmt/pfSense-pkg-softflowd/pkg-descr
Updated package version to 1.2.3
Includes new 'VLAN' flow tracking level
Includes new 'IPFIX' protocol option
Flows will now include a unique ID (or index) to differentiate between multiple instances of softflowd
The indexes will be displayed in an info box at the top of the settings page when softflowd is enabled
> pfSense-pkg-softflowd: Added additional options now available in softflowd-0.9.9_1

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php
This update for the Suricata GUI package contains 2 bug fixes and 7 new features.  The underlying binary is unchanged and remains at version 4.0.3.
1. The configuration files associated with automatic SID managment via the SID MGMT tab are deprecated in favor of storing the automatic SID management directives directly in the firewall's configuration file, _config.xml_.  During the installation of the new package, the content of all files found in the **/var/db/suricata/sidmods** directory will be migrated into a list array stored in the firewall configuration file.  The new list names are taken from the filenames read from the directory.  Storing the automatic SID managment directives content as Base64-encoded data within the firewall configuration ensures that the automatic SID …
> pfSense-pkg-suricata v4.0.3_2

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php
This update adds two new features to the GUI package.  The underlying Suricata binary version is 4.0.4.
1.  Add the ability to use custom user-supplied rules update URLs for downloading rules updates.  See Redmine Feature Request #8362.  This is primarily useful for organizations with many firewalls where it is desirable to fetch rule update archives from the rule vendor and then store them on a central internal server for distribution to the organization's internal firewalls.
2.  Add the ability to use a _rejectsid.conf_ configuration on SID MGMT to duplicate what _dropsid.conf_ does except the rule action is changed to REJECT.
> pfSense-pkg-suricata-4.0.4_1

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_htmllist.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_socketinfo.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_utils.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_files.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pool_edit.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pools.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/widgets/widgets/haproxy.widget.php
- fix widget client traffic statistics / layout
- fix host/path acls for http-response actions
- fix processing of fixed ips and subnets that are mentioned in a alias and skip any dns names that might also be there
- skip saving empty options from action/acl/other htmllists
- add support for server-template definition for automatic server discovery
- several small improvements to the webgui
p.s. please update haproxy-devel binaries also to 1.8.7 (not strictly required for these changes, but it includes several stability fixes)
> haproxy-devel, version bump to 0.56 including a variety of new features and fixes

- net/pfSense-pkg-pfBlockerNG/Makefile
Added a makefile CONFLICT tag to avoid users from installing both DEVEL and REL versions at the same time.
> pfBlockerNG v2.1.2_3 - Add tag for DEVEL/REL conflicts

- net/pfSense-pkg-Avahi/Makefile
- net/pfSense-pkg-Avahi/files/usr/local/pkg/avahi.inc
The "Publish DNS Servers" option was not being used when generating the avahi config which caused the DNS servers to always be published regardless of the setting. This patch comments out the publish-dns-servers line in the config file when the "Publish DNS Servers" option is disabled.
> Avahi: Hook up "Publish DNS" option to fix #8366

- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.inc
- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.xml
Able to specify BIND DNS port and control port,
which default to 53 and 953 respectively.
Slightly restructured the BIND package settings
screen to have an "Advanced Options" panel where
the new port settings are and also moved "Custom Options"
and "Global Settings" overrides to this panel.
> Add port specification to BIND package

- net/pfSense-pkg-pfBlockerNG-devel/Makefile
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_dnsbl.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_ip.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_log.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
- Ensure that General Tab -> new IP Tab settings are migrated before converting pfBlockerNGSuppress Alias
- Improve installation logging messages
- Improve 'TLD Whitelist' Help Text
- Fix SQLite3 error messages (Call to a member function fetchArray() on boolean)
- Add TOP1M Whitelist final list to Log Viewer
- Fix logging on manual user-defined pfBlockerNG rules as the Tracker ID prefix doesn't start with '1770*'
>  pfSense-pkg-pfBlockerNG-devel v2.2.1 fixes

- dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.inc
Use of the PHP function "array_diff_assoc" results in any zone which is
a subdomain of a given static DHCP mapping domain being populated with
said mapping. In other words, a static DHCP mapping with a domain of
"domain.com" would appear in any zone that is a subdomain of it, such
as "sub1.domain.com" or "sub2.sub1.domain.com".
This fix changes the logic to perform a direct domain comparison so
that only the zone matching the exact domain specified in a given
static DHCP mapping will be populated with such a mapping entry.
Redmine issue: https://redmine.pfsense.org/issues/8619
> Properly check domain when registering DHCP static mappings

- net-mgmt/pfSense-pkg-Telegraf/Makefile
- net-mgmt/pfSense-pkg-Telegraf/files/usr/local/pkg/telegraf.inc
- net-mgmt/pfSense-pkg-Telegraf/files/usr/local/pkg/telegraf.xml
As telegraf supports graphite as backend pfsense should support configuration too.
> Support graphite backend for telegraf in config-gui

- net-mgmt/pfSense-pkg-nrpe/Makefile
- net-mgmt/pfSense-pkg-nrpe/files/usr/local/pkg/nrpe.inc
It feels like the check_swap command should be one of the default nrpe commands. I ran into some issues with my swap filling up and I had no notification until my pfsense started to fail and nothing could be done except a hard reboot.
Redmine issue: https://redmine.pfsense.org/issues/8756
> Add check_swap

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_migrate_config.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_sid_mgmt.php
This update to the Snort GUI package ports in three new features added previously to the Suricata package.
1. Create hyperlinks for all rule category files on the CATEGORIES tab so that both enabled and not enabled files can be viewed.  Enabled rule category contents are shown by switching to the RULES tab.  Disabled rule category contents are shown in a modal pop-up window.
2. Provide mechanism to view the list of "user-forced disabled" or "user-forced enabled" or "Active Rules" rules on the RULES tab.
3. Migrate storage of SID management files to the firewall _config.xml_ file using Base64 encoding so they stay with the firewall configuration and can be easily backed up as well.
> pfSense-pkg-snort-3.2.9.7_1 - Port new GUI features added previously to Suricata package

- net/pfSense-pkg-pfBlockerNG-devel/Makefile
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_alerts.php
The following settings 'v4suppression', 'suppression' and 'tldexclusion' are not arrays.
> pfSense-pkg-pfBlockerNG-devel -  Fix previous PHPv7 commits.

- security/pfSense-pkg-acme/Makefile
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme.inc
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_command.sh
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_htmllist.inc
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_sh.inc
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_utils.inc
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates.php
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates_edit.php
acme, add challenge alias feature for dns validation with CNAME (https://redmine.pfsense.org/issues/8613)
-support different validation methods within the domains for 1 certificate
-add notification and syslog message when renewal fails
-minor gui improvements
> acme, add challenge alias feature for dns validation with CNAME (for 2.4.3 )

- security/pfSense-pkg-acme/Makefile
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme.inc
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_command.sh
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_htmllist.inc
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_sh.inc
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates.php
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates_edit.php
acme, add challenge alias feature for dns validation with CNAME (https://redmine.pfsense.org/issues/8613)
-support different validation methods within the domains for 1 certificate
-add notification and syslog message when renewal fails
-minor gui improvements
> acme, add challenge alias feature for dns validation with CNAME

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_utils.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_files.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pool_edit.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pools.php
haproxy-devel, php7 array usage.. drop init() and !isarray(x)x=array() , instead use getarraybyref() where required.
> haproxy-devel, php7 array usage.. drop init() and !isarray(x)x=array() , instead use getarraybyref() where required.

- sysutils/pfSense-pkg-nut/Makefile
- sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut.inc
Rename local user from "monuser" to "local-monitor" to avoid conflict with remote access systems that require the old default username/password.
> Update package to avoid conflict with remote access systems that require the old default username/password such as Synology.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
This update of the Snort GUI package provides support for version 2.9.12 of the Snort binary and also corrects a bug on the CATEGORIES tab that prevented the saving of Shared Object rules selections.
1.  Support for the latest 2.9.12 version of the Snort binary
**Bug Fixes**
1.  Share Object rule selections on the CATEGORIES tab cannot be saved.
> pfSense-pkg-snort-3.2.9.8 -- Snort GUI package update

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
Fix version string length and use latest FreeBSD version for SO rules.
None
**Bug Fixes**
1.  Shared Object rules are not correctly extracted from rules archive when updating Snort rules.
2.  Older FreeBSD-10-0 version is being used for extracted Shared Object rules.
> pfSense-pkg-snort-3.2.9.8_3 -- Fix version string length and use latest FreeBSD for SO rules

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
This update corrects a cosmetic display issue on the UPDATES tab whereby the MD5 checksum for the downloaded Snort Subsriber Rules is shown as "Not Downloaded".  This is due to changes in the file version string that came with Snort 2.9.12.
None
**Bug Fixes**
1.  Snort Subscriber Rules MD5 checksum always displays as "Not Downloaded" when in fact the correct file is present on the system.
> pfSense-pkg-snort-3.2.9.8_4 -- Fix display of MD5 checksum for downloaded rules

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_etiqrisk_update.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_ip_reputation.php
This GUI package update corrects two bugs.  No new features are added and the underlying Suricata binary remains at version 4.0.5.
None
**Bug Fixes**
1. The _suricata.log_ files for configured interfaces continues to grow in size with each startup.  This file contains Suricata startup logging only (no alerts info).  To prevent continual growth in size of this log, it is now truncated to zero length immediately prior to starting the Suricata binary for each configured interface so that it shows startup data for the most recent session only.  Reference Redmine bug 8607.
2. Reference to an un-initialized array in the Suricata configuration migration code that is executed during a package update causes a run-time error in PHP 7.2.  Three additional sections of other legacy …
> pfSense-pkg-suricata-4.0.13_10 -- Bug fix update

- net-mgmt/pfSense-pkg-Telegraf/files/usr/local/pkg/telegraf.inc
current code will generate an invalid config if a prefix is used
> pkg telegraf fix prefix string inside config

- sysutils/pfSense-pkg-syslog-ng/Makefile
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng.xml
Open the settings tab from the menu to prevent GUI issues that the log view tab can cause.
> Switch menu linked tab

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_logs_mgmt.php
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_rulesets.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
This updates the GUI package to work with both Rust-enabled and non-Rust-enabled binary builds.  Detection of the target system's architecture is performed by the installation routine and customized PHP files are copied in for non-Rust support.  These custom source code files remove several logging options and app-layer protocol analyzers from the package for non-Rust builds.
For Rust-supported platforms, full logging and app-layer protocol support is provided including the new dhcp, ikev2, krb5, nfs, ntp, and tftp protocols.
> pfSense-pkg-suricata v4.1.2_1 -- Update to allow non-Rust enabled platform support (armv6 and aarch64).

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
This update corrects an issue with the new RULES_DIR path not being correctly applied when processing SID MGMT customizations.  There are no new features or feature changes in this release.
None
**Bug Fixes:**
1. SID MGMT changes not being applied to rules due to incorrect legacy RULES_DIR path being used.
> pfSense-pkg-suricata-4.1.2_2 -- Fix SID MGMT changes not being applied due to new RULES path in 4.1.2.

- security/suricata/Makefile
- security/suricata/files/patch-geoip2.diff
- security/suricata/files/patch-pfSense-ARMv6_ARMv7.diff
This update for the Suricata binary merges in GeoIP2 fixes submitted to upstream.  These fixes eliminate a small memory leak and update the source code formatting to match upstream coding standards.  It also includes auto-detection of target platform and disables compiler optimization for armv6 or armv7 platforms.
None
**Bug Fixes:**
1. Add missing call to SCFree() to free allocated memory.
2. Add logic to configure.ac to detect when being compiled for armv6 or armv7 platforms and disable compiler optimizations on those platforms.
> Suricata 4.1.2_1 - fix geioip memory leak, disable optimization on armv6/v7 platforms.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
This update for the Snort GUI package includes the built-in Snort preprocessor and decoder rules when filtering and displaying user-forced rules on the RULES tab.  Previously, user disabled preprocessor or decoder rules would not be shown when filtering the rules to display user-forced disabled (or enabled) rules.
> pfSense-pkg-snort-3.2.9.8_5  -- Include built-in rules when filtering for user-forced rules

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_rulesets.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
This update for the Suricata package introduces one modified new feature, fixes three bugs and brings the stats logging parameter settings in _suricata.yaml_ inline with the newest Suricata release.
1. Provide separate enable checkboxes for controlling the logging of flow and netflow data.  Formerly a single setting (Traffic Flows) was provided that either enabled or disabled both flow and netflow data logging simultaneously.  These two parameters can now be set independently of each other.  Reference Issue #9403 on the pfSense Redmine site.
**Modified Features**
1. Adjust stats logging config parameters in _suricata.yaml_ to bring them in ilne with the format expected by the Suricata 4.1.3 binary.
**Bug Fixes**
1. The sample conf files for SID MGMT provided in the …
> pfSense-pkg-suricata -- Update to version 4.1.3

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_post_install.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_iprep_list_browser.php
This Snort GUI package update contains three features and two bug fixes.
1. Change the base URL for ET-Open rules to use HTTPS (https://rules.emergingthreats.net/).
2. Change the base URL for OpenAppID free rules to use HTTPS (https://files.pfsense.org/openappid/).
3. Change the IP REP tab code so IP Reputation preprocessor configuration edits restart Snort instead of causing it to stop when already running.  This is necessary because any IP REP changes require a Snort restart on the interface.
**Bug Fixes**
1. IP REPUTATION tab has cosmetic issues when choosing an IP blacklist for the interface.
2. When updating package (via a reinstall) without Snort VRT rule download enabled the _unicode.map_ file is clobbered rendering Snort unable to start.
> pfSense-pkg-snort-3.2.9.8_6

- www/pfSense-pkg-squid/files/usr/local/pkg/squid.inc
Avoid FATAL error No valid signing SSL certificate configured load squid with a CA certificate imported from Windows.
Issue described in this [Netgate Forum thread](https://forum.netgate.com/topic/142453/ssl-intercept-with-windows-certificate-no-valid-signing-ssl-certificate-configured-for-http_port).
> Convert Windows line feeds in squid ca certificate

- net-mgmt/pfSense-pkg-Telegraf/Makefile
- net-mgmt/pfSense-pkg-Telegraf/files/usr/local/pkg/telegraf.inc
- net-mgmt/pfSense-pkg-Telegraf/files/usr/local/pkg/telegraf.xml
I use the ping and netstat modules for my grafana dashboard, and figured others may as well for statistical purposes.
I couldn't really find a better way, seeing as the config page is plain XML, to enter in multiple hosts, but I made the best of what I could with a list of 4 hosts, which adjusts accordingly if some are empty or not.
Feel free to comment if you think there's a better way for adding an arbitrary number of hosts.
> pfSense-pkg-Telegraf - Add support for Ping and Netstat modules

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php
This update to the Suricata GUI package contains one bug fix and no new features.
None
**Bug Fixes**
1.  On the SID MGMT tab, when the blocking mode for an interface does not meet all the criteria, the user can be prevented from deleting a previously assigned DROP SID or REJECT_SID list even if the list is no longer applicable for the selected blocking mode.
> pfSense-pkg-suricata - Update to version 4.1.4

- net/daq/Makefile
- net/daq/files/patch-daq22-netmap.diff
This update adds support in the DAQ netmap module for using the host OS stack as a netmap pipe endpoint in the netmap device specification.  For example, the device string:
em0^:em0
creates a netmap pipe between the host operating system's network stack and the NIC driver for physical interface _em0_.  The caret character ('^') indicates to netmap that the host OS stack endpoint is requested for the physical interface.
Existing DAQ netmap functionality is retained and any legacy device string specifications for netmap will still function.  This code update impacts only the DAQ netmap module.  No other changes were made in any of the other DAQ source code files.
> daq-2.2.2_1 -- Add host stack OS endpoint support for DAQ netmap module

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_conf_template.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_generate_conf.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_migrate_config.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_post_install.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_preprocessors.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_sid_mgmt.php
- security/pfSense-pkg-snort/files/usr/local/www/widgets/widgets/snort_alerts.widget.php
- security/pfSense-pkg-snort/files/var/db/snort/sidmods/dropsid-sample.conf
- security/pfSense-pkg-snort/files/var/db/snort/sidmods/rejectsid-sample.conf
- security/pfSense-pkg-snort/pkg-plist
This update to the Snort GUI package introduces a new _Inline IPS_ mode of operation using the DAQ netmap module.  With Inline IPS operation, rules with the ALERT action will generate alerts but will **not** block the associated traffic.  Rules with the DROP action will generate alerts and block the associated traffic by dropping the packet and not transmitting it on to the operating system stack.  Rules with the REJECT action will generate an alert, drop the packet by not forwarding it to the OS stack, and will send a RST back to the sender for TCP traffic or a "Destination port unreachable" for UDP/ICMP traffic.
This update also includes a five bug fixes.
1.  Support for Inline IPS mode operation using the DAQ netmap module.  This mode is configured on the INTERFACE …
> pfSense-pkg-snort-4.0 -- Add support for Inline IPS mode and fix miscellaneous bugs

- security/pfSense-pkg-stunnel/files/usr/local/pkg/stunnel.inc
- security/pfSense-pkg-stunnel/files/usr/local/pkg/stunnel.xml
First time using github. Sorry if my approach is ruff.
Custom options is needed for stunnel as it is very well rounded tool. Personally I use stunnel to add TLS to SMTP (old copiers) so will use protocol option often but reviewing the stunnel documentation I foresee myself and other users may need additional features.
> Stunnel custom options

- security/pfSense-pkg-openvpn-client-export/files/usr/local/pkg/openvpn-client-export.inc
I stumbled upon two issues with the wonderful Automagic feature:
1) It currently does not create a remote line at all even if you have NAT rules that point to the TCP server.
2) It behaves unexpectedly when dealing with multiple ports inside an alias: it will only use the first one.
This merge request fixes both issues.
> Fix Automagic for TCP based OpenVPN and for port aliases

- security/pfSense-pkg-tinc/Makefile
- security/pfSense-pkg-tinc/files/usr/local/pkg/tinc.inc
Not stripping \r characters from tinc-up causes problems with custom
tinc-up scripts, e.g. the interface is added to the group "pkg_tinc\r"
instead of "pkg_tinc".
> Fix line ending problem in security/pfSense-pkg-tinc

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_barnyard.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_global.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_preprocessors.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
This update to the Snort GUI package corrects an issue that produces a fatal exit error when attempting to start Snort on an interface such as a VLAN or PPPoE connection due to the real interface name, when combined with the Snort package UUID value, exceeding the built-in Snort limit on a PID file suffix.
**Change Log:**
1.  Edit references to the OpenAppID text rules on the GLOBAL SETTINGS to use a more appropriate description.
2.  On the INTERFACES tab, indicate the type of blocking mode (_Inline IPS_ or _Legacy Mode_) currently configured for the interface.
3.  Deprecate the use of the interface UUID parameter for determining the current status of Snort or Barnyard2 on an interface (stopped or running).
None
**Bug Fixes:**
1.  Remove use of UUID parameter as part of …
> pfSense-pkg-snort-4.0_1 -- Fix VLAN and PPPoE interface startup error (PID suffix too long)

- security/suricata/Makefile
- security/suricata/files/patch-alert-pf.diff
This update corrects a bug in the _alert-pf_ custom blocking plugin used on pfSense that causes a start failure and logging of the error message "_[ERRCODE: SC_ERR_INVALID_ARGUMENTS(52)] - prefix or user NULL_" when Suricata is engaged in Legacy Mode blocking on an interface with a /31 subnet mask.
**Bug Fixes:**
1.  Suricata fails to start on interfaces with a /31 subnet mask when Legacy Mode blocking is enabled.  See Redmine Issue #9031.
> Suricata-4.1.4_1 --Fix Redmine Issue #9031, failure to start on interface with /31 netmask.

- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_etiqrisk_update.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
This update to the GUI package incorporates the use of the PHP _syslog()_ function for logging both informational and error messages so that a SEVERITY_LEVEL flag can be associated with each message.  This lets users sending the logs for automated analysis on remote systems parse log messages by Severity (LOG_ERR, LOG_ALERT, LOG_WARN or LOG_NOTICE).  Formerly all Suricata log messages were logged with Severity LOG_ERR, even those that were merely informational in nature.
This update also includes two bug fixes.
**Changes Log:**
1.  Update the example Snort 2.9.x rules snapshot filename on the GLOBAL SETTINGS tab in the Snort Subsriber Rules section to the most recent Snort 2.9.x version.
2.  Add a warning under the Snort rules snapshot filename text box advising the user to not use Snort3 …
> pfSense-pkg-suricata-4.1.4_2 -- Add SEVERITY LEVEL to logs and miscellaneous bug fixes

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
This update corrects a typo in a function call to the _syslog()_ function.  The SEVERITY parameter was indavertently included within the quotation marks of the message string, so _syslog()_ complains about receiving only one parameter when it expects two.
None
**Bug Fixes:**
1.  PHP warning message generated when signalling Suricata to live-reload its configuration via the GUI.
> pfSense-pkg-suricata-4.1.4_3 -- Fix PHP warning caused by typo in syslog() function call

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
This update corrects one bug (Redmine Issue [#9581](https://redmine.pfsense.org/issues/9581)) and enhances an existing feature.
**Changes Log:**
1.  Replace copy and empty string file write calls with more efficient rename/touch calls in the log rotation code within the Log Management cron task code.
None
**Bug Fixes:**
1.  Upgrade of Suricata GUI package removes default Suricata _*-events.rules_ files installed by the base Suricata binary package.  Redmine issue [#9581](https://redmine.pfsense.org/issues/9581).
> pfSense-pkg-suricata-4.1.4_4 -- Bug Fix Update

- security/suricata/Makefile
- security/suricata/files/patch-alert-pf.diff
This update corrects a serious bug introduced into the Legacy Mode blocking custom output plugin used in pfSense.  The bug was inadvertently introduced when fixing Redmine Issue [#9031](https://redmine.pfsense.org/issues/9031).
_This is an emergency bug fix release and needs to be pushed to both the RELEASE and DEVEL branches of pfSense._
**Changes Log:**
1.  Fixed some formatting issues in the source code caused by differences in tab character translation to spaces between different editors used when editing the source code.
2.  Added additional checks for errors allocating a Radix Tree structure and tests within the code to validate a Radix Tree pointer before using it.
None
**Bug Fixes:**
1.  Legacy Mode blocking not actually blocking offender IPs in some setups and …
> Suricata-4.1.4_2 -- Fix potential crash and failure to block in Legacy Mode blocking plugin.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_cron_misc.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_generate_conf.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_migrate_config.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_post_install.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_uninstall.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_global.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_preprocessors.php
This update for the Snort GUI package enhances logging by providing PRIORITY tagging for messages and also corrects six bugs.
1. Log messages are now tagged with a PRIORITY flag to facilitate parsing by third-party log analysis programs.  The PHP _syslog()_ function is now used for system logging and an appropriate PRIORITY tag is included with each logged message.
**Bug Fixes:**
1. Fix issues with updating the dynamic STATUS icons for Snort and Barnyard2 on the INTERFACES tab when starting/stopping Snort and Barnyard2 on an interface.
2. Change log rotation code to use _rename()_ to just move the existing log file to a new name and then _touch()_ to create the new empty one instead of a copy-then-empty string write sequence.  The former is much more efficient.
3. Ensure …
> pfSense-pkg-snort-4.0_2 -- Bug fix and feature update

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_generate_conf.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_uninstall.php
This update corrects the erroneous use of LOG_WARN instead of LOG_WARNING as a PRIORITY flag for _syslog()_ messages.
None
**Bug Fixes:**
1.  The PRIORITY flag for warning messages printed via _syslog()_ uses LOG_WARN instead of the correct LOG_WARNING constant.
> pf-Sense-pkg-snort-4.0_3 -- Bug Fix Update

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interface_logs.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_global.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
This update for the Snort GUI package contains only bug fixes.  No new features are introduced.
None
**Bug Fixes:**
1. Two changed files were inadvertently left out of the previous Snort 4.0_3 update package.  The files were part of the change set where the constant SNORT_PBI_BINDIR was changed to SNORT_BINDIR.
2. Remove any leading or trailing spaces put there by mistake when saving the Oinkmaster and ETpro subscription codes on GLOBAL SETTINGS tab.
3. Wrap user input on GLOBAL SETTINGS tab with HTML-encode/decode functions for added security against code injection.
4. Clean-up unnecessary _write_config()_ call to prevent spamming of ACB service when downloading rules updates.
> pfSense-pkg-snort v4.0_4 -- Include two files left out of previous 4.0_3 update

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
This Suricata GUI package update corrects five bug reports.  No new features are added in this release.
None
**Bug Fixes:**
1. Syntax error typo in _syslog()_ function call on GLOBAL SETTINGS tab causes PHP warning.
2. When using Legacy Mode blocking the array of SIDs modified for REJECT action is not properly initialized as an empty array before an iteration attempt is made later in the code.
3. Code logic bug allows attempted operation with netmap without specifying an interface when 'Block Offenders' is not checked.
4. Remove any inadvertent leading or trailing spaces from Oinkcode and ETPro code when saving on GLOBAL SETTINGS tab.
5. Clean-up unnecessary _write_config()_ call to prevent spamming of ACB service when downloading rules updates.
> pfSense-pkg-suricata 4.1.4_5 -- Bug Fix Update

- security/barnyard2/files/patch-configure.in
- security/barnyard2/files/patch-schemas_create__mysql
- security/barnyard2/files/patch-src_output-plugins_spo__database__cache.h
The Barnyard2 from 2.4.4.p3 is broken in my recent purchased SG-3100. There are two road blocks:
- Outdated syntax in SQL query.
- Use optimization `-O` CFLAGS that cause unaligned memory access in pointer casting. Barnyard2 crashed with bus error.
I have tested my patched Barnyard2 under SG-3100 in 2.4.4.p3 for days. The database is MariaDB 10.3.9. I haven't seen the crash any more.
See discussion details in [pfSense forum](https://forum.netgate.com/topic/143538/barnyard2-and-mariadb/6)
> Patch Barnyard2 for SG-3100 ARMv6/7

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_migrate_config.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_post_install.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_define_servers.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_suppress.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_suppress_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_passlist.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_passlist_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_preprocessors.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_sid_mgmt.php
This update for the Snort GUI package adds two new features and corrects two bugs. Support is added for the latest Snort-2.9.14.1 binary.
1. The FreeBSD real interface name is now shown in parentheses beside the friendly interface name on the INTERFACES tab and in the interface selection drop-downs on the INTERFACE SETTINGS and ALERTS tabs.
2. Support is added for the latest Snort v2.9.14.1 binary from upstream.
**Bug Fixes:**
1. New SSH preprocessor parameters default value values were not being set when adding a new interface on the INTERFACES tab.
2. An error in the Snort GUI code could allow the most recently added interface configuration to be overwritten by the values of the interface immediately before it in the _config.xml_ file.
> pfSense-pkg-snort-4.0_5 -- Snort GUI Package Update

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_migrate_config.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_post_install.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
This update for the Snort package on pfSense-2.4.4 adds support for the latest 2.9.14.1 snort binary.  It also adds one new feature and corrects two issues.
1. The physical real interface is now shown in parentheses along with the friendly interface name when displaying interfaces on the INTERFACES tab and within drop-down selectors on the INTERFACE SETTINGS and ALERTS tabs.
2. Add support for the latest snort-2.9.14.1 binary from upstream.
**Bug Fixes:**
1. Remove an unnecessary _write_config()_ call when performing the scheduled cron task to update rules to prevent spamming the ACB (Auto Config Backup) service.
2. Release the config array reference pointer used to iterate the Snort _config.xml_ entries during saved settings migration steps when finished using the …
> pfSense-pkg-snort-3.2.9.9 -- Add support for snort-2.9.14.1 and other updates

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_migrate_config.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_uninstall.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
This update corrects a cosmetic issue with the display of the last rules update execution time and status information. Formerly this info was stored in the _config.xml_ file, but that resulted in unnecessary backups of _config.xml_ with each rules update job run. A previous package update removed the call to _write_config()_ that was generating the unnecessary backup, but that prevented the recording of rules update time and status. The rules update execution time and status are now recorded locally in a small file on the firewall.
None
**Bug Fixes:**
1. Rules update task info (execution time and status) is displaying as either "unknown" or the last package installation date and time.
> pfSense-pkg-snort 3.2.9.9_1 -- Fix display of last rules update status info

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
This update fixes an issue with displaying the last rules update job status and corrects the spelling of a _syslog()_ PRIORITY constant in the GeoIP2 database update cron task script.
Formerly the rules update status info was stored in the _config.xml_ file, but that resulted in unnecessary backups of _config.xml_ with each rules update job run. A previous package update removed the call to _write_config()_ that was generating the unnecessary backup, but that prevented the recording of rules update time and status. The rules update execution time and status are now recorded locally in a small file on the firewall.
None
**Bug Fixes:**
1. A PHP warning message is generated in the crash log due to use of an unknown constant in a call to the _syslog()_ function in the GeoIP2 …
> pfSense-pkg-suricata-4.0_6 -- Fix rules update status display and syslog PRIORITY constant

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
This corrects a typo (missing parenthesis) on line 133 in the file _suricata_migrate_config.php_.
None
**Bug Fixes:**
1. Line 133 of _suricata_migrate_config.php_ generates a syntax error.
> pfSense-pkg-suricata-4.1.4_7 -- Fix missing parenthesis

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
This update corrects a bug caused by a dangling (un-released) config array iterator variable. During the package installation process, when an existing Suricata configuration is present and being migrated to the new package version, it is possible for the last configured Suricata interface to be overwritten by the first configured interface.
None
**Bug Fixes:**
1. During package installation when a user has two or more configured Suricata interfaces, the most recently added interface can be overwritten by the data from the first configured interface.
> pfSense-pkg-suricata-4.1.4_8 -- Fix dangling config array iterator bug.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
This update fixes an issue with displaying the last rules update job status and corrects the spelling of a _syslog()_ PRIORITY constant in the GeoIP2 database update cron task script.
Formerly the rules update status info was stored in the _config.xml_ file, but that resulted in unnecessary backups of _config.xml_ with each rules update job run. A previous package update removed the call to _write_config()_ that was generating the unnecessary backup, but that prevented the recording of rules update time and status. The rules update execution time and status are now recorded locally in a small file on the firewall.
None
**Bug Fixes:**
1. A PHP warning message is generated in the crash log due to use of an unknown constant in a call to the _syslog()_ function in the GeoIP2 …
> pfSense-pkg-suricata-4.1.4_8 -- Fix display of rules update status info & dangling array reference iterator

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_migrate_config.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_uninstall.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_sid_mgmt.php
This update corrects a cosmetic issue with the display of the last rules update execution time and status information. Formerly this info was stored in the _config.xml_ file, but that resulted in unnecessary backups of _config.xml_ with each rules update job run. A previous package update removed the call to _write_config()_ that was generating the unnecessary backup, but that prevented the recording of rules update time and status. The rules update execution time and status are now recorded locally in a small file on the firewall.
None
**Bug Fixes:**
1. Rules update task info (execution time and status) is displaying as either "unknown" or the last package installation date and time.
2. The **Save** button is hidden on SID MGMT tab whenever the **Enable** checkbox is …
> pfSense-pkg-snort-4.0_6 -- Fix display of last rules update status info

- www/pfSense-pkg-squid/files/usr/local/pkg/squid_upstream.xml
Small typo. I noticed earlier in the web UI
> Corrected Typo

- security/pfSense-pkg-acme/Makefile
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_command.sh
Execute actions only after the additional certificate files have been written.
> Redmine #9752: Write certificate files before executing actions.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_libhtp_policy_engine.php
This update for the Suricata GUI package adds two new configurable parameters to interface configurations and sets the minimum Suricata binary version requirement to 4.1.5 or greater.
1. Added new _meta-field-limit_  parameter for an HTTP App Layer Parser server config. Redmine issue #6785. This parameter is now available on the libhtp engine configuration when editing a HTP Policy Engine on the APP PARSERS tab.
2. The EVE Alert Log metadata setting is now configurable. Turning off this App Layer metadata logging when sending EVE alert data to a syslog server can help prevent truncating of long lines by syslog. This new parameter is located on the INTERFACE SETTINGS tab.
**Bug Fixes:**
None
> pfSense-pkg-suricata-4.1.5 -- Update for 4.1.5 binary and add new features

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_post_install.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_sid_mgmt.php
This update for the Snort GUI package addresses two identified Redmine Issues.
None
**Bug Fixes:**
1. The WebGUI ignores _Split ANY-ANY_ option on INTERFACE SETTINGS tab. Redmine issue #9772.
2. The Snort GUI does not account for the underlying physical interface for a configured Snort instance being removed in pfSense prior to the Snort instance being removed. This can lead to anomalous behavior. Redmine issue #9789.
> pfSense-pkg-snort-4.0_7 -- Bug fix update

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_libhtp_policy_engine.php
This update for the Suricata GUI package adds two new configurable parameters to interface configurations and sets the minimum Suricata binary version requirement to 4.1.5 or greater.
1. Added new meta-field-limit parameter for an HTTP App Layer Parser server config. Redmine issue #6785. This parameter is now available on the libhtp engine configuration when editing a HTP Policy Engine on the APP PARSERS tab.
2. The EVE Alert Log metadata setting is now configurable. Turning off this App Layer metadata logging when sending EVE alert data to a syslog server can help prevent truncating of long lines by syslog. This new parameter is located on the INTERFACE SETTINGS tab.
**Bug Fixes:**
None
> Update Suricata GUI package to v4.1.5 and import fixes from DEVEL branch

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
This update corrects a typo in the _snort_create_rc()_ function in the _snort.inc_ source file that results in an invalid path being passed to the snort binary as part of its startup arguments.
None
**Bug Fixes:**
1. Fix typo within if() conditional in _snort_create_rc()_ function so the string operation is a comparision instead of an assignment.
> pfSense-pkg-snort-4.0_8 -- Fix typo in snort.sh shell script creation code

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php
This update to the Suricata GUI package corrects an issue present in Suricata that was also identified and fixed recently in the Snort GUI package. See [Redmine Issue #9789](https://redmine.pfsense.org/issues/9789) for details.
None
**Bug Fixes:**
1. The Suriata GUI does not account for the underlying physical interface for a configured Suricata instance being removed in pfSense prior to the Suricata instance being removed. This can lead to anomalous behavior. See [Redmine issue #9789](https://redmine.pfsense.org/issues/9789) created for Snort.
> pfSense-pkg-suricata-4.1.5_1 -- Bug Fix (Redmine Issue #9789)

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_generate_conf.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_suppress.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
This update adds support for the latest 2.9.15 version of the snort binary, fixes two bugs and adds one new feature.
1. Added sortable columns on the RULES tab to duplicate similar functionality available on the ALERTS tab.
**Bug Fixes:**
1. When adding a SID to a Suppress List or disabilng a rule on the ALERTS tab, Snort is stopped if running and logs a "_Snort Reload: Any change to the dynamic preprocessor configuration requires a restart._" message to the system log.
2. The SUPPRESS tab allows deletion of an assigned Suppress List when it should instead issue a warning and not delete lists currently assigned to an interface.
> pfSense-pkg-snort-3.2.9.10 -- Support 2.9.15 binary and bug fixes

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_suppress.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
This update provides support for the 2.9.15 snort binary and adds one new feature as requested in Redmine Issue #9871 and fixes one bug.
1. Several columns are now sortable on the RULES tab (duplicating the functionality present on the ALERTS tab).
**Bug Fixes:**
1. The SUPPRESS tab allows deletion of an assigned Suppress List when it should instead issue a warning and not delete assigned lists.
> pfSense-pkg-snort-4.0_9 -- Update to support 2.9.15 binary

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_interfaces_edit.php
Redmine Issue: https://redmine.pfsense.org/issues/9850
Hyyperscan will run on x86 processors in 64-bit (Intel® 64 Architecture) and 32-bit (IA-32 Architecture) modes.
hide Hyperscan Pattern Matcher Algorithm in case of ARM arch
> show huperscan option only for x86 arch

- security/pfSense-pkg-stunnel/Makefile
- security/pfSense-pkg-stunnel/files/usr/local/pkg/stunnel.inc
- security/pfSense-pkg-stunnel/files/usr/local/pkg/stunnel.xml
Redmine Issue: https://redmine.pfsense.org/issues/9919
stunnel client can use cert with any ECDSA curve,
but if stunnel server use incorrect (not prime256v1, secp384r1, secp521r1) curve, an error occurs:
`SSL_connect: /build/ce-crossbuild-master/pfSense/tmp/FreeBSD-src/crypto/openssl/ssl/record/rec_layer_s3.c:1528: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure`
same func as https://github.com/pfsense/FreeBSD-ports/pull/710
maybe we can create system-wide pkg_get_ca_or_certs($type) function?
> stunnel: check ECDSA certs curves

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export.php
Redmine Issue: https://redmine.pfsense.org/issues/9929
show only ECDSA-safe exports packages on OpenVPN \ Client Export Utility page
i.e. certs with prime256v1, secp384r1, secp521r1 curves
> openvpn client export ECDSA safe list check

- security/pfSense-pkg-stunnel/Makefile
- security/pfSense-pkg-stunnel/files/usr/local/pkg/stunnel.inc
Redmine Issue: https://redmine.pfsense.org/issues/9219
After defining a new tunnel with a non-default certificate the resulting .pem file is readable by any user 
It should be chmod'ed to 0600
> stunnel: chmod 0600 pem file

- sysutils/pfSense-Status_Monitoring/Makefile
- sysutils/pfSense-Status_Monitoring/files/usr/local/www/rrd_fetch_json.php
Redmine Issue: https://redmine.pfsense.org/issues/9807
It looks like the data used for the packets logging is being incorrectly multiplied by 8 as though it is assuming a Bytes value that shouldn't be be applied to PPS.
> Status_Monitoring: packets graphs scale fix

- sysutils/pfSense-pkg-syslog-ng/Makefile
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng.inc
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng.xml
Redmine Issue: https://redmine.pfsense.org/issues/9563
Adds TLS to default protocols list,
creates cert, key and ca files,
and changes syslog-ng.conf by adding to _DEFAULT object:
```php
tls(
key-file('/var/etc/syslog-ng/syslog-ng.key')
cert-file('/var/etc/syslog-ng/syslog-ng.cert')
ca-dir('/var/etc/syslog-ng/ca.d')
)
```
see https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/administration-guide/56
It also check cert/ca with cert_build_list()  for correct ECDSA cert with private key
> syslog-ng TLS support

- net-mgmt/pfSense-pkg-arpwatch/Makefile
- net-mgmt/pfSense-pkg-arpwatch/files/usr/local/pkg/arpwatch.inc
- net-mgmt/pfSense-pkg-arpwatch/files/usr/local/pkg/arpwatch.xml
Update net-mgmt/arpwatch to 3.0 from -current, update net-mgmt/pfSense-pkg-arpwatch to use arpwatch >= 3.0 and add support for the new zero pad flags (-Z/-C). Fix the "update vendors" option to actually ethercodes.dat.
> Update arpwatch to 3.0, pfSense-pkg-arpwatch to support the new zero pad flags (-Z/-C).

- net-mgmt/pfSense-pkg-Telegraf/Makefile
- net-mgmt/pfSense-pkg-Telegraf/files/usr/local/pkg/telegraf.inc
Redmine Issue: https://redmine.pfsense.org/issues/9322
"after reboot, the "Additional configuration for Telegraf" appending configurations will be lost, but the content on the GUI still there, will have to click "save" again, thank you ."
> Telegraf additional conf fix 

- security/suricata4/Makefile
- security/suricata4/distinfo
- security/suricata4/files/patch-alert-pf.diff
- security/suricata4/files/patch-pfSense-ARMv6_ARMv7.diff
- security/suricata4/pkg-plist
This updates the Suricata 4.x branch to the latest upstream stable version. Release Notes for this version can be viewed [here](https://suricata-ids.org/2019/12/13/suricata-4-1-6-released/).
**Note:** this version is intended for non-AMD64 hardware that cannot run the Suricata 5.x branch due to Rust language dependencies.
> suricata4 - Update to v4.1.6 for non-AMD64 architectures.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/arm/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_ip_reputation.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
This GUI package update provides support for the latest version of the Suricata binary (v4.1.6). It also corrects five bugs and adds four new features.
1. Added column sorting to the RULES tab so it behaves the same as the ALERTS tab.
2. Make filters on ALERTS tab sticky across other actions such as suppressing alerts or disabling a SID. Currently any applied filter resets. [Redmine Issue #9902](https://redmine.pfsense.org/issues/9902).
3. Highlight rules with "_noalerts;_" option on RULES tab by coloring the text using the Bootstrap class "text-success" and using a different ACTION icon.
4. Added option to set unique logging directory for _file-store_ configuration section in suricata.yaml.
**Bug Fixes:**
1. When creating HOME_NET and EXTERNAL_NET (and other ipvars), …
> pfSense-pkg-suricata-4.1.6_1 - Support Suricata 4.1.6, fix GeoLite2 DB and others.

- www/pfSense-pkg-squid/files/usr/local/pkg/squid.inc
- www/pfSense-pkg-squid/files/usr/local/pkg/squid_reverse.inc
Redmine Issue: https://redmine.pfsense.org/issues/9652
fixes sslcrtd_program program path for squid 3/4
> squid4 ssl_crtd fix

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/pkg/openvpn-client-export.inc
Redmine Issue: https://redmine.pfsense.org/issues/6339
Use full 'subject' line in openvpn exported configs.
See details on redmine and https://community.openvpn.net/openvpn/ticket/386
> ovpn-export: cryptoapicert full subj

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/arm/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
This update to the Suricata GUI package corrects a bug in the code that downloads and extracts the MaxMind GeoIP2 database file. It also restores the code to check the associated MD5 hash file for the posted database so that new database downloads only happen when needed.
None
**Bug Fixes:**
1. When downloading and extracting the MaxMind GeoIP2 database, the code fails to take into account an additional sub-directory embedded into the gzip archive. This results in a corrupted database when copying the gzip archive content to the _/usr/local/share/suricata/GeoLite2_ directory.
> pfSense-pkg-suricata-4.1.6_2 - Fix GeoIP database download issues

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
This update corrects several issues around unpacking the zipped GeoIP database archive.
None
**Bug Fixes:**
1. Correct several issues preventing the successful unpacking of the zipped GeoIP database archive and the copying of the unpacked file to the correct destination.
> pfSense-pkg-suricata-4.1.6_3 -- Fix the GeoIP database update one more time!

- net-mgmt/pfSense-pkg-Telegraf/Makefile
- net-mgmt/pfSense-pkg-Telegraf/files/usr/local/pkg/telegraf.inc
Redmine Issue: https://redmine.pfsense.org/issues/10218
I'm running the 2.4.5-RC with Telegraf package 0.9_1 and found that Telegraf wouldn't start when I have more then one CA in pfSense.
After checking the created telegraf.ca I found that there is a missing newline after the first certificate, so it looked like this:
-----END CERTIFICATE----------BEGIN CERTIFICATE-----
which is invalid.
The fix is quite simple, look at line 67 in telegraf.inc and change it from
$ca_pem .= base64_decode($ca['crt']);
to
$ca_pem .= base64_decode($ca['crt'])."\n";
actual fix by Grimson Gretzleburg
> Telegraf CA file creation fix. Issue #10218

- net-mgmt/pfSense-pkg-softflowd/Makefile
- net-mgmt/pfSense-pkg-softflowd/files/usr/local/pkg/softflowd.inc
- net-mgmt/pfSense-pkg-softflowd/files/usr/local/pkg/softflowd.xml
Redmine Issue: https://redmine.pfsense.org/issues/10220
Add sampling configuration to softflowd package:
```
-s sampling_rate        Specify periodical sampling rate (denominator)
```
Add PSAMP export:
```
-v 1|5|9|10|psamp       NetFlow export packet version
10 means IPFIX and psamp means PSAMP (packet sampling)
```
see https://tools.ietf.org/html/rfc5476
original PR https://github.com/pfsense/FreeBSD-ports/pull/700 can be closed
Co-authored-by: <chrono@open-resource.org>
Co-authored-by: <viktor@netgate.com>
> Add softflow 1.0.0 features - sampling and PSAMP export. Issue #10220

- net-mgmt/pfSense-pkg-nrpe/Makefile
- net-mgmt/pfSense-pkg-nrpe/files/usr/local/libexec/nagios/check_carp_freebsd.sh
Redmine Issue: https://redmine.pfsense.org/issues/7895
Adds check_carp_freebsd.sh script to the /usr/local/libexec/nagios/
Script output result:
`OK - CARP Status : vmx0 (vhid 5) is MASTER (OK) vmx0 (vhid 6) is MASTER (OK) vmx0 (vhid 7) is MASTER (OK); vmx1 (vhid 10) is MASTER (OK);`
tested on the latest 2.4.5 and 2.5
original script by Stéphane Lapie
> Add a script for CARP monitoring to NRPE. Issue #7895

- sysutils/pfSense-pkg-LCDproc/Makefile
- sysutils/pfSense-pkg-LCDproc/files/usr/local/pkg/lcdproc.inc
- sysutils/pfSense-pkg-LCDproc/files/usr/local/www/packages/lcdproc/lcdproc.php
Redmine Issue: https://redmine.pfsense.org/issues/10243
Rawserial driver has been avalbile since 0.5.7 this will dump raw serial data to the serial port. Hackers/makers can then parse the output with an arduino to display on an LCD. This Pull request adds raw serial as an option in the gui.
original PR: https://github.com/pfsense/FreeBSD-ports/pull/684
> rawserial driver for lcdproc. Issue #10243

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
Redmine Issue: https://redmine.pfsense.org/issues/8830
same as https://github.com/pfsense/FreeBSD-ports/pull/760 but for pfSense 2.4.5
Snort (version 4.0_10), visit Global Settings, enable some rulesets, visit Update and run an update. Once that's done visit Interfaces, add an interface, go to the Categories tab and see that the Automatic flowbit resolution setting is unchecked. Below that, notice the message that reads:
> If checked, Snort will auto-enable rules required for checked flowbits. Default is Checked.
This PR simply sets the default value for this checkbox to on when adding a new interface.
> Set Snort autoflowbit checkbox (2.4.5). Issue #8830

- net/pfSense-pkg-siproxd/Makefile
- net/pfSense-pkg-siproxd/files/usr/local/pkg/siproxd.inc
- net/pfSense-pkg-siproxd/files/usr/local/pkg/siproxd.xml
Redmine Issue: https://redmine.pfsense.org/issues/9249
from siproxd.conf.example:
> Plugin_siptrunk
> 
>  Plugin to handle SIP Trunks where using *one* single SIP account a
>  whole number block is routed. This means asn incoming INVITE does carry
>  the target number (in SIP URI or To: header field) but does not really
>  carry any clear indications to which account it belongs to.
>  Thus, we need some help - a mapping of the number blocks used in a SIP
>  trunk and the corresponding SIP account (as used during REGISTER)
> 
>  ..._name:          any name, pure documentation
>  ..._account:       SIP account in the form of 'sip:user@host',
>                     identical as used for registration.
>  ..._numbers_regex: REGEX that matches the whole number block associated
> …
> SIP Trunk plugin for siproxd. Issue #9249

- security/suricata4/Makefile
- security/suricata4/distinfo
- security/suricata4/files/patch-alert-pf.diff
- security/suricata4/files/patch-pfSense-ARMv6_ARMv7.diff
This updates the _suricata4_ port on pfSense to the latest stable upstream version of Suricata, 4.1.7. Release notes for Suricata 4.1.7 can be found [here](https://suricata-ids.org/2020/02/13/suricata-4-1-7-released/). One change is added to the pfSense custom blocking output plugin in this release. The blocking plugin now checks the signature flags in each passed alert for the "noalert" option and skips blocking for any signature with a "noalert" keyword.
> suricatat4 - Update binary to version 4.1.7 and don't block on noalert signatures.

- net-mgmt/pfSense-pkg-lldpd/Makefile
- net-mgmt/pfSense-pkg-lldpd/files/usr/local/pkg/lldpd/lldpd.inc
- net-mgmt/pfSense-pkg-lldpd/files/usr/local/www/lldpd_settings.php
Redmine Issue: https://redmine.pfsense.org/issues/8574
The lldpd-package provided by the package manager seems to be compiled with AgentX-support, but there is nowhere to activate it using the GUI. 
An AgentX sub-agent can connect to Net-SNMP and would in this case make LLDP-information available over SNMP.
In the Net-SNMP configuration, AgentX is already enabled:
```
grep agentx /var/etc/netsnmpd.conf
master agentx
```
original patch by Nicklas Björk (from the redmine page)
> LLDPd AgentX support. Issue #8574

- benchmarks/pfSense-pkg-iperf/Makefile
- benchmarks/pfSense-pkg-iperf/files/usr/local/pkg/iperf.xml
Redmine Issue: https://redmine.pfsense.org/issues/10357
iperf verbose output (-V) shows more detailed information, including TCP MSS, CPU utilization, time 
and version:
```
iperf 3.7
FreeBSD test.int 12.0-RELEASE-p10 FreeBSD 12.0-RELEASE-p10 ce9563d5729(RELENG_2_5) pfSense amd64
Control connection MSS 1293
Time: Thu, 19 Mar 2020 05:13:39 UTC
Connecting to host 10.1.0.5, port 5201
Cookie: 4bbcxdrco3hburalbff5vwfcoc2iaa763ygb
TCP MSS: 1293 (default)
[  5] local 10.11.0.4 port 23135 connected to 10.1.0.5 port 5201
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 10 second test, tos 0
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   722 KBytes  5.88 Mbits/sec   21   2.51 KBytes       
[  5]   1.00-2.00 …
```
> Add Iperf verbose output option. Issue #10357

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_iprep_list_browser.php
This updates the Snort GUI package on pfSense-2.4.4 RELEASE to support the latest 2.9.15.1 Snort binary. One new feature is added to the GUI and one reported bug is corrected.
1. Filter Panel parameters, when filtering is enabled on the ALERTS tab, are now persistent across page submits so that previously defined filtering parameters do not reset when submitting a revised filter. A new "Exact Match" option was also added to the Filter Panel. When checked, this causes matches only when each provided filter parameter matches exactly. When unchecked, filter values will match on partial strings.
**Bug Fixes:**
1. On IP REP tab, the file browser icons are broken due to an incorrect image source file path.
> pfSense-pkg-snort-3.2.9.10_2 - Add persistent filters on ALERTS tab and bug fix.

- security/snort/Makefile
- security/snort/distinfo
- security/snort/files/patch-alert.csv.diff
- security/snort/files/patch-pfSense-ARM317.diff
- security/snort/files/patch-spoink-integration.diff
This updates the Snort binary for the pfSense-2.4.4 RELEASE branch to the latest upstream version, 2.9.15.1. Release notes for this version can be found here:  [https://blog.snort.org/2020/01/snort-29151-has-been-released.html](https://blog.snort.org/2020/01/snort-29151-has-been-released.html).
> Snort - update Snort binary to 2.9.15.1 version to keep pace with upstream

- security/snort/Makefile
- security/snort/distinfo
- security/snort/files/patch-alert.csv.diff
- security/snort/files/patch-pfSense-ARM317.diff
- security/snort/files/patch-spoink-integration.diff
This updates the Snort binary to the latest 2.9x release, version 2.9.15.1. Release notes for this version are posted here:  [https://blog.snort.org/2020/01/snort-29151-has-been-released.html](https://blog.snort.org/2020/01/snort-29151-has-been-released.html).
> Snort -- update Snort binary to version 2.9.15.1 to keep pace with upstream.

- net-mgmt/pfSense-pkg-zabbix-agent/Makefile
- net-mgmt/pfSense-pkg-zabbix-agent/files/usr/local/pkg/zabbix-agent.inc
- net-mgmt/pfSense-pkg-zabbix-agent/files/usr/local/pkg/zabbix-agent.xml
Redmine Issue: https://redmine.pfsense.org/issues/9272
This PR allow to enter multiple comma-separated Listen IPs,
And also allow to use :: and ::/1 IPv6 addresses
> Allow multiple IP in ListenIP for Zabbix Agent. Issue #9272

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
This updates the Snort GUI package for pfSense-2.5-DEVEL to support the latest 2.9.15.1 Snort binary. One new feature and one bug fix is included in this release.
1. Filter Panel parameters, when filtering is enabled on the ALERTS tab, are now persistent across page submits so that previously defined filtering parameters do not reset when submitting a revised filter. A new "Exact Match" option was also added to the Filter Panel. When checked, this causes matches only when each provided filter parameter matches exactly. When unchecked, filter values will match on partial strings.
**Bug Fixes:**
1. When SID MGMT changes rules to DROP, it is not skipping rules containing "_flowbits:noalert_" tags. This results in dropped traffic without any logged alert about the drop …
> pfSense-pkg-snort-4.0_12 - support 2.9.15.1 binary; add ALERTS tab persistent filter

- security/pfSense-pkg-suricata4/Makefile
- security/pfSense-pkg-suricata4/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata4/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata4/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata4/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata4/files/usr/local/www/suricata/suricata_global.php
This update randomizes the periodic rules update check to spread the load on the rules update sites due to the large number of pfSense Suricata installations. The former default value had large numbers of machines hitting the rules update sites at precisely 5 minutes past the midnight hour local time.
1. The **Rules Update Start Time** on the GLOBAL SETTINGS tab now has a random minute for the default start time for first-time users.
2. For existing users who have never changed their **Rules Update Start Time** from the old default of 00:05, the minutes value will be randomized and stored.
3. The PHP module that performs the actual rules update check will randomly sleep for between 0 and 35 seconds before actually making connection to the Snort.org site.
**Bug Fixes:** …
> pfSense-pkg-suricata4-4.1.7_2 - Randomize rules update checks to minimize load on update sites.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
This update randomizes the periodic rules update check to spread the load on the rules update sites due to the large number of pfSense Suricata installations. The former default value had large numbers of machines hitting the rules update sites at precisely 5 minutes past the midnight hour local time.
1. The **Rules Update Start Time** on the GLOBAL SETTINGS tab now has a random minute for the default start time for first-time users.
2. For existing users who have never changed their **Rules Update Start Time** from the old default of 00:05, the minutes value will be randomized and stored.
3. The PHP module that performs the actual rules update check will randomly sleep for between 0 and 35 seconds before actually making connection to the Snort.org site.
**Bug Fixes:** …
> pfSense-pkg-suricata-5.0.2_1 - Randomize rules update checks to spread the load on rules update sites.

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/pkg/openvpn-client-export.inc
Redmine Issue: https://redmine.pfsense.org/issues/10369
An exact definition of the OpenVPN remote server protocol must be present,
Otherwise, it may try to establish a connection with the wrong version of IP protocol.
see https://redmine.pfsense.org/issues/10368
> OpenVPN Client export server protocol definition. Issue 10369

- sysutils/pfSense-pkg-syslog-ng/Makefile
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng.inc
The TLS support currently is broken because the CA certificate file name is not correct. For this reason the clients certificate can't be verified.
Currently the CA certificate is being stored as "cacert.pem" but as you can see in the syslog-ng [documentation](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/administration-guide/56) it must be "$distinguished_name_hash.0".
> Copy the CA certificate (for example cacert.pem) of the Certificate Authority that issued the certificate of the syslog-ng clients to the syslog-ng server, for example into the /opt/syslog-ng/etc/syslog-ng/ca.d directory.
> 
> Issue the following command on the certificate: openssl x509 -noout -hash -in cacert.pem The result is a hash (for example 6d2962a8), a series of alphanumeric …
> Fix syslog-ng TLS support. Issue #8631

- security/pfSense-pkg-suricata4/Makefile
- security/pfSense-pkg-suricata4/files/arm/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata4/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata4/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata4/files/usr/local/www/suricata/suricata_global.php
None
**Bug Fixes:**
1. The **Rules Update Start Time** minutes value must be padded to 2 digits when the integer value is less than 10.
> pfSense-pkg-suricata4-4.1.7_3 - 'rules_update_starttime' minutes value needs padding

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
None
**Bug Fixes:**
1. The **Rules Update Start Time** minutes value must be padded to 2 digits when the integer value is less than 10.
> pfSense-pkg-suricata-5.0.2_2 - 'rules_update_starttime' minutes value needs padding

- sysutils/pfSense-pkg-Service_Watchdog/Makefile
- sysutils/pfSense-pkg-Service_Watchdog/files/usr/local/pkg/servicewatchdog.inc
Redmine link: https://redmine.pfsense.org/issues/10356
Refer to feature #10354 Telegram Notification Support in the main pfsense package.
This will allow the service watchdog to take advantage of this feature.
> Feature #10356 - Support for additional notification methods

- net-mgmt/pfSense-pkg-arpwatch/Makefile
- net-mgmt/pfSense-pkg-arpwatch/files/usr/local/pkg/arpwatch.inc
- net-mgmt/pfSense-pkg-arpwatch/files/usr/local/pkg/arpwatch.xml
and only clobber on deinstall if clear_database is enabled.
> net-mgmt/pfSense-pkg-arpwatch: Never clobber database on install

- sysutils/pfSense-pkg-syslog-ng/Makefile
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng.inc
Redmine Issue: https://redmine.pfsense.org/issues/10490
On initial setup, `syslogng_build_cert()` tries to get the parameters from `$config`, but it needs to get it from `$post`, because `$config` has no tls configuration parameters
> Syslog-ng initial TLS config fix. Issue #10490

- security/pfSense-pkg-acme/Makefile
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_htmllist.inc
Redmine Issue: https://redmine.pfsense.org/issues/10452
the new dnsapi-plugin for namemaster.de made it into my pfsense with package version 0.6.6
in Services / Acme / Certificate options: Edit
you can see the password/hashofpassword without open the editing option
NameMaster.de uses `nm_sha256` field name for password hash:
https://github.com/pfsense/FreeBSD-ports/blob/6dbb7316f2e11968ebbdfa6c5da6f5d101cd58f3/security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme.inc#L837
but only fields containing `key`, `secret`, `password` or `token` are replaced with ***:
https://github.com/pfsense/FreeBSD-ports/blob/6dbb7316f2e11968ebbdfa6c5da6f5d101cd58f3/security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme_htmllist.inc#L170
can be merged with …
> ACME hide NameMaster.de hash. Issue #10452

- security/pfSense-pkg-openvpn-client-export/Makefile
- security/pfSense-pkg-openvpn-client-export/files/usr/local/pkg/openvpn-client-export.inc
Redmine Issue: https://redmine.pfsense.org/issues/10369
OpenVPN < 2.4 doesn't support remote IPv4/IPv6 protocol definition (udp4/udp6/tcp4/tcp6),
If checkbox **Legacy Client** is set, it must generate compatible config (udp/tcp).
see https://forum.netgate.com/topic/152577/pfsense-openvpn-client-export-problem
> OpenVPN export legacy remote proto. Issue #10369

- security/pfSense-pkg-acme/Makefile
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme.inc
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_accountkeys.php
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_accountkeys_edit.php
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates.php
- security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates_edit.php
Redmine Issue: https://redmine.pfsense.org/issues/10442
this fix uses `descr` field name instead of `desc`,
it's included in the `$cdata_fields` of xmlparser.inc
> ACME IDN description. Issue #10442

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_cron_misc.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_log_mgmt.php
This update adds support for the latest 2.9.16 version of the Snort binary and corrects a Logs Management bug identifed by Redmine Issue #10494.
None
**Bug Fixes:**
1. The Logs Management cron task is not detecting and removing rotated alert and AppID stats files. See [Redmine Issue #10494](https://redmine.pfsense.org/issues/10494).
> pfSense-pkg-snort-4.1 -- Fix Logs Mgmt not purging rotated logs and support 2.9.16 Snort

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_cron_misc.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_log_mgmt.php
This update adds support for the latest 2.9.16 version of the Snort binary and corrects a Logs Management bug identifed by [Redmine Issue #10494](https://redmine.pfsense.org/issues/10494).
None
**Bug Fixes:**
The Logs Management cron task is not detecting and removing rotated alert and AppID stats files. See [Redmine Issue #10494](https://redmine.pfsense.org/issues/10494).
> pfSense-pkg-snort-3.2.9.11 - Fix Logs Mgmt not purging rotated logs, support 2.9.16 Snort

- security/snort/Makefile
- security/snort/files/patch-alert.csv.diff
- security/snort/files/patch-pfSense-ARM317.diff
- security/snort/files/patch-spoink-integration.diff
This updates the Snort binary on pfSense-2.5-DEVEL to version 2.9.16 to keep pace with the latest upstream release from the Snort team. Release notes for this version can be found [here](https://snort-org-site.s3.amazonaws.com/production/release_files/files/000/013/419/original/release_notes_2.9.16.txt).
> Snort - Update snort binary to latest 2.9.16 version to match upstream.

- net-mgmt/pfSense-pkg-arpwatch/Makefile
- net-mgmt/pfSense-pkg-arpwatch/files/usr/local/pkg/arpwatch.inc
Redmine Issue: https://redmine.pfsense.org/issues/10475
fix for https://github.com/pfsense/FreeBSD-ports/pull/844
to correctly check for 'clear_database' value
otherwise arpwatch mac db is never deleted
> ARPwatch fix db cleanup. Issue #10475

- net/pfSense-pkg-pfBlockerNG-devel/Makefile
- net/pfSense-pkg-pfBlockerNG-devel/pkg-plist
Redmine Issue: https://redmine.pfsense.org/issues/9874
SafeSearch install fix
> pfBlockerNG SafeSearch install fix. Issue #9874

- net-mgmt/pfSense-pkg-Telegraf/Makefile
Redmine Issue: https://redmine.pfsense.org/issues/10522
Enabling netstat from the web interface (as part of Telegraf) ... fails. The error message can be seen from a command line test run,
telegraf --test --input-filter netstat --config /usr/local/etc/telegraf.conf:
```
2020-05-03T03:18:31Z I! Starting Telegraf 1.13.4
2020-05-03T03:18:31Z E! [inputs.netstat] Error in plugin: error getting net connections info: exec: "lsof": executable file not found in $PATH
2020-05-03T03:18:31Z E! [telegraf] Error running agent: One or more input plugins had an error
```
from https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NETSTAT_README.md:
```
Netstat Input Plugin
This plugin collects TCP connections state and UDP socket counts by using **lsof**.
```
> Telegraf add lsof dependency. Issue #10522

- net-mgmt/pfSense-pkg-lldpd/Makefile
- net-mgmt/pfSense-pkg-lldpd/files/usr/local/pkg/lldpd/lldpd.inc
Redmine Issue: https://redmine.pfsense.org/issues/9635
Add a workaround for appliances with integrated switches to allow run LLDPd on it,
as by default LLDPd uses parent physical interface to run, which doesn't work with integrated switches
> LLDPd integrated switch workaround. Issue #9635

- net/pfSense-pkg-haproxy-devel/Makefile
Redmine Issue: https://redmine.pfsense.org/issues/10500
However, PROMEX is not built by default with HAProxy. It is provided as an extra
component for everyone want to use it. So you need to explicitly build HAProxy
with the PROMEX service, using the Makefile variable "EXTRA_OBJS". For instance:
`    make TARGET=linux-glibc EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"`
if HAProxy provides the PROMEX service, the following build option will be
reported by the command "haproxy -vv":
>     Built with the Prometheus exporter as a service
https://github.com/haproxy/haproxy/blob/master/contrib/prometheus-exporter/README
needs testing on 2.5 first
> Build HAProxy Package with buildin Prometheus exporter. Implement #10500

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
`filter_get_vpns_list()` returns only:
- IPsec Mobile IPv4 subnet
- IPsec site-to-site networks
- OpenVPN client/server Tunnel Network / Remote Network IPv4
- PPPoE server networks
but not:
- IPsec Mobile IPv6 subnet
- IPsec Mobile warriors IPs (VPN / IPsec / Pre-Shared Keys / Edit)
- OpenVPN client/server Tunnel Network / Remote Network IPv6
- L2TP VPN network
new `snort_get_vpns_list()` returns all
same as https://github.com/pfsense/FreeBSD-ports/pull/878 but for Snort 3.x (pfSense 2.4.5)
> Snort 3.x VPN pass list improvements. Fixes #8688

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
`filter_get_vpns_list()` returns only:
- IPsec Mobile IPv4 subnet
- IPsec site-to-site networks
- OpenVPN client/server Tunnel Network / Remote Network IPv4
- PPPoE server networks
but not:
- IPsec Mobile IPv6 subnet
- IPsec Mobile warriors IPs (VPN / IPsec / Pre-Shared Keys / Edit)
- OpenVPN client/server Tunnel Network / Remote Network IPv6
- L2TP VPN network
new `suricata_get_vpns_list()` returns all
same as https://github.com/pfsense/FreeBSD-ports/pull/878 but for Suricata
> Suricata VPN pass list improvements. Fixes #10700

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
`filter_get_vpns_list()` returns only:
- IPsec Mobile IPv4 subnet
- IPsec site-to-site networks
- OpenVPN client/server Tunnel Network / Remote Network IPv4
- PPPoE server networks
but not:
- IPsec Mobile IPv6 subnet
- IPsec Mobile warriors IPs (VPN / IPsec / Pre-Shared Keys / Edit)
- OpenVPN client/server Tunnel Network / Remote Network IPv6
- L2TP VPN network
new `snort_get_vpns_list()` returns all
TODO: same for snort 3.x and suricata
> Snort VPN pass list improvements. Fixes #8688

- security/pfSense-pkg-suricata4/Makefile
- security/pfSense-pkg-suricata4/files/usr/local/pkg/suricata/suricata.inc
`filter_get_vpns_list()` returns only:
- IPsec Mobile IPv4 subnet
- IPsec site-to-site networks
- OpenVPN client/server Tunnel Network / Remote Network IPv4
- PPPoE server networks
but not:
- IPsec Mobile IPv6 subnet
- IPsec Mobile warriors IPs (VPN / IPsec / Pre-Shared Keys / Edit)
- OpenVPN client/server Tunnel Network / Remote Network IPv6
- L2TP VPN network
new `suricata_get_vpns_list()` returns all
same as https://github.com/pfsense/FreeBSD-ports/pull/878 but for Suricata 4 (which is used by ARM 32-bit systems)
> Suricata 4 VPN pass list improvements. Fixes #10700

- security/pfSense-pkg-acme/Makefile
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme.inc
Fix for issue:
> changing the private key configuration item from ECDSDA to RSA appears to succeed, but when re-issuing or renewing the key it silently continues to use the old private key type. At best this is very confusing when the configuration now shows one type of private key, but they system is actually receiving and using a previously configured type.
> ACME key type change on renew. Fixes #10656

- net/pfSense-pkg-frr/Makefile
- net/pfSense-pkg-frr/files/usr/local/pkg/frr.inc
`frr_ipsec_reload()` must check that the FRR service is enabled and that the `zebra` process is running before run `cycleinterface`
> FRR frr_ipsec_reload() enable check. Fixes #10737

- net/pfSense-pkg-pimd/Makefile
- net/pfSense-pkg-pimd/files/usr/local/pkg/pimd.inc
> Independed if you have enabled the PIMD-service, PIMD is starting during boot
This PR fixes this issue
> PIMd service stop fix. Issue #10692

- security/suricata/Makefile
- security/suricata/distinfo
- security/suricata/files/patch-alert-pf.diff
- security/suricata/pkg-plist
This updates the Suricata binary on pfSense to the latest 5.0.3 version from upstream. Release Notes can be found here:  [https://suricata-ids.org/2020/04/28/suricata-5-0-3-released/](https://suricata-ids.org/2020/04/28/suricata-5-0-3-released/).
This binary update is compatible with both pfSense-2.4.5 and pfSense-2.5 AMD64 versions. This version is not compatible with ARM 32-bit hardware platforms!
> Suricata 5.0.3 -- Update Suricata binary to version 5.0.3 to keep pace with upstream.

- security/suricata4/Makefile
- security/suricata4/distinfo
- security/suricata4/files/patch-alert-pf.diff
- security/suricata4/files/patch-pfSense-ARMv6_ARMv7.diff
- security/suricata4/pkg-plist
This updates the Suricata4 binary on pfSense to the latest 4.1.8 upstream version. Release Notes for this version can be found here:  [https://suricata-ids.org/2020/04/28/suricata-4-1-8-released/](https://suricata-ids.org/2020/04/28/suricata-4-1-8-released/)
This binary version is for the matching _pfSense-pkg-suricata4_ GUI package and is designed for ARM 32-bit platforms where Rust is not available.
> suricata4 -- Update Suricata4 binary to v4.1.8 to keep pace with upstream 4.x  stable branch.

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php
Allows to select SSL/TLS Compatibility Mode in the same manner as Squid SSL Proxy Compatibility Mode option.
Intermediate: https://ssl-config.mozilla.org/#server=haproxy&version=2.1&config=intermediate&openssl=1.1.1d&guideline=5.4
Modern: https://ssl-config.mozilla.org/#server=haproxy&version=2.1&config=modern&openssl=1.1.1d&guideline=5.4
> HAProxy SSL/TLS Compatibility Mode option. Implements #10779

- net-mgmt/pfSense-pkg-arpwatch/Makefile
- net-mgmt/pfSense-pkg-arpwatch/files/usr/local/pkg/arpwatch.inc
- net-mgmt/pfSense-pkg-arpwatch/files/usr/local/pkg/arpwatch.xml
- Allow to disable email notifications by removing recipient email  https://redmine.pfsense.org/issues/10770 
- Do not send cron email notifications https://redmine.pfsense.org/issues/10771
- Do not show PHP error if `ethercodes.dat` file is not found:
`[22-Jul-2020 10:11:21 Europe/Moscow] PHP Warning:  file_get_contents(/usr/local/arpwatch/ethercodes.dat): failed to open stream: No such file or directory in /usr/local/pkg/arpwatch.inc on line 170`
> ARPwatch improvements. Issue #10770

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
`ssl-default-bind-ciphersuites` and `ssl-default-server-ciphersuites` is only available when support for OpenSSL was built in and OpenSSL 1.1.1 or later was used to build HAProxy, see https://www.haproxy.com/documentation/hapee/latest/onepage/#ssl-default-bind-ciphersuites
from https://github.com/pfsense/FreeBSD-ports/pull/911#issuecomment-680719368
> HAProxy: check OpenSSL version for SSL/TLS Compat Mode. Issue #10779

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_blocked.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
###pfSense-pkg-snort-4.1.2
This update to the Snort GUI package provides support for the Snort 2.9.16.1 binary. It also includes a couple of feature enhancements.
1. You can now customize the ACTION for a triggered rule showing on the ALERTS tab by clicking the icon under the **Action** column.
2. When making configuration changes on the INTERFACE SETTINGS tab for an interface, the program logic can now sense certain critical changes and automatically restart Snort on the interface to activate the new settings.
**Bug Fixes:**
None
> Support Snort 2.9.16.1 and improve ALERTS tab and INTERFACE SETTINGS logic.

- net/daq/Makefile
- net/daq/files/patch-daq22-netmap.diff
This updates the Data Acquisition library (DAQ) used by Snort so that it allows netmap connections to host rings in addition to the physical NIC rings. The updated library supports either NETMAP_API version 13 or 14 depending on the which FreeBSD version it is compiled on (NETMAP_API 13 on FreeBSD-11.x and NETMAP_API 14 on FreeBSD-12.x).
When using NETMAP_API version 14, this updated library supports multiple host rings when the physical NIC side of the netmap connection also exposes multiple hardware rings.
> Add host rings support for netmap mode using NETMAP_API versions 13 and 14.

- net/daq/Makefile
- net/daq/files/patch-daq22-netmap.diff
This update to the Snort Data Acquisition library (DAQ) adds support for multiple host rings when using netmap on FreeBSD-12.x systems with the latest NETMAP_API version 14 interface. It also maintains backwards compatibility with the NETMAP_API version 13 interface used on FreeBSD-11.x systems.
> Support host stack interfaces with netmap and NETMAP_API versions 13 and 14.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_cron_misc.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_post_install.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_preprocessors.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
This update to the Snort GUI package corrects the bug reported in [Redmine Issue #10917](https://redmine.pfsense.org/issues/10917). The Snort binary would fail to start in instances where the physical real interface name plus any associated VLAN ID exceeded 10 characters in length. This could occur with certain physical interfaces (e.g., _mvneta1_) when VLAN IDs longer than 2 characters were added. Other interface naming scenarios could also trigger the problem.
There is an 11-character limit (including the terminating NULL) on PID filename suffixes supported by the Snort binary.
1. When unpacking the Snort Subscriber Rules, the code now queries the firewall host OS for the correct version (FreeBSD-11 or FreeBSD-12) and unpacks the appropriate Shared Object (SO) rules …
> pfSense-pkg-snort-4.1.2_1 -- Address Redmine Issue #10917, Snort start failure due to PID file suffix limit.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_cron_misc.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_post_install.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_preprocessors.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
This update to the Snort GUI package corrects the bug reported in [Redmine Issue #10917](https://redmine.pfsense.org/issues/10917). The Snort binary would fail to start in instances where the physical real interface name plus any associated VLAN ID exceeded 10 characters in length. This could occur with certain physical interfaces (e.g., _mvneta1_) when VLAN IDs longer than 2 characters were added. Other interface naming scenarios could also trigger the problem.
There is an 11-character limit (including the terminating NULL) on PID filename suffixes supported by the Snort binary.
1. When unpacking the Snort Subscriber Rules, the code now queries the firewall host OS for the correct version (FreeBSD-11 or FreeBSD-12) and unpacks the appropriate Shared Object (SO) rules …
> pfSense-pkg-snort-4.1.2_1_RELENG_2_4_5 - Fix Redmine Issue #10917 and support FreeBSD-11 and FreeBSD-12

- net-mgmt/pfSense-pkg-bandwidthd/Makefile
- net-mgmt/pfSense-pkg-bandwidthd/files/usr/local/www/diag_bandwidthd.php
from https://api.jquery.com/load-event/:
> Note: This API has been removed in jQuery 3.0; please use .on( "load", handler ) instead of .load( handler ) and .trigger( "load" ) instead of .load().
> BandwidthD frame resize fix. Issue #10911

- net-mgmt/pfSense-pkg-net-snmp/Makefile
- net-mgmt/pfSense-pkg-net-snmp/files/usr/local/pkg/net-snmp.inc
With net-snmp v5.7 (current 2.4.5) snmpd will accept an IPv6 listen address without square brackets, with v5.9 (2.5.0 dev) it requires them to be wrapped in square brackets and will silently fail to start without them. Running in debug to stdout will show a failed to bind error for the v6 address.
Both versions will accept the address in square brackets so do it regardless.
Redmine: https://redmine.pfsense.org/issues/10990
> Wrap net-snmp IPv6 listen address in square brackets

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This package update provides support for the latest 6.0.0 Suricata binary and fixes four bugs. No new features are added.
None
**Bug Fixes:**
1. Check that LRO, TSO and all Hardware Checksumming is disabled in pfSense _config.xml_ when user enables and saves "IPS Inline" mode configuration.
2. Potential YAML key indentation issue with libhtp policy settings in _suricata.yaml_ conf file.
3. Add input validation to prevent users from choosing Netmap Inline IPS Mode with incompatible physical NICs. See [Redmine Issue #10950](https://redmine.pfsense.org/issues/10950) from Snort for details. Suricata needs the same input validation.
4. Complete implementation of fix for [Redmine Issue 9789](https://redmine.pfsense.org/issues/9789) (from Snort) since Suricata is susceptible to …
> pfSense-pkg-suricata-6.0.0 -- Fix Redmine Issues 10950 and 9789, update to support version 6.0.0 binary.

- security/suricata/Makefile
- security/suricata/distinfo
- security/suricata/files/patch-alert-pf.diff
- security/suricata/pkg-plist
This updates the Suricata binary on pfSense AMD64 platforms to the latest 6.0.0 version from upstream. Release Notes for this version can be found here:  [https://suricata-ids.org/2020/10/08/suricata-6-0-0-released/](https://suricata-ids.org/2020/10/08/suricata-6-0-0-released/).
> suricata - Update Suricata binary to the latest 6.0.0 version from upstream.

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_utils.inc
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pool_edit.php
- net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_stats.php
- fix dns-statistics page showing the proper stats
fixes: https://redmine.pfsense.org/issues/10885
- hide deprecated agent-check from available health check options, unless chosen..
fixes: https://redmine.pfsense.org/issues/10936
- allow prefixing server names with supported options like ipv6@ and unix@
and bump version to 0.61.1
> haproxy-devel fixes dnsstats lbagent hostnameprefix

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
This update reverts the Suricata binary to the latest 5.0.4 version from the upstream 5.x branch. It also includes one new feature.
1. Added a rule **Action** column with appropriate icons to the ALERTS tab to show the action set for the triggered rule. Note that for Reject actions, the DROP icon will be shown unless the user forced the rule action to reject by clicking a "change action" icon on the ALERTS or RULES tab. Due to logging limitations in the Suricata binary, a rule whose action is changed to Reject via SID MGMT functions will not show the Reject icon under this column.
**Bug Fixes:**
None
> pfSense-pkg-suricata-6.0.0_1 - Revert runtime binary to 5.0.4, add Action column to ALERTS tab.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This package update provides support for the latest 5.0.4 Suricata binary from the upstream 5.x branch and fixes four bugs. One new feature is also added.
1. Added a rule Action column with appropriate icons to the ALERTS tab to show the action set for the triggered rule. Note that for Reject actions, the DROP icon will be shown unless the user forced the rule action to reject by clicking a "change action" icon on the ALERTS or RULES tab. Due to logging limitations in the Suricata binary, a rule whose action is changed to Reject via SID MGMT functions will not show the Reject icon under this column.
**Bug Fixes:**
1. Check that LRO, TSO and all Hardware Checksumming is disabled in pfSense config.xml when user enables and saves "IPS Inline" mode configuration.
2. …
> pfSense-pkg-suricata-5.0.4-RELENG_2_4_5 - GUI update for 5.0.4 binary support and bug fixes.

- security/suricata/Makefile
- security/suricata/distinfo
- security/suricata/files/patch-alert-pf.diff
- security/suricata/files/patch-src_suricata-common.h
- security/suricata/pkg-plist
This updates the Suricata binary to the latest 5.0.4 version from the upstream 5.x branch. [Release Note](https://suricata-ids.org/2020/10/08/suricata-4-1-9-and-5-0-4-released/)s can be found here: [https://suricata-ids.org/2020/10/08/suricata-4-1-9-and-5-0-4-released/](https://suricata-ids.org/2020/10/08/suricata-4-1-9-and-5-0-4-released/).
> Suricata - Update RELENG_2_4_5 branch to latest 5.0.4 version from upstream 5.x branch.

- security/suricata4/Makefile
- security/suricata4/distinfo
- security/suricata4/files/patch-alert-pf.diff
- security/suricata4/files/patch-pfSense-ARMv6_ARMv7.diff
- security/suricata4/files/patch-src_suricata-common.h
This updates the Suricata4 binary to the latest 4.1.9 version from upstream. [Release Notes](https://suricata-ids.org/2020/10/08/suricata-4-1-9-and-5-0-4-released/) for this version can be found here:  [https://suricata-ids.org/2020/10/08/suricata-4-1-9-and-5-0-4-released/](https://suricata-ids.org/2020/10/08/suricata-4-1-9-and-5-0-4-released/).
> Suricata4 - Update Suricata4 to latest 4.1.9 version from upstream.

- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_define_vars.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules_flowbits.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_suppress_edit.php
This change adds missing description text to calls to the _write_config()_ function to address [Redmine Issue #204](https://redmine.pfsense.org/issues/204). The package version is not incremented.
> pfSense-pkg-suricata-6.0.0_1 -- Add reason text to write_config() calls to address Redmine Issue 204.

- net/pfSense-pkg-pfBlockerNG-devel/Makefile
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
check that `$pfb['dnsbl_vip']` is not empty before `strpos()`
> pfBlockerNG check dnsvl_vip. Fixes #11108

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata4/Makefile
- security/pfSense-pkg-suricata4/files/usr/local/www/suricata/suricata_interfaces.php
> Suricata interface delete icon fix. Issue #11136

- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
If `CURLOPT_TCP_FASTOPEN` is set, curl ignores `CURLOPT_PROXY` settings
> pfBlockerNG proxy fix. Issue #11128

- net/pfSense-pkg-pfBlockerNG-devel/Makefile
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_dnsbl.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
- net/pfSense-pkg-pfBlockerNG-devel/files/var/unbound/pfb_unbound.py
- net/pfSense-pkg-pfBlockerNG-devel/files/var/unbound/pfb_unbound_include.inc
- Fix incorrect function name call
- Add safety belt for DNS Python mode and the DNS Resolver OpenVPN Client Registration option.
- Add a Phishing Army alternative feed.
- Remove any empty < config >< /config > config.xml entries
- DNSBL - NAT / Floating rule modifications when Localhost interface is selected
- Preliminary DNSBL Group Policy configuration
> pfBlockerNG v3.0.0_6

- net/pfSense-pkg-pfBlockerNG-devel/Makefile
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_log.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_update.php
* Fix regression with DNS Resolver cache restore option and DNSBL Blocked Log cache options using the same variable name (Unbound mode issue)
* Remove erroneous comma in Ports Alias (Unbound mode issue)
* Improve Log Browser tab
1) Limit logs to 10,000 lines to avoid browser memory issues
2) Fix issues with Safari browser and log file selection
* Add wide textArea display to Update tab and Log Tab viewer
> pfBlockerNG v3.0.0_7

- net/pfSense-pkg-haproxy-devel/Makefile
- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
use correct `openssl ocsp -header` format,
see https://www.openssl.org/docs/man1.1.1/man1/openssl-ocsp.html:
```
-header name=value
Adds the header name with the specified value to the OCSP request that is sent to the responder. This may be repeated.
```
https://www.openssl.org/docs/man1.0.2/man1/ocsp.html:
```
-header name value
If sending a request to an OCSP server, then the specified header name and value are added to the HTTP request. Note that the name and value must be specified as two separate parameters, not as a single quoted string, and that the header name does not have the trailing colon. Some OCSP responders require a Host header; use this flag to provide it.
```
> HAProxy OCSP crontab fix. Issue #11135

- net-mgmt/pfSense-pkg-net-snmp/Makefile
- net-mgmt/pfSense-pkg-net-snmp/files/usr/local/pkg/net-snmp.inc
The net-snmp service command currently is set to log to a file rather than to syslog so log output ends up in file `/usr/local/www/d` rather than syslog.
Also, increase logging level to info as net-snmpd is very un-chatty.
Redmine: https://redmine.pfsense.org/issues/11204
> Fix net-snmp logging to syslog

- net/daq/Makefile
- net/daq/files/patch-daq22-netmap.diff
This update backports a bug fix for the NS_MOREFRAG flag from the upstream netmap code for the _bridge_ example app. The new netmap implementation in DAQ mimics code from the _bridge_ example app from the netmap base, and that code had an error where the Receive Slot NS_MOREFRAG flag was being set instead of the Transmit Slot NS_MOREFRAG flag.
The netmap implementation in this version of DAQ is used by Snort on pfSense.
> daq-2.2.2_3 - Backport NS_MOREFRAG bug fix from netmap upstream demo app code.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_suppress_edit.php
This update to the GUI package provides support for the latest 5.0.5 binary from upstream. One bug fix and three new features are included.
1. When enabling required Flowbits rules, add the _flowbits:noalert_ tag to rules that were not enabled initially. This will allow flowbits logic to function by pulling in required but disabled rules, but will suppress alerts for those rules not specifically enabled by the user.
2. Add a checkbox selection for "Not Dropped" in the filtering section on the ALERTS tab. Of interest only when the engine mode is "INLINE IPS".
3. Add a checkbox selections for "Drop" and "Reject" in the filtering section on the RULES tab when BLOCK_OFFENDERS is enabled. The "Reject" checkbox is only available when INLINE_IPS mode is also enabled.
**Bug …
> pfSense-pkg-suricata-6.0.0_6 - Update to support 5.0.5 binary, bug fix and add new features

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_suppress_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
This update to the GUI package provides support for the latest Snort 2.9.17 binary. Four bug fixes and one new feature is included in the update.
1. When enabling required Flowbits rules using the automatic flowbits resolution logic, add the _flowbits:noalert_ tag to rules that were not enabled initially by the user but needed to be enabled to satisfy checked flowbits.
**Bug Fixes:**
1. On the CATEGORIES tab, the IPS Policy Mode control should be hidden unless Inline IPS Mode is selected.
2. On the RULES tab, make sure User-Disabled rules are included when filtering for Disabled Rules.
3. Update the help text on the SUPPRESS LIST EDIT tab.
4. Fix typo in Snort GPLv2 Community Rules MD5 file path. See Forum post here: …
> pfSense-pkg-snort-4.1.3 -- Support latest 2.9.17 binary and add bug fixes and new features

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
This update for the Suricata GUI package corrects a bug introduced in version 6.0.0_6 with the auto-flowbits resolution logic. It also corrects a cosmetic issue with the IPS Policy Mode selector on the CATEGORIES tab and beefs up the logic to ensure user-forced-disabled rules are properly filtered on the RULES tab.
None
**Bug Fixes:**
1. Correct bug introduced in the auto-flowbits resolution logic that rendered rules added by the flowbits resolution logic corrupted and unreadable.
2. The IPS Policy Mode drop-down selector should be hidden when the IPS Mode is not IPS MODE INLINE.
3. Logic in the filter panel on the RULES tab may not correctly filter user-forced-disabled rules.
> pfSense-pkg-suricata-6.0.0_7 - Bug fixes for auto-flowbits logic, IPS Policy Mode and RULES tab filtering.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_cron_misc.inc
This update to the Snort GUI package corrects an issue with notifying Snort when a log file has been rotated by the LOGS MGMT logic. No new features are added with this update.
None
**Bug Fixes:**
1. Send the running Snort instance a "soft restart" command when an interface log file is rotated by the LOGS MGMT logic. The soft restart signals Snort to reload/refresh its internal log file handles.
> pfSense-pkg-snort-4.1.3_1 - Make sure Snort is sent "soft restart" when a log file is rotated.

- net/pfSense-pkg-pfBlockerNG-devel/Makefile
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfb_dnsbl.doh.conf
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_alerts.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_ip.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_safesearch.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
- net/pfSense-pkg-pfBlockerNG-devel/files/var/unbound/pfb_unbound.py
* Add doh.dns.apple.com to DoH Block list (SafeSearch page)
* Add RR_TYPE_SIG, RR_TYPE64, RR_TYPE65 to Unbound Python mode DNSBL validation.
* Remove deprecated SafeSearch pfb_dnsbl.firefoxdoh.conf file
* Fix regression with "+" icon Add IP to Whitelist Alias (Reports Tab)
* Add pfSense Uniq_id string to the Curl User Agent String (Should improve BGPView issues for IP Blocked events ASN Reporting.)
* Under the hood improvements to the Widget
* Upgrade DNSBL Unbound mode parser for Lighttpd changes (pfSense 2.5 only)
* Remove AutoShun Feed
* Unbound Python mode improve Log events for potential file permission errors.
* Fix ASN Cache clearing of old ASN Entries, add a "1 Week" ASN Cache option
> pfBlockerNG-devel v3.0.0_10

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
> Add WireGuard networks to Snort VPN pass list. Implements #11386

- security/snort/Makefile
- security/snort/files/patch-spoink-integration.diff
This update enhances the custom blocking output plugin used with pfSense. The plugin can now ingest _pf_ alias table names from a Pass List file. At runtime, IP addresses pulled from alerts are compared against IP addresses, IP subnets and any IP addresses contained in the _pf_ table names provided in the Pass List file. A match results in the IP not being blocked. Thus a Pass List can now contain dynamic IP addresses (_pf_ table names) that are updated by the _filterdns_ daemon in pfSense.
1. Support for _pf_ table names (produced from certain alias types defined in pfSense) as Pass List entries.
**Bug Fixes:**
None
> snort-2.9.17_1 - Custom blocking plugin update to support pf table aliases in Pass List.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_migrate_config.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_blocked.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_define_servers.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_frag3_engine.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ftp_client_engine.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ftp_server_engine.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_httpinspect_engine.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_import_aliases.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interface_logs.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_global.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_suppress.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_suppress_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_list_mgmt.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ip_reputation.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_log_mgmt.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_passlist.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_passlist_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_preprocessors.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rules.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_select_alias.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_sid_mgmt.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_stream5_engine.php
This update to the Snort GUI package provides support for the assignment of multiple custom IP addresses, IP subnets and/or alias names to a Pass List. This includes aliases with content that is dynamically updated by the _filterdns_ daemon. Two new features and three bug fixes are included.
1. Support for multiple custom IP address, IP subnet and/or alias names in a Pass List.
2. On the PASS LISTS tab, a new column indicates if a Pass List is currently assigned to an active interface.
**Bug Fixes:**
1. Undefined constant warning from PHP due to missing quotes in Select Alias and Import Alias dialogs when the help info block is opened.
2. Incorrect variable name in config migration script resulting in config migration repeating and attempting to remove deprecated …
> pfSense-pkg-snort-4.1.3_2 - add support for multiple custom IP and alias Pass List entries, and misc bug fixes

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
add ena(4) to the list of INLINE mode (netmap) supported cards (pfSense 2.5/21.02)
see https://github.com/pfsense/FreeBSD-src/blob/devel-12/sys/dev/ena/ena.c
> Snort ena(4) netmap support. Implements #11533

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata4/Makefile
- security/pfSense-pkg-suricata4/files/usr/local/www/suricata/suricata_interfaces_edit.php
add ena(4) to the list of INLINE mode (netmap) supported cards (pfSense 2.5/21.02)
see https://github.com/pfsense/FreeBSD-src/blob/devel-12/sys/dev/ena/ena.c
> Suricata ena(4) netmap support. Implements #11560

- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_alerts.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_dnsbl.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_ip.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/www/index.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
- net/pfSense-pkg-pfBlockerNG-devel/files/var/unbound/pfb_unbound.py
- net/pfSense-pkg-pfBlockerNG-devel/files/var/unbound/pfb_unbound_include.inc
**CHANGELOG:**
* Improve logging of Services pfb_filter and pfb_dnsbl to show stop/start events in the pfSense system.log
* Fix issue with pfb_filter service not terminating tail_pfb pids correctly (pfSense 2.5+ / pfSense Plus)
* Improve IP Kill States for selected Interfaces in the IP Tab only.
* Improve IP Placeholder settings for empty IP Alias conditions. Default for IPv4: 127.1.7.7, for IPv6 default to ::127.1.7.7
* Improve ipv6 Feed Parsing to remove comment lines after the IPv6 entry
* Fix calls from rc.update_urltables script
* Fix issue with DNSBL Block page when browsing to the DNSBL VIP Address
* Fix issue with Dashboard widget incorretly showing "pfB_DNSBL_VIPs/pfB_DNSBL_Ping/pfB_DNSBL_Permit"
* Add WireGuard interface option to IP Interface settings Redmine: …
> pfBlockerNG-devel v3.0.0_11

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_frag3_engine.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ftp_client_engine.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_ftp_server_engine.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_httpinspect_engine.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_stream5_engine.php
This update for the Snort GUI package provides support for the 2.9.17.1 Snort binary version and includes a fix for Redmine Issue #11637, and a fix for one of the two issues identified in Redmine Issue #11466. There are no new added features in this release.
None
**Bug Fixes:**
1. Correct problem resulting in a duplicate "default" read-only engine name created when adding a new engine to the _HTTP_Inspect_, _Stream5_, _Frag3_, _FTP Server_ or _FTP Client_ preprocessor engines list and clicking the **Select Alias** button to add an existing alias as the "Bind-To" or "Ports" target. See [Redmine Issue #11637](https://redmine.pfsense.org/issues/11637).
2. Correct the issue with "Unknown" or blank being shown for the interface name on other tabs when adding a new interface …
> pfSense-pkg-snort-4.1.3 5 - Fix issue #11637, part of issue #11466, and add support for 2.9.17.1 binary.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_httpinspect_engine.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_global.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
This update to the Snort GUI package provides support for the latest 2.9.18 binary from upstream, adds a new FEODO Tracker Botnet C2 IP rules package option, and fixes two Redmine-reported bugs.
1. Add support for the FEODO Tracker Botnet C2 IP Rules package.
**Bug Fixes:**
1. Fix issue with losing previously entered alias values when adding a new HTTP_INSPECT server engine on the PREPROCESSORS tab. [Redmine Issue #11637](https://redmine.pfsense.org/issues/11637).
2. Make rules update process smarter about restarting running Snort interfaces at the end of the update cycle. See [Redmine Issue #6235](https://redmine.pfsense.org/issues/6235).
> pfSense-pkg-snort-4.1.4 -- Support new 2.9.18 binary, add FEODO Tracker rules, and bug fixes

- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
Do not flush all ipfw rules after enabling the "Use Client-IP to connect to backend servers." and remove associated rules if option or HAProxy  is disabled
> Allow to use HAProxy "Use Client-IP" option with Captive Portal. Fixes #11937

- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
`no-sslv3/no-tlsv1x` are deprecated, use `ssl-min-ver` instead
> HAProxy SSL/TLS Compatibility Mode improvement. Feature #10779

- net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#option%20httpchk:
> Note : For a while, there was no way to add headers or body in the request
used for HTTP health checks. So a workaround was to hide it at the end
of the version string with a "\r\n" after the version. It is now
deprecated. The directive "http-check send" must be used instead.
> HAProxy httpchk method fix. Issue #11491

- sysutils/pfSense-pkg-syslog-ng/Makefile
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng.inc
A separate driver for each interface will now be configured.
The corresponding bug can be found [here](https://redmine.pfsense.org/issues/12114).
> Bug #12114: Fix generated configuration to make syslog-ng bind on all specified interfaces

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
This update addresses three reported bug in the Snort GUI package.
None
**Bug Fixes:**
1. PHP _foreach()_ warning error if rules update is run before a Snort interface is configured. [Redmine Issue #12137](https://redmine.pfsense.org/issues/12137).
2. Remove the _snort.sh_ shell script from _/usr/local/etc/rc.d/_ when no enabled Snort interfaces are present. [Redmine Issue #12001](https://redmine.pfsense.org/issues/12001).
3. Fix Feodotracker rules and some others not working when using SID MGMT features.
> pfSense-pkg-snort-4.1.4_1 -- Bug fix update for Redmine #12001 and #12137.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This update corrects reported bugs in the GUI package. The binary remains at versoin 5.0.6 for now.
1. Add control for parameter 'autofp_scheduler' to the INTERFACE SETTINGS tab. This parameter is only applicabe when runmode 'autofp' is selected.
**Bug Fixes:**
1. Fix a GUI controls state inconsistency issue on the INTERFACE SETTTINGS tab.
2. Change default value for JA3 Fingerprints on the APP PARSERS tab from "off" to "auto".
3. Fix new Feodotracker and SSL Blacklist rules not working with SID MGMT.
4. Remove the _suricata.sh_ shell script from _/usr/local/etc/rc.d/_ when no enabled Suricata interfaces remain. This addresses [Redmine Issue #12001](https://redmine.pfsense.org/issues/12001).
5. Initialize config interface array in rules update code. Fixes [Redmine Issue …
> pfSense-pkg suricata-6.0.0_12

- sysutils/pfSense-pkg-syslog-ng/Makefile
- sysutils/pfSense-pkg-syslog-ng/files/usr/local/pkg/syslog-ng.inc
The corresponding issue can be found [here](https://redmine.pfsense.org/issues/12160).
> Regression #12160: An invalid configuration is generated when choosing TLS as the default protocol

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
rules for testing:
https://github.com/OISF/suricata-intel-index/blob/master/index.yaml
https://raw-data.gitlab.io/post/feeds/
also I found that `suricata_check_rule_md5()` doesn't work correctly without `trim()`,
```php
$md5_check_new = file_get_contents($file_dst);
$md5_check_old = file_get_contents("{$suricatadir}{$filename_md5}");
```
must be:
```php
$md5_check_new = trim(file_get_contents($file_dst));
$md5_check_old = trim(file_get_contents("{$suricatadir}{$filename_md5}"));
```
> Suricata extra rulesets. Implements #11210

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_suppress_edit.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_passlist_edit.php
This update for the Snort GUI package addresses [Redmine Issue #12263](https://redmine.pfsense.org/issues/12263) where a Pass List cannot be saved when the firewall's language setting is anything other than English.
None
**Bug Fixes:**
1. [Redmine Issue #12263](https://redmine.pfsense.org/issues/12263). Pass List cannot be saved when the firewall language is set for anything other than English.
2. Fix unicode encoding for the Description field. Use of the _mb_convert_encoding()_ function is not necessary because the XML config logic wraps the field with CDATA tags.
> pfSense-pkg-snort -- Fix Redmine #12263, Pass List save fails when language is not English

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_suppress_edit.php
This package update provides support for the latest 6.0.3 Suricata binary from upstream. It also adds two new features and corrects six reported bugs.
1. Support is added for FTP, HTTP2 and RFB event logging via the EVE JSON log system.
2. Support is added for HTTP2 and RFB application protocol parsing on the APP PARSERS tab.
**Bug Fixes:**
1. Default GeoIP2 database download to 'off' during a greenfield install.
2. When saving Suppress and Pass Lists, there is no need to call _mb_convert_encoding()_ for the description field ['desc'], because the _config.xml_ code automatically wraps that field with CDATA tags.
3. On INTERFACE SETTINGS tab, when enabling File Store in a greenfield install, the default filestore logging directory name is incomplete (missing the UUID …
> pfSense-pkg-suricata-6.0.3 -- Update for 6.0.3 binary plus new features and bug fixes

- security/suricata/Makefile
- security/suricata/distinfo
- security/suricata/files/patch-alert-pf.diff
- security/suricata/files/patch-configure.ac
- security/suricata/files/patch-flow-mutex-lock.diff
- security/suricata/files/patch-netmap.diff
- security/suricata/files/patch-src_suricata-common.h
- security/suricata/pkg-plist
This updates the Suricata binary to the latest upstream version (6.0.3). It also includes two pfSense-specific patches. These two patches will eventually be merged into Suricata upstream, and at that time can be removed from the pfSense port. 
**pfSense Bugfix Patches:**
1. The 6.x branch of Suricata contains a logic error in the flow manager threading code that can result in a kernel lock of Suricata packet processing threads. The _patch-flow-mutex-lock.diff_ patch corrects this issue. The kernel lock would cause Suricata to stop processing traffic. On netmap-enabled interfaces, this lock resulted in no traffic flowing in either direction.
**pfSense Feature Patches:**
1. Suricata support of netmap is greatly enhanced by the _patch-netmap.diff_ patch. This patch enables multiple netmap …
> suricata-6.0.3 -- Update Suricata binary to the latest 6.0.3 version from upstream.

- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_etiqrisk_update.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
Send rules update and new rules categories notification via email/telegram/pushover
sample message:
```
Suricata rules update started: 2021-08-21 13:00:09
- Emerging Threats Open rules rules were updated.
- Snort VRT rules will not be updated, md5 download failed!
- Snort GPLv2 Community Rules rules were updated.
- Feodo Tracker Botnet C2 IP rules were updated.
- ABUSE.ch SSL Blacklist rules were updated.
- Extra malsilo rules were updated.
- Extra positive rules were updated.
- Extra hunting rules were updated.
----- New rule categories are available -----
- Emerging Threats Open rules: 3coresec.rules, botcc.portgrouped.rules, botcc.rules, ciarmy.rules
Suricata rules update finished: 2021-08-21 13:01:26
```
can be merged with https://github.com/pfsense/FreeBSD-ports/pull/1097
> Suricata rules/categories notifications. Implements #10809

- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
Adds IDN domains support for:
- DNSBL Whitelist
- TLD Exclusion List
- TLD Blacklist/Whitelist
- DNSBL Custom_List
- Python no AAAA List
- IPv4 Custom_List (domain/AS mode)
> pfBlockerNG IDN lists support. Implements #11295

- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
can be merged with https://github.com/pfsense/FreeBSD-ports/pull/1103
> Suricata: skip incorrect HOME_NET entries. Fixes #12322

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This update to the Suricata GUI package fixes a reported issue with netmap use in IPS mode on VLAN interfaces, adds an option for increasing the verbosity of startup/shutdown logging, and increases the greenfield default for the TCP stream memcap value from 64 MB to 128 MB.
1. Add option to the INTERFACE SETTINGS tab for enabing more verbose logging in the _suricata.log_ file from Suricata when starting up and shutting down an interface instance.
**Bug Fixes:**
1. When using Inline IPS Mode with VLANs, because the netmap device cannot process VLAN tags, Suricata should pass the VLAN's parent interface as the physical interface where netmap will operate.
2. The default value for TCP Stream Memcap (on the FLOW/STREAM tab) for greenfield installs is increased from 64 MB to …
> pfSense-pkg-suricata-6.0.3_3 -- Fix netmap VLAN issue, add verbose logging option, increase stream memcap.

- security/suricata/Makefile
- security/suricata/files/patch-alert-pf.diff
This update adds support for FQDN (fully-qualified domain name) aliases as entries in a Pass List for the Legacy Blocking Mode custom plugin. The code for the custom blocking plugin was also cleaned up, and some selective read/write locks were implemented where necessary to control access to shared data structures from multiple threads.
1. Add support for FQDN host aliases in a Pass List supplied to the Legacy Blocking Mode custom plugin.
**Bug Fixes:**
None
> suricata-6.0.3_4 - Support FQDN alias in Pass List for Legacy Mode Blocking custom plugin.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php
**pfSense-pkg-suricata-6.0.3_4**
This update to the Suricata GUI package adds support for entering multiple host and network aliases (including FQDN aliases) to a Pass List. This mimics the same feature added to the Snort GUI package back in February of 2021.
1. Added the ability to specify multiple IP addresses, network subnets, or host and network aliases (including fully-qualified-domain-name aliases) to a Pass List.
**Bug Fixes:**
None
> pfSense-pkg-suricata-6.0.3_4 - Support multiple host and network aliases in a Pass List.

- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_filecheck.php
1) Reload all instances that use the same suppression list
2) Add "Please wait at least 15 secs for the process to complete before toggling additional rule actions." to suppress list change save messages
3) Add VirusBay link to `suricata_filecheck.php`
Can be merged with https://github.com/pfsense/FreeBSD-ports/pull/1122
> Suricata instance reload on suppress list change fix. Issue #12506

- net-mgmt/pfSense-pkg-Telegraf/Makefile
- net-mgmt/pfSense-pkg-Telegraf/files/usr/local/pkg/telegraf.inc
https://redmine.pfsense.org/issues/12462
The Netgate XG-1537 has the following disk paths at 100% utilization:
/dev
/var/dhcpd/dev
/var/unbound/dev
All three of the above disks use`devfs` as the filesystem.
The current issue with the telegraf package is that when you save from the Services -> Telegraf page, it overwrites whatever you put into `/usr/local/etc/telegraf.conf` with the following:
```txt
[[inputs.disk]]
ignore_fs = ["tmpfs", "devtmpfs"]
```
The package needs to be updated to also include `devfs` in that list like so:
```txt
[[inputs.disk]]
ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
```
> Telegraf: add "devfs" to ignore_fs

- net-mgmt/pfSense-pkg-softflowd/files/usr/local/pkg/softflowd.inc
- net-mgmt/pfSense-pkg-softflowd/files/usr/local/pkg/softflowd.xml
- net-mgmt/softflowd/Makefile
This patch allows to configure bi-directional flows when IPFIX version is selected. 
Associated Redmine ticket: https://redmine.pfsense.org/issues/12507
> Add support for bi-directional flow in softflowd

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_rulesets.php
This updates the Snort GUI package to provide support for the latest upstream release of Snort version 2.9.19. Two bug fixes are also included in this update.
none
**Bug Fixes:**
1. Correct typo in name of OpenAppID ruleset name on the CATEGORIES tab.
2. Incorporate the fix for [Redmine Issue #12476](https://redmine.pfsense.org/issues/12476) from Suricata into Snort as the Snort GUI had the same code bug.
> pfSense-pkg-snort-4.1.5 -- update the Snort GUI package to support the 2.9.19 binary

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
This updates the Suricata GUI package to support the latest 6.0.4 binary from upstream.
1. DHCP, HTTP2, and MQTT default rules are added to the built-in rules package.
**Bug Fixes:**
1. Correct typo in checkbox variable name for HTTP2 EVE logging parameter.
> pfSense-pkg-suricata-6.0.4 - Update for 6.0.4 Suricata binary and add new http2 and mqtt built-in rules.

- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
1) Added OpenVPN CSO
2) `openvpn_gen_tunnel_network()` used if available, to correctly expand OpenVPN aliases (https://redmine.pfsense.org/issues/2668)
> suricata_get_vpns_list() OpenVPN improvements. Fixes #12642

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
> Add igc(4) to the list of Suricata INLINE mode (iflib/netmap) supported cards. Feature #12718

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
This update to the Snort GUI package corrects the rules update bug identified in [Redmine Issue #12979](https://redmine.pfsense.org/issues/12979).
None
**Bug Fixes:**
1. Fix [Redmine Issue #12979](https://redmine.pfsense.org/issues/12979). FreeBSD precompiled SO rules subdirectory name changed to FreeBSD-13 in latest Snort rules archives.
> pfSense-pkg-snort-4.1.5_2 -- Fix Redmine Issue #12979 (FreeBSD subdirectory name changed)

- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
Attempts to access the feed file via the old URL return a 301 (Moved Permanently), however the redirect goes to the base of the new domain (HTML text) rather than to the feed file. The result is that the download succeeds, but the downloaded
file does not contain the list of IP addresses.
> The NiX Spam feed has moved from www.dnsbl.manitu.net to www.nixspam.net

- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category_edit.php
This PR adds the ability to specify `CURLOPT_INTERFACE` when downloading lists. (Feature [#12282](https://redmine.pfsense.org/issues/12882))
> pfBlockerNG: Add the option to specify CURLOPT_INTERFACE for IPv4/IPv6 lists (Feature #12882)

- security/pfSense-pkg-acme/Makefile
- security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme.inc
The current link lands on a legacy api page, which gives the impression that perhaps the integration for easyDNS isn't up to date even though it is and works great.
[Redmine #13050](https://redmine.pfsense.org/issues/13050)
> ACME: Update easyDNS API Key Sign Up URL

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
This GUI package update fixes one bug and implements one feature request for the Snort package.
1. Improve robustness of Snort Rules Update Logfile size limit code by changing the logic to match that used in the Suricata package. [Redmine Issue #13096](https://redmine.pfsense.org/issues/13096).
**Bug Fixes:**
1. Fix [Redmine Issue #13095](https://redmine.pfsense.org/issues/13095) where a path name change in the Snort VRT rules archive results in Shared Object (SO) rules not being extracted and updated. The fix makes the new code more flexible in dealing with future internal path name changes in the rules archive tarball.
> pfSense-pkg-snort-4.1.5_3 - Fix Redmine Issues #13095 and #13096

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
This GUI package update fixes one bug and implements one feature request for the Snort package.
1. Improve robustness of Snort Rules Update Logfile size limit code by changing the logic to match that used in the Suricata package. [Redmine Issue #13096](https://redmine.pfsense.org/issues/13096).
**Bug Fixes:**
1. Fix [Redmine Issue #13095](https://redmine.pfsense.org/issues/13095) where a path name change in the Snort VRT rules archive results in Shared Object (SO) rules not being extracted and updated. The fix makes the new code more flexible in dealing with future internal path name changes in the rules archive tarball.
> pfSense-pkg-snort-4.1.5_3_RELENG_2_6_0

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_defs.inc
This updates the Snort GUI package to support the latest 2.9.20 version of the binary from upstream. There are no new features or bug fixes in this GUI update.
None
**Bug Fixes:**
None
> pfSense-pkg-snort-4.1.6 - Update Snort GUI package to support latest 2.9.20 binary.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
This updates the Suricata GUI package to support the latest 6.0.6 binary from upstream. Four new features and two bug fixes are included in this release.
1. Add MQTT and ENIP app-layer-protocol configuration controls on the APP PARSERS tab.
2. Improve the configuration options available in the GUI for the Suricata default events rules on the CATEGORIES tab.
3. Add the new _ssh-events.rules_ file to the list of default Suricata events rules.
4. Add column sorting and improve the functionality of the BLOCKS tab (used for Legacy Blocking Mode). [Redmine Feature Request #12748](https://redmine.pfsense.org/issues/12748).
**Bug Fixes:**
1. Fix [Redmine Issue #12956](https://redmine.pfsense.org/issues/12956) - revert the use of preg_quote() to wrap the user-supplied PCRE …
> pfSense-pkg-suricata-6.0.6 -- Update the Suricata GUI package to support 6.0.6 and add bug fixes and features.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
This update corrects a bug reported in [Redmine Issue #13612](https://redmine.pfsense.org/issues/13612) where a missing _gettext()_ translation of list names equal to 'default' causes the creation of an empty list in non-English multilingual installs.
None
**Bug Fixes:**
1. Correct the issue identified in [Redmine Issue #13612](https://redmine.pfsense.org/issues/13612) - Snort building of lists in multilingual non-English systems is broken when the list name is 'default'.
> pfSense-pkg-snort-4.1.6_2 - Fix Redmine Issue #13612 - Multilingual issue with lists named 'default'.

- security/snort/Makefile
This update for the Snort binary package addresses an issue caused by changes in FreeBSD-ports upstream to the version  of the _luajit_ library. The fix is to explicitly specify the current version of _luajit-openresty_ as the required _luajit_ library to be used with the OpenAppID option in Snort.
None
**Bug Fixes:**
1. [Redmine Issue #13623](https://redmine.pfsense.org/issues/13623) - Snort binary fails to install in the latest pfSense 2.7.0-DEVEL snapshots due to _luajit-openresty_ and _luajit-devel_ conflicts.
> Snort-2.9.20_2 - Fix Redmine Issue #13623 - luajit-openresty conflict with luajit-devel.

- security/suricata/Makefile
This update corrects a conflict between the luajit-devel and luajit-openresty libraries in pfSense. This modifies the Suricata binary to explicitly use luajit-openresty. This is the same issue previously corrected in the Snort binary package as reported in [Redmine Issue #13623](https://redmine.pfsense.org/issues/13623) (already closed against Snort).
None
**Bug Fixes:**
1. Resolve conflict between the luajit-devel and luajit-openresty shared libraries when installing the Suricata binary package.
> suricata-6.0.8_2 - Address Redmine #13623 in Suricata -- luajit-openresty conflict.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
This update corrects one syntax error bug on the ALERTS tab and matches up the GUI package version number with that of the underlying Suricata binary (which was recently updated to 6.0.8 via resync with FreeBSD ports upstream).
None
**Bug Fixes:**
1. [Redmine Issue #13709](https://redmine.pfsense.org/issues/13709), syntax error when loading ALERTS tab page due to a missing parenthesis.
> pfSense-pkg-suricata-6.0.8 - Fix Redmine Issue 13709 and match up GUI and binary version numbers

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This update addresses [Redmine Issue #13714](https://redmine.pfsense.org/issues/13714), "PHP 8.1 error when adding a new interface".
None
**Bug Fixes:**
1. PHP 8.1 fatal error when adding a new interface. [Redmine Issue #13714](https://redmine.pfsense.org/issues/13714).
> pfSense-pkg-suricata-6.0.8_1 - Fix Redmine Issue #13714 - fatal error when adding new interface.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
This update corrects the issue identified in [Redmine Issue #13730](https://redmine.pfsense.org/issues/13730). A change in output behavior of the _filter_var()_ function in PHP 8.1 caused the generation of an incorrect URL for downloading Emerging Threats rules archives.
None
**Bug Fixes:**
1. Suricata fails to download Emerging Threats rule archive due to a behavior change in a native PHP function in PHP 8.1. [Redmine Issue #13730](https://redmine.pfsense.org/issues/13730).
> pfSense-pkg-suricata-6.0.89_2 - Fix Redmine Issue #13730 - failure to download Emerging Threats rules

- net/pfSense-pkg-pfBlockerNG-devel/Makefile
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfb_unbound.py
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category_edit.php
Changelog:
* Fix issue causing Resolver issues in certain cases
* Fix issue with Header Field Auto-Sort
* Fix issue with 'Whois' Format
* Fix issue saving URLs in the IPv4/v6/DNSBL Tab. 
Each save would repeat the htmlspecialchars() encoding resulting in duplicate ";amp" tags being added. 
Please review any IP Aliaes/ DNSBL Groups that have been saved since the last update and manually remove any of these erroneous tags. 
I assume that these will still download ok, so its more cosmetic, and these Feeds will show in the Feeds Tab - Unknown User defined feeds at the bottom of the page.
> pfBlockerNG-devel v3.1.0 9

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php
This update addresses Redmine Issues [13771](https://redmine.pfsense.org/issues/13771) and [13794](https://redmine.pfsense.org/issues/13794).
None
**Bug Fixes:**
1. Fix [Redmine Issue #13771](https://redmine.pfsense.org/issues/13771) - Suricata tries to load invalid SID file.
2. Fix [Redmine Issue #13794](https://redmine.pfsense.org/issues/13794) - when adding a new interface the latest app-layer protocol decoders are not default enabled on the new interface.
> pfSense-pkg-suricata-6.0.8_3 - Fix Redmine Issues #13771 and #13794.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
This update corrects Redmine Issues [#13806](https://redmine.pfsense.org/issues/13806), [#13808](https://redmine.pfsense.org/issues/13808), and [#13812](https://redmine.pfsense.org/issues/13812) reported for the Suricata package.
None
**Bug Fixes:**
1. Fix [Redmine Issue #13806](https://redmine.pfsense.org/issues/13806), Suricata interface rules cannot be viewed.
2. Fix [Redmine Issue #13808](https://redmine.pfsense.org/issues/13808), Suricata saves duplicate entries for the default built-in rules when saving changes on the CATEGORIES tab.
3. Fix [Redmine Issue #13812](https://redmine.pfsense.org/issues/13812), attempting to change suricata blocking mode on LAN interface from legacy to inline throws a PHP error .
> pfSense-pkg-suricata-6.0.8_4 - Fix Suricata Redmine Issues #13806, #13808, and 13812

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
This update improves the code flow during package uninstallation based on items discussed in [Redmine Issue #13827](https://redmine.pfsense.org/issues/13827). One new feature is also added allowing use of IPS Policy Mode to automatically set rule actions when using either Inline IPS Mode or Block On DROPs Only Mode.
1. Added the ability to utilize the built-in IPS Policy "action" metadata to automatically set IPS Policy rule actions to the value specified in the policy metadata (alert or drop) when using Legacy Blocking Mode with the "Block on DROPs Only" option enabled. Formerly IPS Policy "action" metadata was only available for use when using Inline IPS Mode, but that option can also be effective in Legacy Mode Blocking when "Block on DROPs Only" is enabled.
**Bug …
> pfSense-pkg-suricata-6.0.8_5 - Improve uninstall code based on Redmine 13827 and add one new feature

- net/pfSense-pkg-pfBlockerNG-devel/Makefile
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_alerts.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category_edit.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_dnsbl.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.php
- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
- Add "application/json" to list of allowed file download mime-types
- Remove validation for paths in URL validations.
- Add dash as an allowed character in Whois/TLD customlist settings
- Add workaround for .ZIP compressed files. Will now validate ZIP files contents after extraction as opposed to beforehand.
- Fix regression with ASN/Whois File downloads
- Fix regression for the extraction of MaxMind MMDB database file
- Increase DNSBL max domain count for 32GB Ram installs.
- Fix Advanced Inbound/Outbound Port definition regression not saving properly
- Fix DNSBL and IP Counter clearing for the Widget
- Fix Alerts Tab - Dark mode colour options missing in some cases
- Fix Alerts Tab - Page Refresh on/off not saving correctly
> pfBlockerNG-devel v3.1.0_10

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_generate_conf.php
This update to the Snort GUI package corrects the problem identified in [Redmine Issue #13910](https://redmine.pfsense.org/issues/13910).
none
**Bug Fixes:**
1. Fix [Redmine Issue #13910](https://redmine.pfsense.org/issues/13910) - invalid snort.conf parameter for Perf Stats Log Size Limit is created when Performance Stats logging is enabled.
> pfSense-pkg-snort-4.1.6_PHP-8.1 - Fix Redmine Issue #13910, invalid Perf Stats Log Size limit created

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
This update corrects a function name typo identified in [Redmine Issue #13919](https://redmine.pfsense.org/issues/13919).
none
**Bug Fixes:**
1. Fix [Redmine Issue #13919](https://redmine.pfsense.org/issues/13919), typo in function name within the dashboard widget removal code.
> pfSense-pkg-suricata-6.0.8_7-PHP-8.1 - Fix Redmine Issue #13919, typo in function removing dashboard widget

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_etiqrisk_update.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
This update to the Suricata GUI package addresses [Redmine Issue #13839](https://redmine.pfsense.org/issues/13839) (Suricata version updates take a long time). While here, a few other code clean-ups were added.
none
**Bug Fixes:**
1. Fix [Redmine Issue #13839](https://redmine.pfsense.org/issues/13839), Suricata version updates take a long time. This bug only surfaced when certain rules download URLs were used. The cause was traced to a failure to properly negotiate an HTTP/2 session when one was offered by the remote site during the download of new rules packages.
2. While here, make sure all our locally created files are removed when uninstalling Suricata.
3. Add return as the last command in files that are called via include statements (to be a good PHP citizen).
> pfSense-pkg-suricata-6.0.8_8_PHP-8.1 - Fix Redmine Issue #13839 and a few other clean-ups.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_check_for_rule_updates.php
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_generate_conf.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_download_updates.php
This update fixes Redmine Issues [#13922](https://redmine.pfsense.org/issues/13922) and [#13923](https://redmine.pfsense.org/issues/13923). While here some unneeded parentheses were removed from print statements.
none
**Bug Fixes:**
1. Fix [Redmine Issue #13922](https://redmine.pfsense.org/issues/13922), Snort rules package downloads may hang for an extended period if remote site offers an HTTP/2 connection.
2. Fix [Redmine Issue #13923](https://redmine.pfsense.org/issues/13923), Snort fails to clean-up all files when uninstalling and also creates an unnecessary barnyard2 logging subdirectory.
> pfSense-pkg-snort-4.1.6_6-PHP-8.1 - Fix Redmine Issues #13922 and #13923.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
- security/pfSense-pkg-snort/files/usr/local/www/widgets/include/widget-snort.inc
- security/pfSense-pkg-snort/files/usr/local/www/widgets/widgets/snort_alerts.widget.php
This GUI package update corrects two bugs and cleans up direct _$config_ array access in the Snort Dashboard Widget.
None
**Bug Fixes:**
1. Fix [Redmine Issue #13991](https://redmine.pfsense.org/issues/13991) - Suppress icon on ALERTS tab always shows "globally suppressed" for all entries under GID:SID column on ALERTS tab.
2. Fix [Redmine Issue $13994](https://redmine.pfsense.org/issues/13994) - Snort not saving automatically created and assigned Suppress List on an interface when performing actions on the ALERTS tab.
3. Remove previously overlooked direct $config array access in the Snort Dashboard Widget and replace with appropriate config_get_path() or config_set_path() functions.
> pfSense-pkg-snort-4.1.6_7-PHP-8.1 - Fix Redmine Issues #13991 and #13994

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_define_vars.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_files.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
This update to the Suricata GUI package corrects [Redmine Issue #13995](https://redmine.pfsense.org/issues/13995), Suricata fails to save the interface assignment for an automatically generated Suppress List.
None
**Bug Fixes:**
1. Fix [Redmine Issue #13995](https://redmine.pfsense.org/issues/13995) - Suricata not saving automatic assignment of a new pass list for an interface - PHP 8.1 regression.
> pfSense-pkg-suricata-6.0.10_1+PHP-8.1 - Fix Redmine Issue #13995 and update copyright year in missed files

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
This package update corrects the issue identified in [Redmine Issue #14029](https://redmine.pfsense.org/issues/14029). Safe practice is to unset array reference variables when no longer needed to prevent unintended consequences if the same variable happens to be set to a value elsewhere in the code module.
none
**Bug Fixes:**
1. Fix Redmine #14029 - Release dangling array reference variables used in post-install migration.
2. While here, fix two additional instances of dangling array reference variables. 
3. Modify checks for config array values in the package migration of settings code per earlier recommendations of Reid Linnemann. Some areas of this code were actually not working as intended.
4. Simplify and shorten the code section used to remove deprecated Barnyard2 …
> pfSense-pkg-suricata-6.0.10_2 - Fix Redmine Issue 14029, dangling config array references

- security/suricata/Makefile
- security/suricata/files/patch-netmap.diff
This updates the Suricata binary package's netmap IPS mode patch to reflect the most recent changes submitted to upstream.
none
**Bug Fixes:**
1.  Change a startup log message from _SCLogInfo()_ to _SCLogDebug()_ to reduce log spam.
2.  Add Fatal Error exit in the rare event a hardware NIC exposes an unequal number of RX/TX queues. This condition would result in some traffic potentially bypassing Suricata. Suricata netmap operation assumes the RX/RX queue counts are symmetrical, so a NIC with asymmetrical queue counts is incompatible with netmap operation in Suricata.
3. Clean up and format some comment lines and add additional comments to more clearly document the operation of the new v14 netmap API code.
> suricata-6.0.10_1 - Sync netmap IPS mode patch with latest changes submitted to upstream

- security/suricata/Makefile
- security/suricata/files/patch-alert-pf.diff
**suricata-6.0.10_2**
This update for the binary tweaks log messages to better logged processing of URL Table Aliases in a Pass List.
1. Support URL Table alias in Pass List.
**Bug Fixes:**
none
> suricata-6.0.10_2 - Tweak log messages and comments for support of URL Table alias in Pass List in Suricata binary

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php
This update to the Suricata GUI package adds support for URL Table Aliases in a custom Pass List when using Legacy Blocking Mode.
1. Add support for URL Table Aliases in a custom Pass List
**Bug Fixes:**
1. Modify the heredoc coding in the snort_interfaces.php per email comments from Jim Pingle to double-quote the variable strings and validate the $id interface index value prior to use.
> pfSense-pkg-suricata-6.0.10_3_PHP-8.1 - Add support for URL Table alias usage in custom Pass List

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php
This GUI package update for Suricata addresses two bug fixes for [Redmine Issue #14041](https://redmine.pfsense.org/issues/14041) and [Redmine Issue #14042](https://redmine.pfsense.org/issues/14042).
none
**Bug Fixes:**
1. Fix [Redmine Issue #14041](https://redmine.pfsense.org/issues/14041) - post-install migration of existing settings throws a PHP error when the configuration contains the legacy layout of a single alias in a Pass List.
2. Fix [Redmine Issue #14042](https://redmine.pfsense.org/issues/14042) - an assigned Pass List is not shown as "Assigned" on the PASS LISTS tab when the list is used in the HOME_NET or EXTERNAL_NET setting on a Suricata interface.
> pfSense-pkg-suricata-6.0.10_4_PHP-8.1 - Fix Redmine Issues 14041 and 14042.

- security/pfSense-pkg-suricata/Makefile
This request updates the pfSense Suricata GUI package to support the latest 6.0.12 upstream binary release.
None
**Bug Fixes:**
None
> pfSense-pkg-suricata-6.0.12 -- Update Suricata GUI package to support latest 6.0.12 binary

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort_generate_conf.php
- security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
This update for the Snort GUI package corrects two reported bugs. No new features are added.
None
**Bug Fixes:**
1. Fix [Redmine Issue #14469](https://redmine.pfsense.org/issues/14469) - Config pass-through parameter is not properly base64 encoded/decoded after saving a page change. This can result in an invalid value being written to the _snort.conf_ file for the interface.
2. Fix [Redmine Issue #14496](https://redmine.pfsense.org/issues/14496) - When IP and MAC address host pairings are present in the config, but ARP Spoof detection is not currently enabled, an invalid configuration is created in the _snort.conf_ file for the interface resulting in Snort startup failure.
> pfSense-pkg-snort-4.1.6_8 -- Fix Redmine Issues 14469 and 14496.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
**pfSense-pkg-suricata-6.0.13**
This package update provides support for the latest 6.0.13 binary version from upstream and fixes [Redmine Issue #14475](https://redmine.pfsense.org/issues/14475).
None
**Bug Fixes:**
1. Fix [Redmine Issue #14475](https://redmine.pfsense.org/issues/14475) - PHP crash error for some users when updating rules due to calling _gettext()_ with a string argument longer than 4096 characters.
> pfSense-pkg-suricata-6.0.13 -- Fix Redmine Issue 14475 and add support for 6.0.13 binary.

- net-mgmt/pfSense-pkg-net-snmp/Makefile
- net-mgmt/pfSense-pkg-net-snmp/files/usr/local/pkg/net-snmp.inc
This adds an ignoreDIsk directive for /var/unbound/dev for net-smp. Addresses issue [14670](https://redmine.pfsense.org/issues/14670).
> Add ignoreDisk for /var/unbound/dev

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_mgmt.php
This package update provides support for the latest 7.0.0 version of the binary from upstream. Additionally, a few Memory Cap defaults have been increased to match the new OISF suggested default values.
1. Support for new Exception Policies for flows, streams, and app parsers. These new policy settings default to "ignore". With the default settings, Suricata 7.x running with Inline IPS Mode will behave the same as older versions. But the new Exception Policies allow an administrator much greater flexibility in securing the IDS/IPS when off-normal situations are encountered, including a general "fail closed" setup. More details on Exception Polices can be found at: [https://docs.suricata.io/en/suricata-7.0.0/configuration/exception-policies.html](https://docs.suricata.io/e …
> pf-Sense-pkg-suricata-7.0.0 -- Add support for Suricata 7.0.0 binary from upstream

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
This update corrects the bug reported in [Redmine Issue 14723](https://redmine.pfsense.org/issues/14723).
None
**Bug Fixes:**
1. [Redmine Issue 14723](https://redmine.pfsense.org/issues/14723) - GUI code incorrectly calculates a rollover value of 24 hours instead of 00 hours when computing the start time for automatic rules updates for the 12-hour or 6-hour intervals.
> pfSense-pkg-snort - Fix Redmine Issue 14723 - Incorrect rollover from 23 to 00 hours.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
This update corrects the bug reported in [Redmine Issue 14724](https://redmine.pfsense.org/issues/14724).
None
**Bug Fixes:**
1. [Redmine Issue 14724](https://redmine.pfsense.org/issues/14724) - the package incorrectly adjusts the rollover hours value when calculating the start times for the rules update cron task and the user has selected either the 12-hour or 6-hour interval. The code incorrectly chooses 24 as a valid hour instead of rolling over to 00, thus creating an invalid cron task start time.
> pfSense-pkg-suricata-7.0.0_1 - Fix Redmine Issue 14724 - Incorrect adjustment from 23 to 00 hours.

- security/pfSense-pkg-snort/Makefile
- security/pfSense-pkg-snort/files/usr/local/pkg/snort/snort.inc
This corrects the bug reported in [Redmine Issue 14723](https://redmine.pfsense.org/issues/14723) for the Snort package in pfSense CE 2.7.0.
None
**Bug Fixes:**
1. [Redmine Issue 14723](https://redmine.pfsense.org/issues/14723) - Snort package incorrectly handles rollover from 23 to 00 hours when calculating rules update cron task times.
> pfSense-pkg-snort-4.1.6_9_RELENG_2_7_0 - Fix Redmine Issue 14723 - incorrect rollover of cron hours value

- sysutils/pfSense-pkg-nut/Makefile
- sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut.xml
- sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut.inc
- sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut_email.php
Note that this PR depends upon the FreeBSD "nut-devel" package rather than the "nut" package.
Please see Redmine issue [14795](https://redmine.pfsense.org/issues/14795) for details behind this change.
> Move from nut-2.8.0 to nut-devel

- sysutils/pfSense-pkg-nut/Makefile
- sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut.xml
- sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut.inc
- sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut_email.php
Implements Redmine issue [14795](https://redmine.pfsense.org/issues/14795). Replacement for PRs #1295 and #1296.
**Note that this PR is dependent on fixes to the FreeBSD sysutils/nut-devel port that were committed [upstream](https://cgit.freebsd.org/ports/log/sysutils/nut-devel) at 2023-10-11 04:28:25 +0000. This PR will not build without those fixes.**
> Move from nut-2.8.0 to nut-devel. Implement #14795

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
Assuming this was intended to be the tab character.  PHP 8 changed strpos so that Integer is no longer cast to a character by strpos.
> Update suricata.inc - fix suricata_Getdirsize tab char

- security/suricata/Makefile
- security/suricata/files/patch-alert-pf.diff
This updates the Suricata binary to the latest 7.0.2 version from upstream. Some cleanup was done to the code in the firewall interface IP change monitoring thread of the custom Legacy Blocking Module, and add additional "belts and suspenders" checks were added to validate kernel routing messages prior to use.
None
**Bug Fixes:**
1. Code cleanup was done in the custom Legacy Blocking plugin used with pfSense and additional data integrity checks were added when processing kernel routing socket messages for the firewall interface IP change monitoring thread. This thread monitors for interface IP additions or deletions and updates an internal automatic Pass List to prevent insertion of blocks for firewall interface IP addresses.
> suricata-7.0.2_1 -- Cleanup custom Legacy Blocking module code and update for 7.0.2 from upstream

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_list_view.php
This updates the Suricata GUI package to support the latest 7.0.2 binary from upstream. This update contains one feature enhancement and two bug fixes.
1. Added new EVE JSON logging option to log Ethernet headers (MAC addresses) from a packet when available. See [Redmine Issue 14954](https://redmine.pfsense.org/issues/14954).
**Bug Fixes:**
1. Fix [Redmine Issue 14955](https://redmine.pfsense.org/issues/14955) - Fatal PHP error generated when attempting to create an EventTime object from an invalid line of text read from the _alerts.log_ or _blocks.log_ files.
2. Fix [Redmine Issue 14956](https://redmine.pfsense.org/issues/14956) - Suricata GUI generates invalid syslog priority values in suricata.yaml file for some drop-down list values.
> pfSense-pkg-suricata-7.0.2 -- Update Suricata GUI package for latest 7.0.2 binary from upstream and fix Redmine issues

- security/snort/Makefile
- security/snort/files/patch-spoink-integration.diff
This update cleans up some of the code in the custom Legacy Blocking Module used with pfSense and adds some safety checks around the routing socket message data before using it in the firewall interface IP change monitoring thread for automatic whitelisting of firewall interface IP addresses.
None
**Bug Fixes:**
None
> snort-2.9.20_5 -- Cleanup code in custom Legacy Blocking module and add safety checks

- security/suricata/Makefile
- security/suricata/distinfo
- security/suricata/files/patch-alert-pf.diff
- security/suricata/files/patch-configure.ac
- security/suricata/pkg-plist
This updates the Suricata binary to the latest 7.0.2 version from upstream. Some cleanup was done to the code in the firewall interface IP change monitoring thread of the custom Legacy Blocking Module, and add additional "belts and suspenders" checks were added to validate kernel routing messages prior to use.
None
**Bug Fixes:**
1. Code cleanup was done in the custom Legacy Blocking plugin used with pfSense and additional data integrity checks were added when processing kernel routing socket messages for the firewall interface IP change monitoring thread. This thread monitors for interface IP additions or deletions and updates an internal automatic Pass List to prevent insertion of blocks for firewall interface IP addresses.
> suricata-7.0.2_1_RELENG_2_7_0 -- Cleanup custom Legacy Blocking module code and update for latest 7.0.2 binary from upstream

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_post_install.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_list_view.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_mgmt.php
This updates the Suricata GUI package to support the latest 7.0.2 binary from upstream. This update contains one feature enhancement and two bug fixes.
1. Added new EVE JSON logging option to log Ethernet headers (MAC addresses) from a packet when available. See [Redmine Issue 14954](https://redmine.pfsense.org/issues/14954).
**Bug Fixes:**
1. Fix [Redmine Issue 14955](https://redmine.pfsense.org/issues/14955) - Fatal PHP error generated when attempting to create an EventTime object from an invalid line of text read from the alerts.log or blocks.log files.
2. Fix [Redmine Issue 14956](https://redmine.pfsense.org/issues/14956) - Suricata GUI generates invalid syslog priority values in suricata.yaml file for some drop-down list values.
> pfSense-pkg-suricata-7.0.2_RELENG_2_7_0 - Update for latest 7.0.2 binary and fix Redmine Issues  14954, 14955 and 14956

- security/suricata/Makefile
- security/suricata/files/patch-alert-pf.diff
This updates the Suricata binary to address the Hyperscan fatal errors and random segfaults identified in Redmine Issues 15080 and 14898.
none
**Bug Fixes:**
1. Fix [Redmine Issue 14898](https://redmine.pfsense.org/issues/14898) and [Redmine Issue 15080](https://redmine.pfsense.org/issues/15080).
> suricata-7.0.2_5 - Fix Redmine Issues 15080 and 14898 - Hyperscan fatal error and random segfault

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php
This update to the Suricata GUI package corrects the issue identified in Redmine Issue 15033.
none
**Bug Fixes:**
1. Fix [Redmine Issue 15033](https://redmine.pfsense.org/issues/15033) - Suricata rule lists can't be manually updated unless the ETOpen Emerging Threats list is enabled.
> pfSense-pkg-suricata-7.0.2_2_RELENG_2_7_2 - Fix Redmine Issue 15033

- security/suricata/Makefile
- security/suricata/files/patch-alert-pf.diff
This update to the Suricata binary addresses two heap memory buffer overflows in the custom Legacy Blocking Module identified during testing/troubleshooting with the llvm Address Sanitizer enabled. The Legacy Blocking Module is a custom output pluging used only with the pfSense version of the package.
In addition to the bug fixes, the code within the custom module was cleaned up a bit and the Pass List logic modified to use separate Radix Trees for IPv4 and IPv6 addresses.
none
**Bug Fixes:**
1. Fix two instances of a heap memory buffer overflow identified in the Pass List processing logic of the custom Legacy Blocking Module. These overflows would randomly corrupt data in user installations resulting in issues with the Hyperscan library and occasional segfaults in the …
> suricata-7.0.2_6 - Fix heap buffer overflows identified by llvm ASAN testing in custom Legacy Blocking module.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This update for the Suricata GUI package adds one new feature, updates the help text for a button on the ALERTS tab, and adds an additional belts-and-suspenders check for invalid timestamps read from log files so we don't create PHP errors when passing the invalid timestamps to the _date_create_from_format()_ PHP function.
1. Add new drop-down selector on the INTERFACES EDIT tab to allow the selection of the Single-Pattern Matcher algorithm. Formerly this parameter was defaulted in the code and not user adjustable.
**Bug Fixes:**
1. Adjust Help text for the CLEAR button on the ALERTS tab to clarify that it only clears the currently active alerts log file and not all logs (original help text was misleading).
2. Add a try-catch exception handler around the call to the PHP …
> pfSense-pkg-suricata-7.0.2_3 - Add single-pattern matcher algo choice, fix help text, and add check for invalid timestamps

- sysutils/pfSense-pkg-nut/Makefile
- sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut.inc
Redmine issue [15119](https://redmine.pfsense.org/issues/15119).
Update nut startup script to avoid ups failure notifications on nut restart following interface changes.
> Version 2.8.2_1

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_geoipupdate.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
- security/pfSense-pkg-suricata/files/usr/local/www/widgets/widgets/suricata_alerts.widget.php
This update to the Suricata GUI package addresses three Redmine Issues and updates the GUI for the latest 7.0.3 binary from upstream.
1. Exposed passlist debugging option in the GUI on the INTERFACE SETTINGS tab.
**Bug Fixes:**
1. [Redmine Issue #15240](https://redmine.pfsense.org/issues/15240), GeoIP2 database download/update procedure broken due to recent MaxMind API change.
2. [Redmine Issue #15241](https://redmine.pfsense.org/issues/15241), add protection for blank lines in alerts.log to Suricata Dashboard Widget code.
3. [Redmine Issue #15242](https://redmine.pfsense.org/issues/15242), examine all calls to _write_config()_ to see when it is appropriate to set "$backup" parameter to "false" to prevent unneccessary _config.xml_ backups.
> pfSense-pkg-suricata-7.0.3 - Fix Redmine Issues 15240, 15241, and 15242. Update for latest 7.0.3 upstream binary

- security/suricata/Makefile
- security/suricata/distinfo
- security/suricata/files/patch-alert-pf.diff
- security/suricata/files/patch-hugepages.diff
This update for the Suricata binary adds enhanced error checking and code optimization to the Legacy Blocking Mode custom output plugin along with support for the latest 7.0.3 binary from upstream. To workaround a temporary upstream bug, the patch file _patch-hugepages.diff_ has been added to bypass NUMA snapshot checks when running on FreeBSD. This patch file can be removed when upstream corrects the bug.
Release Notes for Suricata v7.0.3 can be found here: [https://forum.suricata.io/t/suricata-7-0-3-and-6-0-16-released/4468](https://forum.suricata.io/t/suricata-7-0-3-and-6-0-16-released/4468).
> suricata-7.0.3 - Streamline blocking module, enhance error checking, update for 7.0.3

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
This update for the Suricata GUI package corrects a bug identified by [Redmine Issue 15312](https://redmine.pfsense.org/issues/15312).
none
**Bug Fixes:**
1. Fix [Redmine Issue 15312](https://redmine.pfsense.org/issues/15312) - Unable to load rules page with no categories selected.
> pfSense-pkg-suricata-7.0.3_1_RELENG_2_7_2 - Fix Redmine 15312, unable to load rules tab with no categories selected

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
This update to the Suricata GUI package refactors the original fix for [Redmine Issue 15350](https://redmine.pfsense.org/issues/15350). The original code contained a logic error.
none
**Bug Fixes:**
1. Refactor code for the [Redmine 15350 Issue](https://redmine.pfsense.org/issues/15350) fix as the original code had a logic flaw resulting in the user-specified PHP Memory Limit still not being honored.
> pfSense-pkg-suricata-7.0.4_1_RELENG_2_7_2 -- Refactor fix for Redmine Isseu 15350.

- sysutils/pfSense-pkg-nut/Makefile
- sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut.inc
Redmine issue [15393](https://redmine.pfsense.org/issues/15393).
- Move from the development version (nut-devel) back to the release version (nut>=2.8.2).
- Complete the update for PHP 8 and use config_get_path() for all config access.
Note that nut-2.8.2 is already present in pfSense / FreeBSD-ports.
> Return to the ga version of NUT (2.8.2)

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php
This updates the Suricata GUI package to support the latest 7.0.6 version of the binary from upstream. Also backported three small PHP fixes from the pfSense DEVEL branch submitted by @marcos-ng.
none
**Bug Fixes:**
1. Move to config assessors.
> pfSense-pkg-suricata-7.0.6_RELENG_2_7_2 - Update GUI package to support latest 7.0.6 version from upstream.

- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
I made some changes in the Finnish list repo. From now on, please use this url as the source file for the list.
> Update the Finnish list source url

- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
Changed from a dead feed to a maintained feed
The current Ejrv_VPNv doesn’t exist.
Found a replacement at https://github.com/X4BNet/lists_vpn
> Updated VPN pfblockerng feed (dead feed)

- net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_dnsbl.php
- net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_dnsbl.php
Enable Logging (`aliaslog`) is always hidden because List Action (`action`) is not a checkbox, it is a dropdown.
`dnsbl_ip_text_in` and `dnsbl_ip_text_out` don't appear to exist.
> Fix pfBlockerNg DNSBL IP Enable Logging input issue

- security/pfSense-pkg-suricata/Makefile
This updates the GUI package to support the latest v7.0.7 binary Suricata version from upstream. There are no other package code changes in this update.
none
**Bug Fixes:**
none
> pfSense-pkg-suricata-7.0.7 - Update Suricata GUI package to support latest 7.0.7 binary from upstream.

- security/pfSense-pkg-suricata/Makefile
This updates the GUI package to support the latest v7.0.7 binary Suricata version from upstream. There are no other package code changes in this update.
none
**Bug Fixes:**
none
> pfSense-pkg-suricata-7.0.7_RELENG_2_7_2 - Update Suricata GUI package to support latest v7.0.7 binary.

- net-mgmt/pfSense-pkg-zabbix-agent/Makefile
- net-mgmt/pfSense-pkg-zabbix-agent/files/usr/local/share/pfSense-pkg-zabbix-agent/info.xml
- net-mgmt/pfSense-pkg-zabbix-proxy/Makefile
- net-mgmt/pfSense-pkg-zabbix-proxy/files/usr/local/share/pfSense-pkg-zabbix-proxy/info.xml
[Redmine Issue 13444](https://redmine.pfsense.org/issues/13444)
Fixes the permissions issue for the zabbix agent and proxy packages log files that occurs upon log rotation.
The log rotation would incorrectly set the user/group to the (default) `root:wheel` and set (default) permissions `600`.
This would prevent the zabbix agent and proxy from writing to their log files until their services were restarted.
This issue would appear in the logs `Status > System Logs > Packages > Zabbix Agent/Proxy` as follows:
```
zabbix_agentd [75082]: failed to open log file: [13] Permission denied
zabbix_agentd [75082]: failed to open log file: [13] Permission denied
zabbix_agentd [75082]: failed to open log file: [13] Permission denied
zabbix_agentd [75082]: failed to open log file: [13] Permission denied …
```
> Fix Redmine 13444 - Add zabbix agent+proxy package log files owner and mode (fixes log rotations)

- sysutils/pfSense-pkg-node_exporter/Makefile
- sysutils/pfSense-pkg-node_exporter/files/usr/local/share/pfSense-pkg-node_exporter/interface-collector.py
This fix resolves bug [#13214](https://redmine.pfsense.org/issues/13214)
I was seeing this error on my pfsense install with ArpWatch enabled
This code checks the element exists before trying to assign the text value, if it does not exist an empty string is assigned instead.
> Fix: Bug #13214 AttributeError: 'NoneType' object has no attribute 'text'

- security/pfSense-pkg-suricata/Makefile
This updates the Suricata GUI package to support the latest 7.0.8 binary from upstream. There are no other code changes in this GUI update.
None
**Bug Fixes:**
None
> pfSense-pkg-suricata- Update Suricata GUI package to 7.0.8. Fixes Redmine 15981.

- security/pfSense-pkg-suricata/Makefile
This updates the Suricata GUI package to support the latest 7.0.8 binary from upstream. There are no other code changes in the GUI package with this update.
None
**Bug Fixes:**
None
> pfSense-pkg-suricata_RELENG_2_7_2 - Update Suricata GUI package to 7.0.8. Fixes Redmine 15981.

- security/pfSense-pkg-suricata/Makefile
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_cron_misc.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php
- security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_files.php
- security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
- security/pfSense-pkg-suricata/files/usr/local/www/widgets/include/widget-suricata.inc
- security/pfSense-pkg-suricata/files/usr/local/www/widgets/widgets/suricata_alerts.widget.php
This update to the GUI package addresses one Redmine Bug Report and a Redmine Feature Request.
1. [Redmine Feature Request #16009](https://redmine.pfsense.org/issues/16009) - Use the built-in UNIX control socket interface to communicate certain actions to the running Suricata binary.
**Bug Fixes:**
1. [Redmine Issue #16008](https://redmine.pfsense.org/issues/16008) - Improperly double-quoted constants for SIGHUP and SIGUSR2.
> pfSense-pkg-suricata-7.0.8_1_RELENG_2_7_2 - Fix Redmine Issues 16008 and 16009.

- net/pfSense-pkg-ntopng/Makefile
- net/pfSense-pkg-ntopng/files/usr/local/pkg/ntopng.inc
- net/pfSense-pkg-ntopng/files/usr/local/pkg/ntopng.xml
Implements Redmine #15976 ([https://redmine.pfsense.org/issues/15976](https://redmine.pfsense.org/issues/15976))
If both IPv4 and IPv6 server listen are enabled, the IPv4 address will not work. While the current version of ntopng accepts a list for listen address, it only uses the last element in the list. This means that both an IPv4 and IPv6 listen address cannot be provided at the same time. Hopefully this will be fixed upstream at some point in the future. Until then, we limit the listen selection to one protocol.
Additionally, bracket the address for IPv6.
> Fix ntopng listen options

- net/pfSense-pkg-mDNS-Bridge/Makefile
- net/pfSense-pkg-mDNS-Bridge/files/etc/inc/priv/mdns-bridge.priv.inc
- net/pfSense-pkg-mDNS-Bridge/files/usr/local/pkg/mdns-bridge.inc
- net/pfSense-pkg-mDNS-Bridge/files/usr/local/pkg/mdns_bridge.xml
- net/pfSense-pkg-mDNS-Bridge/files/usr/local/www/mdns-bridge.php
- net/pfSense-pkg-mDNS-Bridge/files/usr/local/www/shortcuts/pkg_mdns-bridge.inc
Implements redmine 16361 https://redmine.pfsense.org/issues/16361)
This update addresses an issue with mdns-bridge rejecting mDNS packets containing zero length records, and adds filtering of link local addresses from forwarded mDNS records.
> Update to mDNS-Bridge 2.1
