net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng.php
* Add missing $g global setting
* Adjust log messages (Installation and MaxMind Cron Updates)
=> pfBlockerNG - update pfblockerng.php

net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc
* Remove '-cgi' from php commands, causing issues with max_execution_time
* Add/Change syslog notice messages.
=> pfBlockerNG - update pfblockerng.inc

net/pfSense-pkg-pfBlockerNG/Makefile, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl_easylist.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl_lists.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_sync.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_top20.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_v4lists.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_v6lists.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/share/pfSense-pkg-pfBlockerNG/info.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_alerts.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_log.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_update.php
* Remove obsoleted XML tags
* Add breadcrumbs to title
* Mods to display_top_tabs
* Mods to update tab Radio buttons
* Fix $result array
* Bump version to 2.0.4
=> pfBlockerNG - Updates

net/pfSense-pkg-pfBlockerNG/Makefile, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc, net/pfSense-pkg-pfBlockerNG/files/usr/local/share/pfSense-pkg-pfBlockerNG/info.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng.php
* Fix incorrect function call.
=> pfBlockerNG - version 2.0.6

net/pfSense-pkg-haproxy-devel/Makefile
=> haproxy-devel, fix build

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy.xml, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_gui.inc, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_htmllist.inc, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_sync.sh, net/pfSense-pkg-haproxy-devel/files/usr/local/share/pfSense-pkg-haproxy-devel/info.xml, net/pfSense-pkg-haproxy-devel/pkg-plist
haproxy-devel, Asynchronous XMLRPC sync, and fixed issues due to changed paths. pkg v 0.38
=> haproxy-devel, Asynchronous XMLRPC sync, and fixed issues due to changed paths. pkg v 0.38

net/pfSense-pkg-Quagga_OSPF/Makefile, net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd.inc, net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd.xml, net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd_interfaces.xml, net/pfSense-pkg-Quagga_OSPF/files/usr/local/pkg/quagga_ospfd_raw.xml, net/pfSense-pkg-Quagga_OSPF/files/usr/local/share/pfSense-pkg-Quagga_OSPF/info.xml
Please see https://github.com/pfsense/pfsense-packages/pull/1227
=>  Allow to select OSPF Network Type in the Quagga OSPFd > Interface Settings

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
haproxy-devel, fix rc.d/haproxy.sh pkg v0.40
=> haproxy-devel, fix rc.d/haproxy.sh pkg v0.40

security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
=> [suricata_rulesets]: Fix typo

net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.sh, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl_easylist.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_dnsbl_lists.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_sync.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_top20.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_v4lists.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_v6lists.xml, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_alerts.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_alerts_ar.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_log.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_threats.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_update.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/www/index.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/widgets/javascript/pfblockerng.js, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
* Styling and text improvements
* Add collapsible menus where appropriate
* Change infoblock from id= to class=
* Add id to Widget Wrench customization menu
* Add 'Advanced Outbound Firewall Rule' customizations
* Improve 'Max Download Failure' code
* Fix Emerging Threats IQRisk code issue
* Add header to Update Tab to stop NGINX from buffering output
* Add a line space before Update Tab 'Run' and 'View' button text (Temporary fix until CSS issue is resolved to maintain a space between a button Text and an embeded fa Icon.)
=> pfBlockerNG v2.07

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php, net/pfSense-pkg-haproxy/Makefile, net/pfSense-pkg-haproxy/files/usr/local/pkg/haproxy/haproxy.inc, net/pfSense-pkg-haproxy/files/usr/local/pkg/haproxy/haproxy_htmllist.inc, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_files.php, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_global.php, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_listeners.php, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_listeners_edit.php, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_pool_edit.php, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_pools.php, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_stats.php, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_templates.php, net/pfSense-pkg-haproxy/files/usr/local/www/widgets/widgets/haproxy.widget.php
haproxy, sync files from haproxy-devel pkg v0.42
haproxy-devel, check for proper 'process', dont report php background script memory usage pkg v0.42
=> haproxy, sync files from haproxy-devel pkg v0.42

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners.php, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php
haproxy-devel, pkg 0.44 fix moving frontends for some frontendnames, fix OCSP renewal script, textual correction for explanation of condition/action items
=> haproxy-devel, pkg 0.44 fix moving frontends for some frontendnames & OCSP renewal

sysutils/pfSense-Status_Monitoring/files/usr/local/www/rrd_fetch_json.php, sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
Resolution option
Graph type option (line/bar) (not functional yet)
=> Status / monitoring   resolution & type

sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
Include graph meta data to provide context to screen captures and print outs.  As well as when settings panel is collapsed/hidden.
=> Status Monitoring - Graph Meta Data

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_htmllist.inc, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pool_edit.php, net/pfSense-pkg-haproxy/Makefile, net/pfSense-pkg-haproxy/files/usr/local/pkg/haproxy/haproxy.inc, net/pfSense-pkg-haproxy/files/usr/local/pkg/haproxy/haproxy_htmllist.inc, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_pool_edit.php
haproxy, haproxy-devel, pkg 0.46 fix error in certificate manager when no backends have been configured
=> haproxy, haproxy-devel, pkg 0.46 fix error in certificate manager when no backends have been configured

net/pfSense-pkg-Avahi/pkg-message
Trim text width and add newline at EOF.
=> Update avahi pkg-message

sysutils/pfSense-Status_Monitoring/files/usr/local/www/rrd_fetch_json.php, sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
It actually defaults to highest possible resolution.
=> Status Monitoring - Custom Resolution Terminology

net/pfSense-pkg-pfBlockerNG/Makefile, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc
* Properly escape variables for rc dnsbl.sh script
=> pfBlockerNG - version 2.0.16

net/pfSense-pkg-pfBlockerNG/Makefile, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc
* Fix issue with EasyPrivacy parsing
=> pfBlockerNG - version 2.0.17

sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
See PR https://github.com/pfsense/pfsense/pull/2989
This is a dependent change that will allow the statusmonitoringsettingspanel to be specified per user.
It needs the PR in the main pfSense repo first.
=> Feature #6388 custom profile per user

net/pfSense-pkg-cellular/Makefile, net/pfSense-pkg-cellular/files/etc/inc/priv/cellular.priv.inc, net/pfSense-pkg-cellular/files/pkg-deinstall.in, net/pfSense-pkg-cellular/files/pkg-install.in, net/pfSense-pkg-cellular/files/usr/local/pkg/cellular.inc, net/pfSense-pkg-cellular/files/usr/local/pkg/cellular.xml, net/pfSense-pkg-cellular/files/usr/local/pkg/pkg_cellular.inc, net/pfSense-pkg-cellular/files/usr/local/sbin/cellular.py, net/pfSense-pkg-cellular/files/usr/local/share/pfSense-pkg-cellular/info.xml, net/pfSense-pkg-cellular/files/usr/local/www/widgets/widgets/cellular.widget.php, net/pfSense-pkg-cellular/pkg-descr, net/pfSense-pkg-cellular/pkg-plist
Hi,
this package adds a widget and information for cellular LTE/3G modems to pfSense.
It does work with certain Huawei modems that offer 2 AT command ports.
Best
Sven
=> Package for cellular modem information

net/pfSense-pkg-haproxy/Makefile, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_global.php, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_listeners_edit.php, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_pool_edit.php
Some package cosmetics. 
@PiBa-NL please check this is case you have some other stuff to commit. (BTW, 1.6.10 is out.)
=> haproxy - Update outdated/deprecated documentation links; typo plus English improvements

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_htmllist.inc, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_pool_edit.php
haproxy-devel, pkg v0.52, shorten frontend descriptions, typo's, doc links
=> haproxy-devel, pkg v0.52, shorten frontend descriptions, typo's, doc links

net/pfSense-pkg-siproxd/Makefile, net/pfSense-pkg-siproxd/files/usr/local/pkg/siproxd.xml
Pretty sure it will make the guy who made the request 6,5 years ago extremely happy this Xmas, LOL.
=> siproxd - make virtual IPs available in interfaces selection (Feature #556)

www/pfSense-pkg-squid/Makefile, www/pfSense-pkg-squid/files/usr/local/pkg/squid.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_antivirus.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_auth.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_cache.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_nac.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_reverse_general.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_reverse_peer.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_reverse_redir.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_reverse_sync.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_reverse_uri.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_sync.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_traffic.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_upstream.xml, www/pfSense-pkg-squid/files/usr/local/share/pfSense-pkg-squid/info.xml, www/pfSense-pkg-squid/pkg-descr
=> Squid - improve bootstrap conversion and descriptions

www/pfSense-pkg-squid/files/usr/local/pkg/squid.xml
Fix description to match the one in devel branch.
=> Squid - RELENG_2_3 sync up

net/pfSense-pkg-cellular/Makefile, net/pfSense-pkg-cellular/files/usr/local/pkg/cellular.inc, net/pfSense-pkg-cellular/files/usr/local/sbin/cellular.py, net/pfSense-pkg-cellular/files/usr/local/www/widgets/widgets/cellular.widget.php
Hi,
I fixed a few bugs in the cellular package that came up while we tested it.
Best
Sven
=> Fixes for the cellular package

sysutils/pfSense-upgrade/Makefile, sysutils/pfSense-upgrade/files/pfSense-upgrade
Add GitSync options support.
Minimal, Diff, Show Files, Show Command, Dry Run
=> System Update Settings - GitSync Options

sysutils/pfSense-pkg-syslog-ng/Makefile, sysutils/pfSense-pkg-syslog-ng/files/usr/local/www/syslog-ng_log_viewer.php
=> syslog-ng fixes - use full paths to executables and do some sanity checking

www/pfSense-pkg-Lightsquid/Makefile, www/pfSense-pkg-Lightsquid/files/usr/local/pkg/lightsquid.inc
See comments in the file for explanation. Lighttpd == POS.
=> lightsquid - Hack around incredible lighttpd idiocy with HTTPS/IPv6

security/pfSense-pkg-acme/Makefile, security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme.inc
This looks like a typo, but I have no idea where his output goes and what it effects.
=> pfsense-pkg-acme challenge typo

net/pfSense-pkg-freeradius2/Makefile, net/pfSense-pkg-freeradius2/files/usr/local/pkg/freeradius.inc
https://redmine.pfsense.org/issues/7197
=> Freeradius - Fix a typo breaking LDAP auth (Bug #7197)

security/pfSense-pkg-acme/Makefile, security/pfSense-pkg-acme/files/usr/local/pkg/acme/acme.inc, security/pfSense-pkg-acme/files/usr/local/www/acme/acme_accountkeys_edit.php, security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates.php, security/pfSense-pkg-acme/files/usr/local/www/acme/acme_certificates_edit.php
acme, fix DNS-PowerDNS selection > dns_pdns
=> acme, fix DNS-PowerDNS selection > dns_pdns

sysutils/pfSense-pkg-LCDproc/files/usr/local/pkg/lcdproc_client.php
While cleaning up commits for #271 I somehow introduced diff characters into the pull request.
=> LCDproc merge error

dns/pfSense-pkg-bind9/Makefile, dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.inc, dns/pfSense-pkg-bind9/files/usr/local/www/widgets/widgets/bind.widget.php
Please do this together with https://github.com/pfsense/FreeBSD-ports/pull/319 to avoid useless version bumps.
=> BIND widget cleanup, fix license

sysutils/pfSense-pkg-Cron/Makefile, sysutils/pfSense-pkg-Cron/files/usr/local/pkg/cron.inc, sysutils/pfSense-pkg-Cron/files/usr/local/pkg/cron.xml, sysutils/pfSense-pkg-Cron/files/usr/local/www/packages/cron/cron.php, sysutils/pfSense-pkg-Cron/files/usr/local/www/packages/cron/cron_edit.php
- Add reason to write_config() calls
- Clean up some no longer needed code
=> cron pkg - Add reason to write_config() calls

security/pfSense/Makefile
Abandoned tunnel service, see http://www.iot-inc.com/gogo6/
=> Remove net/gogoc from pfSense

net-mgmt/pfSense-pkg-net-snmp/Makefile, net-mgmt/pfSense-pkg-net-snmp/files/usr/local/pkg/net-snmp.inc
Make the rcfiles verbose.
Bump PORTREVISION.
=> pfSense-pkg-net-snmp: Sync net-snmptrapd in the initialization process

net/pfSense-pkg-cellular/Makefile, net/pfSense-pkg-cellular/files/usr/local/sbin/cellular.py, net/pfSense-pkg-cellular/files/usr/local/www/widgets/widgets/cellular.widget.php
Hi,
we fixed multiple problems in the cellular package:
1. Carrier was not displayed in Widget
2. Signal strength scale was off by 1
3. AT commands are tried for 3 times since the port is sometimes busy
Best
Sven
=> Cellular Package Fixes

security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
This is to correct Bug #7578 (unblock links do not unblock on suricata alerts page).
Bug for reference: https://redmine.pfsense.org/issues/7578
=> Correct unblock src/dest IP method call.

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
These changes allow more granular control over the eve output.
=> pfSense-pkg-suricata:  Granular eve output settings

sysutils/pfSense-pkg-Service_Watchdog/Makefile, sysutils/pfSense-pkg-Service_Watchdog/files/usr/local/www/services_servicewatchdog.php, sysutils/pfSense-pkg-Service_Watchdog/files/usr/local/www/services_servicewatchdog_add.php
Part of https://redmine.pfsense.org/issues/204
=> sysutils/pfSense-pkg-Service_Watchdog: Add reason to write_config() calls

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php, net/pfSense-pkg-haproxy-devel/files/usr/local/www/shortcuts/pkg_haproxy.inc, net/pfSense-pkg-haproxy/Makefile, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_global.php, net/pfSense-pkg-haproxy/files/usr/local/www/shortcuts/pkg_haproxy.inc
haproxy, haproxy-devel, fix saving global settings without needing to disable/enable the package, fix link for service settings icon.
=> haproxy, haproxy-devel, fix saving global settings

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php, net/pfSense-pkg-haproxy-devel/files/usr/local/www/shortcuts/pkg_haproxy.inc, net/pfSense-pkg-haproxy/Makefile, net/pfSense-pkg-haproxy/files/usr/local/www/haproxy/haproxy_global.php, net/pfSense-pkg-haproxy/files/usr/local/www/shortcuts/pkg_haproxy.inc
haproxy-devel, use haproxy-devel (currently 1.8rc) from ports
=> haproxy-devel, use haproxy-devel (currently 1.8rc) from ports

dns/pfSense-pkg-bind9/files/usr/local/pkg/bind.inc, dns/pfSense-pkg-bind9/files/usr/local/pkg/bind_zones.xml
Resolves [redmine issue 8189](https://redmine.pfsense.org/issues/8189)
=> Add working JavaScript toggles

net-mgmt/pfSense-pkg-lldpd/Makefile, net-mgmt/pfSense-pkg-lldpd/files/etc/inc/priv/lldpd.priv.inc, net-mgmt/pfSense-pkg-lldpd/files/pkg-deinstall.in, net-mgmt/pfSense-pkg-lldpd/files/pkg-install.in, net-mgmt/pfSense-pkg-lldpd/files/usr/local/pkg/lldpd.xml, net-mgmt/pfSense-pkg-lldpd/files/usr/local/pkg/lldpd/lldpd.inc, net-mgmt/pfSense-pkg-lldpd/files/usr/local/share/pfSense-pkg-lldpd/info.xml, net-mgmt/pfSense-pkg-lldpd/files/usr/local/www/lldpd_settings.php, net-mgmt/pfSense-pkg-lldpd/files/usr/local/www/lldpd_status.php, net-mgmt/pfSense-pkg-lldpd/files/usr/local/www/shortcuts/pkg_lldpd.inc, net-mgmt/pfSense-pkg-lldpd/pkg-descr, net-mgmt/pfSense-pkg-lldpd/pkg-plist
Add support for the lldpd package, which provides up to date support for 802.1ab.
=> Add new package pfSense-pkg-lldpd

net-mgmt/pfSense-pkg-Telegraf/Makefile, net-mgmt/pfSense-pkg-Telegraf/files/usr/local/pkg/telegraf.inc
=> Updated pkg inc file for pf metrics inclusion (native Telegraf plugin)

net/pfSense-pkg-pfBlockerNG-devel/Makefile, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
=> pfSense-pkg-pfBlockerNG-devel - Update Quidsup Feed URLs

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_templates.php
haproxy-devel, php7 fix for haproxy_global.php and templates
=>  haproxy-devel, php7 fix for haproxy_global.php and templates

net/pfSense-pkg-pfBlockerNG-devel/Makefile, net/pfSense-pkg-pfBlockerNG-devel/files/etc/inc/priv/pfblockerng.priv.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.sh, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_alerts.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_blacklist.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category_edit.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_dnsbl.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_general.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_ip.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_log.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_sync.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_threats.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_update.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/widgets/pfblockerng.widget.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/wizards/pfblockerng_wizard.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/wizards/pfblockerng_wizard.xml, net/pfSense-pkg-pfBlockerNG-devel/pkg-plist
* PHPv7 improvements
* Improve input validations
* Add Wizard for default (entry level) installation
* Add ASN Reporting functionality
* Improve ASN -> IP Conversion function
* Integrate textproc/jq port
* Improve Auto Rule Order functions
* IP Suppression default enabled on new installations
* Improve installation script and logging
=> pfBlockerNG-devel - v2.2.5_18

net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php
...in HAProxy's main setting page.
PS: maybe an idea to remove or update `CONTRIBUTING.md` added in 8aeea93de4f77074a0f72d77ff4f63ee710bf417? It points to the _real_ FreeBSD ports handbook for submitting patches, so it's a bit confusing.
=> Fixed typos and improved some awkward wording

mail/pfSense-pkg-mailreport/Makefile, mail/pfSense-pkg-mailreport/files/etc/inc/mail_reports.inc, mail/pfSense-pkg-mailreport/files/usr/local/www/status_mail_report_edit.php
Add minute management - Ticket #8416
Correction to be able to send over multiples addresses - Ticket #9185
Change TLS autostart to be always true, it should be the better default value in any case, as explained in the phpmailer class. - Ticket #7437
=> Ticket #8416 - Ticket #9185 - Ticket #7437 - MailReport Package

net/pfSense-pkg-pfBlockerNG/Makefile, net/pfSense-pkg-pfBlockerNG/files/etc/inc/priv/pfblockerng.priv.inc, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.inc, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.sh, net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng.php, net/pfSense-pkg-pfBlockerNG/files/usr/local/www/pfblockerng/pfblockerng_alerts.php
* Update Maxmind library from GeoIP -> [ libmaxminddb Port](https://www.freshports.org/net/libmaxminddb)
=>  pfSense-pkg-pfBlockerNG v2.1.4_15

net/pfSense-pkg-pfBlockerNG-devel/Makefile, net/pfSense-pkg-pfBlockerNG-devel/files/etc/inc/priv/pfblockerng.priv.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng.xml, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.sh, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng_extra.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/shallalist_global_usage, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/ut1_global_usage, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfBlockerNG.js, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_alerts.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_blacklist.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category_edit.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_dnsbl.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_general.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_ip.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_log.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_sync.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_threats.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_update.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/www/index.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/include/widget-pfblockerng.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/javascript/pfblockerng.js, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/widgets/pfblockerng.widget.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/wizards/pfblockerng_wizard.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/wizards/pfblockerng_wizard.xml
* Update Maxmind library from GeoIP -> [ libmaxminddb Port](https://www.freshports.org/net/libmaxminddb)
* Relocate EasyList to the Feeds tab to be added like all other Feeds.
* Modify EasyList parser
* Allow other Easylist/ADBlock/uBlock/ADGuard feed syntax to the DNSBL parser
* Add more EasyList Language specific feeds
* Add "Server.max-request-size = 1" to Lighttpd config
* Alerts Tab/Logs: Collect NAT IP addresses by Target:Port
* Improve SQLite3 DB validations
* Fix issue causing DNSBL/Unbound Counters to report over 100%
=>  pfSense-pkg-pfBlockerNG v2.2.5_20

security/pfSense-pkg-openvpn-client-export/Makefile, security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export.php
Re-align buttons from this:
To this:
=> Tidy up SIP phone config download buttons

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy/Makefile
https://redmine.pfsense.org/issues/9521
=> Bump haproxy package versions

sysutils/pfSense-pkg-System_Patches/Makefile, sysutils/pfSense-pkg-System_Patches/files/usr/local/pkg/patches.inc, sysutils/pfSense-pkg-System_Patches/files/usr/local/www/system_patches.php, sysutils/pfSense-pkg-System_Patches/files/usr/local/www/system_patches_edit.php
Redmine Issue: https://redmine.pfsense.org/issues/9742
Adds ability to log patch id to system log
=> patching logging

sysutils/pfSense-pkg-apcupsd/Makefile, sysutils/pfSense-pkg-apcupsd/files/usr/local/pkg/apcupsd.inc
Redmine issue: https://redmine.pfsense.org/issues/9811
=> #9811: allow to set BATTERYLEVEL and MINUTES to -1

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_threats.php
shodan search query based on IP changed a while so keep this on track.
=> update shodan search engine

net/pfSense-pkg-cellular/Makefile, net/pfSense-pkg-cellular/files/etc/devd/cellular.conf, net/pfSense-pkg-cellular/files/usr/local/bin/cellular_dev.py, net/pfSense-pkg-cellular/files/usr/local/sbin/cellular.py
Add another modem and compatibility with python3
=> Cellular Package Upgrade for 2.4.5

net-mgmt/pfSense-pkg-softflowd/Makefile, net-mgmt/pfSense-pkg-softflowd/files/usr/local/pkg/softflowd.inc
Redmine Issue: https://redmine.pfsense.org/issues/10220
This PR fix input validation, to allow select PSAMP protocol version
=> Fix softflow input validation. Issue #10220

net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc
Correct MaxMind registration wording.
Signed-off-by: Hans Geiblinger <cybrnook2002@yahoo.com>
=> Correct MaxMind registration wording (stable)

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng_install.inc
Correct MaxMind registration wording.
Signed-off-by: Hans Geiblinger <cybrnook2002@yahoo.com>
=> Correct MaxMind registration wording (devel)

net-mgmt/pfSense-pkg-arpwatch/Makefile, net-mgmt/pfSense-pkg-arpwatch/files/usr/local/pkg/arpwatch.inc, net-mgmt/pfSense-pkg-arpwatch/files/usr/local/pkg/arpwatch.xml
Redmine Issue: https://redmine.pfsense.org/issues/10474
Allow to suppress specific MACs from ARPwatch notifications
=> ARPwatch: Suppress notifications for specific MACs. Issue #10474

net/pfSense-pkg-frr/Makefile, net/pfSense-pkg-frr/files/etc/inc/priv/frr.priv.inc, net/pfSense-pkg-frr/files/usr/local/bin/frrctl, net/pfSense-pkg-frr/files/usr/local/pkg/frr.inc, net/pfSense-pkg-frr/files/usr/local/pkg/frr.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_bfd.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_bgp.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_bgp_advanced.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_bgp_aspaths.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_bgp_communities.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_bgp_neighbors.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_global_acls.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_global_prefixes.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_global_raw.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_global_routemaps.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_ospf.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_ospf6.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_ospf6_interfaces.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_ospf_areas.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/frr_ospf_interfaces.xml, net/pfSense-pkg-frr/files/usr/local/pkg/frr/inc/frr_bfd.inc, net/pfSense-pkg-frr/files/usr/local/pkg/frr/inc/frr_validation.inc, net/pfSense-pkg-frr/files/usr/local/pkg/frr/inc/frr_zebra.inc, net/pfSense-pkg-frr/files/usr/local/www/status_frr.php, net/pfSense-pkg-frr/pkg-plist
https://redmine.pfsense.org/issues/10441
=> Integration of bfd daemon (Ticket #10441)

security/pfSense-pkg-openvpn-client-export/Makefile, security/pfSense-pkg-openvpn-client-export/files/usr/local/pkg/openvpn-client-export.inc, security/pfSense-pkg-openvpn-client-export/files/usr/local/www/vpn_openvpn_export.php
Allow to create silent Windows Installers
=> OpenVPN Client Export silent installer. Implements #10858

net-mgmt/pfSense-pkg-bandwidthd/Makefile, net-mgmt/pfSense-pkg-bandwidthd/files/usr/local/pkg/bandwidthd.inc, net-mgmt/pfSense-pkg-bandwidthd/files/usr/local/pkg/bandwidthd.xml
Remove PostgreSQL feature from package
current bandwidthd port don't support postgresql:
https://github.com/pfsense/FreeBSD-ports/blob/e8b54d83912d6390289df50bd8a1806447eabacb/net-mgmt/bandwidthd/Makefile#L19-L22
removed by port maintainer? (not found in history)
=> Remove bandwidthd pgsql options. Issue #9809

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/www/shortcuts/pkg_haproxy.inc
[x]Redmine Issue: https://redmine.pfsense.org/issues/10884
[x]Ready for review
=> Update pkg_haproxy.inc issue 10884

net-mgmt/pfSense-pkg-net-snmp/Makefile, net-mgmt/pfSense-pkg-net-snmp/files/usr/local/pkg/net-snmp.inc, net-mgmt/pfSense-pkg-net-snmp/files/usr/local/pkg/net-snmp_trapgen.xml
Support up to three SNMPv3 Trap/Inform notification hosts
=> Net-SNMP SNMPv3 Trap/Inform. Implements #10897

benchmarks/pfSense-pkg-iperf/Makefile, benchmarks/pfSense-pkg-iperf/files/usr/local/pkg/iperf.xml, benchmarks/pfSense-pkg-iperf/files/usr/local/pkg/iperfserver.xml
=> iPerf port comment fix. Issue #10939

net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php
=> HAProxy Global Settings Typo Fix

sysutils/pfSense-Status_Monitoring/Makefile, sysutils/pfSense-Status_Monitoring/files/usr/local/www/status_monitoring.php
Check user privileges to test if the user is allowed to disable graphing / reset data.
=> Status Monitoring privs check. Fixes #7375

www/pfSense-pkg-squid/Makefile, www/pfSense-pkg-squid/files/usr/local/pkg/squid.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_antivirus.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_auth.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_cache.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_nac.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_sync.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_traffic.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_upstream.xml, www/pfSense-pkg-squid/files/usr/local/pkg/squid_users.xml, www/pfSense-pkg-squid/files/usr/local/www/squid_monitor.php, www/pfSense-pkg-squid/files/usr/local/www/status_squid.php, www/pfSense-pkg-squid/pkg-plist
Show the `squidclient mgr:info` output on the status page
=> Squid status page. Implements #9721

security/pfSense-pkg-snort/Makefile, security/pfSense-pkg-snort/files/usr/local/www/snort/snort_interfaces_edit.php
input validation to prevent users from choosing an unsupported card
=> Snort netmap support check. Implements #10950

security/pfSense-pkg-stunnel/Makefile, security/pfSense-pkg-stunnel/files/usr/local/pkg/stunnel.inc
Same problem as: https://github.com/pfsense/FreeBSD-ports/pull/979
=> Fixing XMLRPCSync - Stunnel

net/pfSense-pkg-pfBlockerNG-devel/Makefile, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
=> pfBlockerNG feeds update. Issue #11107

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
=> pfBlocker phishing feeds update. Implements #11113

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
=> Suricata del icon fix for 2.4.5. Issue #11136

net/pfSense-pkg-pfBlockerNG-devel/Makefile
=> Add rsync to pfBlockerNG RUN_DEPENDS. Fixes #11152

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php
=> Virtual IP link destination fix. Issue #11236

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
=> pfBlockerNG uninstall shell scripts. Fixes #11191

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_alerts.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_threats.php
1) Alerts page - add Yandex.DNS (https://dns.yandex.com);
2) Threat lookup page - add Kaspersky and InterServer.net links, update Google SafeBrowsing/Transparency report link;
=> pfBlockerNG minor update. Implements #11199

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc, security/pfSense-pkg-suricata4/Makefile, security/pfSense-pkg-suricata4/files/usr/local/pkg/suricata/suricata.inc
=> Add WireGuard networks to Suricata VPN pass list. Implements #11385

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy_upgrade_config.inc, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners.php, net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_listeners_edit.php
=> HAProxy CDATA frontend description. Fixes #11680

net/pfSense-pkg-haproxy-devel/files/usr/local/www/haproxy/haproxy_global.php
=> HAProxy service disable fix. Issue #11993

net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
=> HAProxy http-after-response and http-request_replace-path actions support. Implements #10739

net/pfSense-pkg-haproxy-devel/Makefile, net/pfSense-pkg-haproxy-devel/files/usr/local/pkg/haproxy/haproxy.inc
=> HAProxy plugin_certificates() improvements. Fixes #11766

security/pfSense-pkg-snort/Makefile, security/pfSense-pkg-snort/files/usr/local/www/snort/snort_alerts.php
=> Snort DB GID:SID link on the Alerts page. Implements #12221

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_for_rule_updates.php, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_sync.xml, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_blocked.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_define_vars.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_download_updates.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_filecheck.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_files.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_ip_list_mgmt.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_ip_reputation.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_browser.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_logs_mgmt.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_sid_mgmt.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_suppress.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_suppress_edit.php, security/pfSense-pkg-suricata/pkg-plist
How to test:
1) create a custom rule: `alert http any any -> any any (msg:"FILE store all"; filestore; sid:1; rev:1;)`
2) enable EVE JSON log, EVE Output Type = FILE, Tracked-Files Checksum = SHA256, Enable File-Store
3) open any HTTP site
=> Suricata captured Files tab. Implements #9852

security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php
can be merged with https://github.com/pfsense/FreeBSD-ports/pull/1093
=> Suricata Host OS Policy Assignment fix. Issue #6964

security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
should only be merged with suricata 6.x binary!
=> Suricata FTP, HTTP2 and RFB EVE logs support. Implements #12285

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
=> Suricata: show netmap compatible cards in IPS Mode note. Implements #11531

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php
can be merged with https://github.com/pfsense/FreeBSD-ports/pull/1097
=> Suricata GID:SID rule pop-up. Feature #12297

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc
=> pfBlockerNG incorrect CARP VIP advskew value fix. Issue #11964

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
=> pfBlockerNG: remove non-functional feeds. Todo #12351

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_app_parsers.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_filecheck.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_files.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rules.php
=> Suricata improvements. Feature #12317

security/suricata/Makefile, security/suricata/files/patch-netmap.diff
This updates the Suricata binary to the latest upstream patch revision for the netmap multiple host rings feature upgrade.
=> suricata-6.0.3_1 - Update netmap multi-host rings patch to latest upstream edition.

security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc
=> Suricata single IP passlist fix. Issue #12476

security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
=> Suricata netmap device list fix. Issue #11531

security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php
Can be merged with https://github.com/pfsense/FreeBSD-ports/pull/1122
=> Suricata extra rules input validation fix. Issue #12533

security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php
=> Suricata rule categories fix. Issue #12643

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_migrate_config.php, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_filecheck.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_flow_stream.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_global.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_passlist_edit.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_rulesets.php
This updates the Suricata GUI package to the latest 6.0.4 version from pfSense DEVEL.
=> pfSense-pkg-suricata-6.0.4 - Update Suricata GUI package to latest 6.0.4 from DEVEL.

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category_edit.php
=> Fix white font on yellow background

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_safesearch.php
=> pfBlockerNG SafeSearch page input validation fix. Issue #12414

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
=> pfBlockerNG widget sqlite database missing error message update. Fixes #12423

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_blacklist.php
=> pfBlockerNG: DNSBL Category Enable/Disable All buttons fix. Issue #12443

net/pfSense-pkg-pfBlockerNG-devel/Makefile, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfb_dnsbl.doh.conf, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_alerts.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_safesearch.php
* Remove Krisk Feeds (Unreliable)
https://forum.netgate.com/topic/161103/krisk_c19-list-unreliable
* Add Apple iCloud Private Relay to DOH Blocklist https://www.reddit.com/r/pfBlockerNG/comments/rpui3y/icloud_private_relay_allowing_ads_through/
* Fix Alerts Tab ($chart_events) error 
https://forum.netgate.com/topic/168152/error-in-devel-package
=> pfBlockerNG-devel v3.1.0_1

net/pfSense-pkg-pfBlockerNG-devel/Makefile, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfb_dnsbl.doh.conf, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.sh, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_alerts.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category_edit.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_safesearch.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_update.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/widgets/widgets/pfblockerng.widget.php
**CHANGELOG**
* Fix widget PHP8 errors
* Fix Feeds not updating with some Cron settings
* Fix issue with auto-sort in IP/DNSBL pages
* Add European public DNS zero.dns0.eu (DoH/DoT/DoQ) to DNSBL DoH/DoT/DoQ blocking
* Fix typo in Widget IP/DNSBL clearing
* Add textproc/gnugrep to fix TLD Wildcard issue.
=> pfBlockerNG-devel v3.2.0_3

net/pfSense-pkg-pfBlockerNG-devel/Makefile, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfblockerng.inc, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_category_edit.php, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json, net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_ip.php
* MaxMind Licence Key Syntax changes
https://dev.maxmind.com/geoip/release-notes/2023?lang=en
* EasyList Header name duplication issue
* Regression with Suppression (localhost and Private IP removal)
=> pfBlockerNG-devel_v3.2.0_4

sysutils/pfSense-pkg-nut/Makefile, sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut.xml, sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut.inc, sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut_email.php
=> Move from nut-2.8.0 to nut-devel

sysutils/pfSense-pkg-nut/files/usr/local/pkg/nut/nut_email.php
Minor tweak to message format for the pending 2.8.1 release of the NUT package as part of Redmine [14795](https://redmine.pfsense.org/issues/14795).
=> Minor tweak to email message for NUT 2.8.1

security/snort/Makefile, security/snort/files/patch-spoink-integration.diff
This update to the Snort binary package adds stability improvements to the Legacy Blocking custom output plugin. It also enhances the logging of pluging operation via syslog.
1. Add logging of certain plugin in actions via _syslog_.
**Bug Fixes:**
1. Fix potential for memory corruption when removing an element from the Linked List containing passlist entries.
=> snort-2.9.20_8_RELENG_2_7_2 - Improve stability and add syslog logging to Legacy Blocking custom module

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces_edit.php
This update for the Suricata GUI package corrects two reported Redmine Issues and supports the latest 7.0.4 version of the upstream Suricata binary.
None
**Bug Fixes:**
1. [Redmine Issue 15333](https://redmine.pfsense.org/issues/15333) - Interface Description not updated properly when add/creating new interface in Suricata.
2. [Redmine Issue 15350](https://redmine.pfsense.org/issues/15350) - Refactor the PHP_INI Memory Setting in suricata.inc so that we honor the new pfSense user configured limit when it is greater than 512MB.
=> pfSense-pkg-suricata-7.0.4 - Fix Redmine Issues 15333 and 15350.

net/pfSense-pkg-pfBlockerNG/files/usr/local/pkg/pfblockerng/pfblockerng.sh
improve performance by 30% or so.
=> pfBlockerNG - sort | uniq to sort -u for improved performance

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/www/pfblockerng/pfblockerng_feeds.json
=> Add dibdot DoH-IP-blocklists feeds. Feature #13135

net-mgmt/pfSense-pkg-zabbix-agent5/Makefile, net-mgmt/pfSense-pkg-zabbix-agent54/Makefile, net-mgmt/pfSense-pkg-zabbix-agent6/Makefile, net-mgmt/pfSense-pkg-zabbix-agent7/Makefile, net-mgmt/pfSense-pkg-zabbix-proxy5/Makefile, net-mgmt/pfSense-pkg-zabbix-proxy54/Makefile, net-mgmt/pfSense-pkg-zabbix-proxy6/Makefile, net-mgmt/pfSense-pkg-zabbix-proxy7/Makefile
https://redmine.pfsense.org/issues/15548
I have added the files for the Zabbix 7 PFSense GUI packages, hopefully this was the missing link to get the new version available.
Ready for review.
=> added Zabbix 7 GUI package for PFSense, Feature: #15548

security/pfSense-pkg-suricata/Makefile, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata.inc, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_check_cron_misc.inc, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_defs.inc, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_generate_yaml.php, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_uninstall.php, security/pfSense-pkg-suricata/files/usr/local/pkg/suricata/suricata_yaml_template.inc, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_alerts.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_files.php, security/pfSense-pkg-suricata/files/usr/local/www/suricata/suricata_interfaces.php, security/pfSense-pkg-suricata/files/usr/local/www/widgets/include/widget-suricata.inc, security/pfSense-pkg-suricata/files/usr/local/www/widgets/widgets/suricata_alerts.widget.php
This update to the GUI package addresses one Redmine Bug Report and a Redmine Feature Request.
1. [Redmine Feature Request #16009](https://redmine.pfsense.org/issues/16009) - Use the built-in UNIX control socket interface to communicate certain actions to the running Suricata binary.
**Bug Fixes:**
1. [Redmine Issue #16008](https://redmine.pfsense.org/issues/16008) - Improperly double-quoted constants for SIGHUP and SIGUSR2.
=> pfSense-pkg-suricata-7.0.8_1 - Fix Redmine 16008 and implement Redmine 16009

net/pfSense-pkg-pfBlockerNG-devel/files/usr/local/pkg/pfblockerng/pfb_unbound.py
See the [2nd](https://github.com/pfsense/FreeBSD-ports/pull/1407#issuecomment-2634796462) and [3rd](https://github.com/pfsense/FreeBSD-ports/pull/1407#issuecomment-2634819227) comments of this PR and https://forum.netgate.com/topic/196164/null-blocking-servfail/10.
for more details.
=> net/pfSense-pkg-pfBlockerNG-devel: fix dual-stack null blocking. Fix #16094
